// Copyright (c) 2026 Invinite. Licensed under the MIT License.
// See the LICENSE file in the repo root for full license text.

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve as resolvePath } from "node:path";

import ts from "typescript";

import { AUTO_GENERATED_HEADER, GenDocsError } from "./genDocs.js";

type Stability = "stable" | "experimental" | "frozen";

/**
 * Phase-4 generated docs entry. The `symbolPath` points at a core export or
 * object-literal member whose JSDoc is rendered into one markdown page.
 *
 * @since 0.4
 * @experimental
 * @example
 *     const page: Phase4DocEntry = {
 *         title: "input.int",
 *         sourceRelPath: "packages/core/src/input/input.ts",
 *         symbolPath: ["input", "int"],
 *         outRelPath: "docs/primitives/input/int.md",
 *         seeAlso: "Input builders",
 *     };
 *     void page;
 */
export type Phase4DocEntry = Readonly<{
    title: string;
    sourceRelPath: string;
    symbolPath: ReadonlyArray<string>;
    outRelPath: string;
    seeAlso: string;
}>;

/**
 * Parsed Phase-4 documentation payload.
 *
 * @since 0.4
 * @experimental
 * @example
 *     const doc: Phase4DocInput = {
 *         entry: PHASE4_DOC_ENTRIES[0],
 *         description: "Build an input descriptor.",
 *         since: "0.4",
 *         stability: "stable",
 *         example: "input.int(20)",
 *         signature: "int(defaultValue: number): IntDescriptor",
 *         sourceUrl: "https://example.invalid/input.ts",
 *     };
 *     void doc;
 */
export type Phase4DocInput = Readonly<{
    entry: Phase4DocEntry;
    description: string;
    since: string;
    stability: Stability;
    example: string;
    signature: string;
    sourceUrl: string;
}>;

const CORE = "packages/core/src";

/**
 * Core Phase-4 docs generated by `chartlang docs`.
 *
 * @since 0.4
 * @experimental
 * @example
 *     const first = PHASE4_DOC_ENTRIES[0]?.title;
 *     void first;
 */
export const PHASE4_DOC_ENTRIES: ReadonlyArray<Phase4DocEntry> = Object.freeze([
    ...[
        "int",
        "float",
        "bool",
        "string",
        "enum",
        "color",
        "source",
        "time",
        "price",
        "symbol",
        "interval",
        "externalSeries",
    ].map((name) =>
        Object.freeze({
            title: `input.${name}`,
            sourceRelPath: `${CORE}/input/input.ts`,
            symbolPath: ["input", name],
            outRelPath: `docs/primitives/input/${name}.md`,
            seeAlso: "`input.*` namespace",
        }),
    ),
    ...["float", "int", "bool", "string"].flatMap((name) => [
        Object.freeze({
            title: `state.${name}`,
            sourceRelPath: `${CORE}/state/state.ts`,
            symbolPath: ["state", name],
            outRelPath: `docs/primitives/state/${name}.md`,
            seeAlso: "`state.*` namespace",
        }),
        Object.freeze({
            title: `state.tick.${name}`,
            sourceRelPath: `${CORE}/state/state.ts`,
            symbolPath: ["state", "tick", name],
            outRelPath: `docs/primitives/state/tick-${name}.md`,
            seeAlso: "`state.tick.*` namespace",
        }),
    ]),
    Object.freeze({
        title: "barstate",
        sourceRelPath: `${CORE}/views/barstate.ts`,
        symbolPath: ["barstate"],
        outRelPath: "docs/primitives/barstate.md",
        seeAlso: "`barstate.*` view",
    }),
    Object.freeze({
        title: "syminfo",
        sourceRelPath: `${CORE}/views/syminfo.ts`,
        symbolPath: ["syminfo"],
        outRelPath: "docs/primitives/syminfo.md",
        seeAlso: "`syminfo.*` view",
    }),
    Object.freeze({
        title: "timeframe",
        sourceRelPath: `${CORE}/views/timeframe.ts`,
        symbolPath: ["timeframe"],
        outRelPath: "docs/primitives/timeframe.md",
        seeAlso: "`timeframe.*` view",
    }),
    Object.freeze({
        title: "request.security",
        sourceRelPath: `${CORE}/request/request.ts`,
        symbolPath: ["request", "security"],
        outRelPath: "docs/primitives/request/security.md",
        seeAlso: "`request.*` namespace",
    }),
    ...["maxBarsBack", "format", "precision", "scale", "requiresIntervals", "shortName"].map(
        (name) =>
            Object.freeze({
                title: `defineIndicator.${name}`,
                sourceRelPath: `${CORE}/define/overrides.ts`,
                symbolPath: ["ScriptOverrides", name],
                outRelPath: `docs/primitives/define/${name}.md`,
                seeAlso: "`defineIndicator` overrides",
            }),
    ),
]);

function commentText(comment: string | ts.NodeArray<ts.JSDocComment> | undefined): string {
    if (typeof comment === "string") return comment.trim();
    return (ts.getTextOfJSDocComment(comment) ?? "").trim();
}

function tagText(tag: ts.JSDocTag): string {
    return commentText(tag.comment);
}

function findTag(tags: readonly ts.JSDocTag[], name: string): ts.JSDocTag | undefined {
    return tags.find((t) => t.tagName.text === name);
}

function stabilityOf(tags: readonly ts.JSDocTag[]): Stability | null {
    if (findTag(tags, "stable")) return "stable";
    if (findTag(tags, "experimental")) return "experimental";
    if (findTag(tags, "frozen")) return "frozen";
    return null;
}

function descriptionOf(node: ts.Node): string {
    const jsDocs = (node as ts.Node & { jsDoc?: ts.JSDoc[] }).jsDoc;
    return commentText(jsDocs?.[0]?.comment);
}

function nodeName(node: ts.Node): string | null {
    if (
        (ts.isVariableDeclaration(node) ||
            ts.isTypeAliasDeclaration(node) ||
            ts.isInterfaceDeclaration(node) ||
            ts.isFunctionDeclaration(node) ||
            ts.isMethodDeclaration(node) ||
            ts.isPropertySignature(node) ||
            ts.isPropertyAssignment(node)) &&
        node.name !== undefined
    ) {
        if (ts.isIdentifier(node.name) || ts.isStringLiteral(node.name)) return node.name.text;
    }
    return null;
}

function childrenFor(node: ts.Node): ReadonlyArray<ts.Node> {
    if (ts.isSourceFile(node)) {
        const children: ts.Node[] = [];
        for (const stmt of node.statements) {
            if (ts.isVariableStatement(stmt)) {
                children.push(...stmt.declarationList.declarations);
            } else {
                children.push(stmt);
            }
        }
        return children;
    }
    if (
        ts.isVariableDeclaration(node) &&
        node.initializer !== undefined &&
        ts.isCallExpression(node.initializer) &&
        ts.isPropertyAccessExpression(node.initializer.expression) &&
        node.initializer.expression.name.text === "freeze" &&
        node.initializer.arguments.length === 1
    ) {
        const arg = node.initializer.arguments[0];
        if (arg !== undefined && ts.isObjectLiteralExpression(arg)) return arg.properties;
    }
    if (ts.isPropertyAssignment(node)) {
        const value = node.initializer;
        if (
            ts.isCallExpression(value) &&
            ts.isPropertyAccessExpression(value.expression) &&
            value.expression.name.text === "freeze" &&
            value.arguments.length === 1
        ) {
            const arg = value.arguments[0];
            if (arg !== undefined && ts.isObjectLiteralExpression(arg)) return arg.properties;
        }
    }
    if (ts.isTypeAliasDeclaration(node)) {
        if (ts.isTypeLiteralNode(node.type)) return node.type.members;
        if (
            ts.isTypeReferenceNode(node.type) &&
            ts.isIdentifier(node.type.typeName) &&
            node.type.typeName.text === "Readonly"
        ) {
            const firstArg = node.type.typeArguments?.[0];
            if (firstArg !== undefined && ts.isTypeLiteralNode(firstArg)) return firstArg.members;
        }
    }
    return [];
}

function findSymbolTrace(
    source: ts.SourceFile,
    path: ReadonlyArray<string>,
): ReadonlyArray<ts.Node> | null {
    let current: ts.Node = source;
    const trace: ts.Node[] = [];
    for (const part of path) {
        const next = childrenFor(current).find((child) => nodeName(child) === part);
        if (next === undefined) return null;
        trace.push(next);
        current = next;
    }
    return trace;
}

function tagsFromNearest(trace: ReadonlyArray<ts.Node>, name: string): ts.JSDocTag | undefined {
    for (const node of trace.slice().reverse()) {
        const tag = findTag(ts.getJSDocTags(node), name);
        if (tag !== undefined) return tag;
    }
    return undefined;
}

function stabilityFromNearest(trace: ReadonlyArray<ts.Node>): Stability | null {
    for (const node of trace.slice().reverse()) {
        const stability = stabilityOf(ts.getJSDocTags(node));
        if (stability !== null) return stability;
    }
    return null;
}

function descriptionFromNearest(trace: ReadonlyArray<ts.Node>): string {
    for (const node of trace.slice().reverse()) {
        const description = descriptionOf(node);
        if (description.length > 0) return description;
    }
    return "";
}

function printNode(source: ts.SourceFile, node: ts.Node): string {
    const printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed, removeComments: true });
    return printer.printNode(ts.EmitHint.Unspecified, node, source);
}

function buildSourceUrl(repoUrl: string, sourceRelPath: string): string {
    const trimmed = repoUrl.replace(/\.git$/, "").replace(/\/+$/, "");
    return `${trimmed}/blob/main/${sourceRelPath}`;
}

async function loadRepoUrl(repoRoot: string): Promise<string> {
    const raw = await readFile(join(repoRoot, "packages", "cli", "package.json"), "utf8");
    const pkg = JSON.parse(raw) as { repository?: { url?: string } };
    return pkg.repository?.url ?? "https://github.com/outraday-org/chartlang.git";
}

/**
 * Parse one Phase-4 core export or member into a generated docs payload.
 *
 * @since 0.4
 * @experimental
 * @example
 *     // const doc = await parsePhase4DocEntry(process.cwd(), PHASE4_DOC_ENTRIES[0]);
 *     // void doc;
 */
export async function parsePhase4DocEntry(
    repoRoot: string,
    entry: Phase4DocEntry,
): Promise<Phase4DocInput> {
    const sourcePath = resolvePath(repoRoot, entry.sourceRelPath);
    const text = await readFile(sourcePath, "utf8");
    const source = ts.createSourceFile(sourcePath, text, ts.ScriptTarget.ES2022, true);
    const trace = findSymbolTrace(source, entry.symbolPath);
    if (trace === null) {
        throw new GenDocsError(
            "missing-symbol",
            sourcePath,
            `could not find symbol path ${entry.symbolPath.join(".")}`,
        );
    }
    const node = trace[trace.length - 1];
    if (node === undefined) {
        throw new GenDocsError("missing-symbol", sourcePath, "empty symbol path");
    }
    const since = tagsFromNearest(trace, "since");
    if (!since) throw new GenDocsError("missing-since", sourcePath, "missing @since tag");
    const example = tagsFromNearest(trace, "example");
    if (!example) throw new GenDocsError("missing-example", sourcePath, "missing @example tag");
    const stability = stabilityFromNearest(trace);
    if (stability === null) {
        throw new GenDocsError(
            "missing-stability",
            sourcePath,
            "missing @stable / @experimental / @frozen tag",
        );
    }
    const repoUrl = await loadRepoUrl(repoRoot);
    return {
        entry,
        description: descriptionFromNearest(trace),
        since: tagText(since),
        stability,
        example: tagText(example),
        signature: printNode(source, node),
        sourceUrl: buildSourceUrl(repoUrl, entry.sourceRelPath),
    };
}

/**
 * Render a Phase-4 core docs page.
 *
 * @since 0.4
 * @experimental
 * @example
 *     // const md = generatePhase4DocsPage(doc);
 *     // void md;
 */
export function generatePhase4DocsPage(input: Phase4DocInput): string {
    const lines: string[] = [];
    lines.push(AUTO_GENERATED_HEADER);
    lines.push("");
    lines.push(`# \`${input.entry.title}\``);
    lines.push("");
    lines.push(`> **Stability:** ${input.stability}`);
    lines.push(`> **Since:** ${input.since}`);
    lines.push("");
    if (input.description.length > 0) {
        lines.push(input.description);
        lines.push("");
    }
    lines.push("## Signature");
    lines.push("");
    lines.push("```ts");
    lines.push(input.signature);
    lines.push("```");
    lines.push("");
    lines.push("## Example");
    lines.push("");
    lines.push("```ts");
    lines.push(input.example);
    lines.push("```");
    lines.push("");
    lines.push("## See also");
    lines.push("");
    lines.push(`- ${input.entry.seeAlso}`);
    lines.push(`- [Source on GitHub](${input.sourceUrl})`);
    lines.push("");
    return lines.join("\n");
}

/**
 * Generate all Phase-4 core primitive docs pages.
 *
 * @since 0.4
 * @experimental
 * @example
 *     // const { written } = await runGenPhase4Docs({ repoRoot: process.cwd() });
 *     // void written;
 */
export async function runGenPhase4Docs(
    opts: Readonly<{ repoRoot: string; outRoot?: string }>,
): Promise<{
    readonly written: ReadonlyArray<string>;
}> {
    const written: string[] = [];
    for (const entry of PHASE4_DOC_ENTRIES) {
        const input = await parsePhase4DocEntry(opts.repoRoot, entry);
        const outPath = resolvePath(opts.outRoot ?? opts.repoRoot, entry.outRelPath);
        await mkdir(dirname(outPath), { recursive: true });
        await writeFile(outPath, generatePhase4DocsPage(input), "utf8");
        written.push(outPath);
    }
    return { written: written.sort() };
}
