// Copyright (c) 2026 Invinite. Licensed under the MIT License.
// See the LICENSE file in the repo root for full license text.

import fc from "fast-check";
import { describe, expect, it } from "vitest";

import type {
    ConformanceFailure,
    ConformanceReport,
    ScenarioResult,
} from "../runConformanceSuite.js";

import {
    renderConformanceJson,
    renderConformanceMarkdown,
    type ConformanceReportMeta,
} from "./renderReport.js";

const META: ConformanceReportMeta = {
    adapterName: "Canvas2D reference adapter",
    generatedBy: "@invinite-org/chartlang-conformance@1.0.0",
};

function reportFromScenarios(scenarios: ReadonlyArray<ScenarioResult>): ConformanceReport {
    const failures = scenarios.flatMap((scenario) => [...scenario.failures]);
    return Object.freeze({
        passed: scenarios.filter((scenario) => scenario.status === "pass").length,
        failed: scenarios.filter((scenario) => scenario.status === "fail").length,
        failures: Object.freeze(failures),
        scenarios: Object.freeze(scenarios.slice()),
    });
}

const EMPTY_REPORT: ConformanceReport = reportFromScenarios([]);

const FAILURE: ConformanceFailure = Object.freeze({
    scenarioId: "draw-table",
    assertionKind: "drawing-hash",
    message: "drawing-hash[<all>]: expected abc, actual def (2 emissions)",
});

describe("renderConformanceMarkdown", () => {
    it("renders an empty report", () => {
        const markdown = renderConformanceMarkdown(EMPTY_REPORT, META);
        expect(markdown).toContain("# Conformance report\n");
        expect(markdown).toContain("Adapter: Canvas2D reference adapter");
        expect(markdown).toContain("Generated by: @invinite-org/chartlang-conformance@1.0.0");
        expect(markdown).toContain("Summary: 0 passed / 0 failed / 0 total");
        expect(markdown).toContain("| scenario id | title | status |");
    });

    it("omits the failure section for an all-pass report", () => {
        const report = reportFromScenarios([
            Object.freeze({
                id: "b",
                title: "Beta",
                status: "pass",
                failures: Object.freeze([]),
            }),
            Object.freeze({
                id: "a",
                title: "Alpha",
                status: "pass",
                failures: Object.freeze([]),
            }),
        ]);
        const markdown = renderConformanceMarkdown(report, META);
        expect(markdown).toContain("| a | Alpha | pass |");
        expect(markdown).toContain("| b | Beta | pass |");
        expect(markdown).not.toContain("## Failures");
    });

    it("renders failing scenarios as fenced diff snippets", () => {
        const report = reportFromScenarios([
            Object.freeze({
                id: "draw-table",
                title: "Draw table",
                status: "fail",
                failures: Object.freeze([FAILURE]),
            }),
        ]);
        const markdown = renderConformanceMarkdown(report, META);
        expect(markdown).toContain("## Failures");
        expect(markdown).toContain("### draw-table");
        expect(markdown).toContain("```diff");
        expect(markdown).toContain(
            "- drawing-hash: drawing-hash[<all>]: expected abc, actual def (2 emissions)",
        );
    });

    it("escapes pipes in table titles", () => {
        const report = reportFromScenarios([
            Object.freeze({
                id: "pipe|id",
                title: "title | with | pipes",
                status: "pass",
                failures: Object.freeze([]),
            }),
        ]);
        expect(renderConformanceMarkdown(report, META)).toContain(
            "| pipe\\|id | title \\| with \\| pipes | pass |",
        );
    });
});

describe("renderConformanceJson", () => {
    it("renders parseable stable JSON with explicit key order", () => {
        const report = reportFromScenarios([
            Object.freeze({
                id: "draw-table",
                title: "Draw table",
                status: "fail",
                failures: Object.freeze([FAILURE]),
            }),
        ]);
        const first = renderConformanceJson(report, META);
        const second = renderConformanceJson(report, META);
        expect(first).toBe(second);
        expect(JSON.parse(first)).toEqual({
            adapterName: META.adapterName,
            generatedBy: META.generatedBy,
            passed: 0,
            failed: 1,
            scenarios: [
                {
                    id: "draw-table",
                    title: "Draw table",
                    status: "fail",
                    failures: [
                        {
                            scenarioId: "draw-table",
                            assertionKind: "drawing-hash",
                            message: "drawing-hash[<all>]: expected abc, actual def (2 emissions)",
                        },
                    ],
                },
            ],
        });
        expect(first).toMatch(
            /^\{\n {4}"adapterName": .*\n {4}"generatedBy": .*\n {4}"passed": 0,\n {4}"failed": 1,\n {4}"scenarios": /,
        );
    });

    it("round-trips empty reports", () => {
        expect(JSON.parse(renderConformanceJson(EMPTY_REPORT, META))).toEqual({
            adapterName: META.adapterName,
            generatedBy: META.generatedBy,
            passed: 0,
            failed: 0,
            scenarios: [],
        });
    });
});

const safeText = fc.stringOf(
    fc.constantFrom("a", "b", "c", "d", "e", "f", "0", "1", "2", "-", "_", " "),
    { minLength: 1, maxLength: 16 },
);

const failureArbitrary: fc.Arbitrary<ConformanceFailure> = fc.record({
    scenarioId: safeText,
    assertionKind: fc.constant("alert-count"),
    message: safeText,
});

const scenarioArbitrary: fc.Arbitrary<ScenarioResult> = fc
    .record({
        id: safeText,
        title: safeText,
        status: fc.constantFrom("pass" as const, "fail" as const),
        failures: fc.array(failureArbitrary, { maxLength: 3 }),
    })
    .map((scenario) =>
        Object.freeze({
            id: scenario.id,
            title: scenario.title,
            status: scenario.status,
            failures: Object.freeze(
                scenario.status === "pass"
                    ? []
                    : scenario.failures.map((failure) =>
                          Object.freeze({ ...failure, scenarioId: scenario.id }),
                      ),
            ),
        }),
    );

describe("conformance report rendering properties", () => {
    it("keeps table row count and JSON round-trip stable", () => {
        fc.assert(
            fc.property(fc.array(scenarioArbitrary, { maxLength: 12 }), (scenarios) => {
                const report = reportFromScenarios(scenarios);
                const markdown = renderConformanceMarkdown(report, META);
                const tableRows = markdown.split("\n").filter((line) => line.startsWith("| "));
                expect(tableRows).toHaveLength(scenarios.length + 2);

                const json = renderConformanceJson(report, META);
                expect(JSON.parse(json)).toEqual(JSON.parse(renderConformanceJson(report, META)));
            }),
            { seed: 42, numRuns: 25 },
        );
    });
});
