// Copyright (c) 2026 Invinite. Licensed under the MIT License.
// See the LICENSE file in the repo root for full license text.

import type { ConformanceFailure, ConformanceReport, ScenarioResult } from "../runConformanceSuite";

/**
 * Metadata included in generated conformance reports.
 *
 * @since 1.0
 * @stable
 * @example
 *     import type { ConformanceReportMeta } from "@invinite-org/chartlang-conformance";
 *     const meta: ConformanceReportMeta = {
 *         adapterName: "Canvas2D reference adapter",
 *         generatedBy: "@invinite-org/chartlang-conformance@1.0.0",
 *     };
 *     void meta;
 */
export type ConformanceReportMeta = {
    readonly adapterName: string;
    readonly generatedBy: string;
};

function compareScenarioId(a: ScenarioResult, b: ScenarioResult): number {
    return a.id.localeCompare(b.id);
}

function escapeMarkdownTableCell(value: string): string {
    return value.replaceAll("|", "\\|");
}

function renderFailureBlock(
    scenario: ScenarioResult,
    failures: ReadonlyArray<ConformanceFailure>,
): ReadonlyArray<string> {
    if (failures.length === 0) return [];
    return [
        "",
        `### ${scenario.id}`,
        "",
        "```diff",
        ...failures.map((failure) => `- ${failure.assertionKind}: ${failure.message}`),
        "```",
    ];
}

/**
 * Render a deterministic `CONFORMANCE.md` document for an adapter
 * report. The renderer is pure: it performs no I/O, reads no clock,
 * and sorts scenario rows by id for byte-reproducible output.
 *
 * @since 1.0
 * @stable
 * @example
 *     import { renderConformanceMarkdown } from "@invinite-org/chartlang-conformance";
 *     import type { ConformanceReport } from "@invinite-org/chartlang-conformance";
 *     const report: ConformanceReport = {
 *         passed: 0,
 *         failed: 0,
 *         failures: [],
 *         scenarios: [],
 *     };
 *     const markdown = renderConformanceMarkdown(report, {
 *         adapterName: "Demo adapter",
 *         generatedBy: "@invinite-org/chartlang-conformance@1.0.0",
 *     });
 *     void markdown;
 */
export function renderConformanceMarkdown(
    report: ConformanceReport,
    meta: ConformanceReportMeta,
): string {
    const scenarios = [...report.scenarios].sort(compareScenarioId);
    const total = report.passed + report.failed;
    const lines = [
        "# Conformance report",
        "",
        `Adapter: ${meta.adapterName}`,
        `Generated by: ${meta.generatedBy}`,
        "",
        `Summary: ${report.passed} passed / ${report.failed} failed / ${total} total`,
        "",
        "| scenario id | title | status |",
        "| --- | --- | --- |",
        ...scenarios.map(
            (scenario) =>
                `| ${escapeMarkdownTableCell(scenario.id)} | ${escapeMarkdownTableCell(scenario.title)} | ${scenario.status} |`,
        ),
    ];

    const failed = scenarios.filter((scenario) => scenario.status === "fail");
    if (failed.length > 0) {
        lines.push("", "## Failures");
        for (const scenario of failed) {
            lines.push(...renderFailureBlock(scenario, scenario.failures));
        }
    }

    return `${lines.join("\n")}\n`;
}

/**
 * Render a deterministic JSON sidecar for an adapter conformance
 * report. Keys are constructed in stable order and the result uses
 * four-space indentation with a trailing newline.
 *
 * @since 1.0
 * @stable
 * @example
 *     import { renderConformanceJson } from "@invinite-org/chartlang-conformance";
 *     import type { ConformanceReport } from "@invinite-org/chartlang-conformance";
 *     const report: ConformanceReport = {
 *         passed: 0,
 *         failed: 0,
 *         failures: [],
 *         scenarios: [],
 *     };
 *     const json = renderConformanceJson(report, {
 *         adapterName: "Demo adapter",
 *         generatedBy: "@invinite-org/chartlang-conformance@1.0.0",
 *     });
 *     void json;
 */
export function renderConformanceJson(
    report: ConformanceReport,
    meta: ConformanceReportMeta,
): string {
    const scenarios = [...report.scenarios].sort(compareScenarioId).map((scenario) => ({
        id: scenario.id,
        title: scenario.title,
        status: scenario.status,
        failures: scenario.failures.map((failure) => ({
            scenarioId: failure.scenarioId,
            assertionKind: failure.assertionKind,
            message: failure.message,
        })),
    }));
    const payload = {
        adapterName: meta.adapterName,
        generatedBy: meta.generatedBy,
        passed: report.passed,
        failed: report.failed,
        scenarios,
    };
    return `${JSON.stringify(payload, null, 4)}\n`;
}
