#!/usr/bin/env tsx
// Copyright (c) 2026 Invinite. Licensed under the MIT License.
// See the LICENSE file in the repo root for full license text.

/**
 * Bundle `src/workerBoot.ts` (and its transitive runtime / adapter-kit / core
 * imports) into a single browser-loadable ESM file at
 * `dist/worker-boot.js`. The main-side host loads this URL via
 * `new URL("./worker-boot.js", import.meta.url)` (see
 * `src/defaultWorkerFactory.ts`).
 *
 * The bundle is also published under the `./worker-boot` subpath export so
 * Vite consumers can do `new Worker(new URL("@invinite-org/chartlang-host-worker/worker-boot", import.meta.url))`
 * or `import workerCtor from "@invinite-org/chartlang-host-worker/worker-boot?worker"`.
 * The accompanying `worker-boot.d.ts` is a minimal side-effect declaration
 * so TypeScript NodeNext consumers don't error on the bare specifier.
 *
 * Pinned esbuild flags: `bundle: true`, `format: "esm"`, `platform:
 * "browser"`, `target: "es2022"`. Matches the compiler's `bundle.ts`
 * surface.
 */

import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import * as esbuild from "esbuild";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "..");

await esbuild.build({
    entryPoints: [resolve(ROOT, "src/workerBoot.ts")],
    outfile: resolve(ROOT, "dist/worker-boot.js"),
    bundle: true,
    format: "esm",
    platform: "browser",
    target: "es2022",
    sourcemap: true,
    minify: false,
});

// Minimal types stub for the `./worker-boot` subpath export. The bundle is a
// side-effect-only module the consumer feeds to `new Worker(new URL(...))` —
// it has no importable surface at the type level. Shipping an empty declaration
// keeps NodeNext consumers happy without committing a hand-written `.d.ts` to
// the source tree.
writeFileSync(
    resolve(ROOT, "dist/worker-boot.d.ts"),
    [
        "// Copyright (c) 2026 Invinite. Licensed under the MIT License.",
        "// See the LICENSE file in the repo root for full license text.",
        "// Generated by scripts/buildWorkerBoot.ts. Do not edit by hand.",
        "// The worker-boot bundle is a side-effect module loaded via",
        "// `new Worker(new URL(...))`; it has no importable type surface.",
        "export {};",
        "",
    ].join("\n"),
);
