// Copyright (c) 2026 Invinite. Licensed under the MIT License.
// See the LICENSE file in the repo root for full license text.

import { describe, expect, it } from "vitest";

import type { ScriptScaffold } from "../transform/ir.js";
import { emit } from "./emit.js";

function baseScaffold(overrides: Partial<ScriptScaffold> = {}): ScriptScaffold {
    return {
        constructor: "defineIndicator",
        apiVersion: 1,
        name: "Demo",
        shortName: null,
        overlay: true,
        format: null,
        precision: null,
        scale: null,
        maxDrawings: {},
        maxBarsBack: null,
        inputs: [],
        stateSlots: [],
        handleSlots: [],
        handleRings: [],
        computeBody: { statements: [] },
        diagnostics: [],
        ...overrides,
    };
}

describe("emit", () => {
    it("emits the auto-generated header as the first lines", () => {
        const out = emit(baseScaffold());
        expect(
            out.startsWith("// Auto-generated by @invinite-org/chartlang-pine-converter.\n"),
        ).toBe(true);
        expect(out).toContain("// Do not edit directly — re-run the converter.");
    });

    it("emits an empty-body indicator with only the constructor import", () => {
        const out = emit(baseScaffold());
        expect(out).toContain('import { defineIndicator } from "@invinite-org/chartlang-core";');
        expect(out).toContain("export default defineIndicator({");
        expect(out).toContain('name: "Demo",');
        expect(out).toContain("apiVersion: 1,");
        expect(out).toContain("overlay: true,");
        expect(out).toContain("compute({ bar }) {");
        expect(out.endsWith("});\n")).toBe(true);
    });

    it("omits overlay/format/precision/scale/shortName/maxBarsBack when null", () => {
        const out = emit(
            baseScaffold({
                overlay: null,
                format: null,
                precision: null,
                scale: null,
                shortName: null,
                maxBarsBack: null,
            }),
        );
        expect(out).not.toContain("overlay:");
        expect(out).not.toContain("format:");
        expect(out).not.toContain("precision:");
        expect(out).not.toContain("scale:");
        expect(out).not.toContain("shortName:");
        expect(out).not.toContain("maxBarsBack:");
    });

    it("emits every non-null scalar option for a fully-specified scaffold", () => {
        const out = emit(
            baseScaffold({
                shortName: "D",
                format: "percent",
                precision: 2,
                scale: "right",
                maxBarsBack: 100,
            }),
        );
        expect(out).toContain('shortName: "D",');
        expect(out).toContain('format: "percent",');
        expect(out).toContain("precision: 2,");
        expect(out).toContain('scale: "right",');
        expect(out).toContain("maxBarsBack: 100,");
    });

    it("emits all five maxDrawings buckets in fixed order, defaulting unset to 0", () => {
        const out = emit(baseScaffold({ maxDrawings: { other: 5, lines: 20 } }));
        const linesIdx = out.indexOf("lines: 20,");
        const otherIdx = out.indexOf("other: 5,");
        expect(linesIdx).toBeGreaterThan(-1);
        expect(otherIdx).toBeGreaterThan(linesIdx);
        expect(out).toContain("labels: 0,");
        expect(out).toContain("boxes: 0,");
        expect(out).toContain("polylines: 0,");
    });

    it("omits maxDrawings entirely when no bucket is set", () => {
        const out = emit(baseScaffold({ maxDrawings: {} }));
        expect(out).not.toContain("maxDrawings:");
    });

    it("emits an inputs object literal and imports `input`", () => {
        const out = emit(
            baseScaffold({
                inputs: [{ name: "len", code: "input.int(14)" }],
                computeBody: { statements: ["plot(inputs.len);"] },
            }),
        );
        expect(out).toContain("input");
        expect(out).toContain("inputs: {");
        expect(out).toContain("len: input.int(14),");
        expect(out).toContain("compute({ bar, plot, inputs }) {");
    });

    it("emits a Camp A handle slot helper + allocation inside compute", () => {
        const out = emit(
            baseScaffold({
                handleSlots: [{ name: "__lvl_handle", kind: "line" }],
                computeBody: {
                    statements: [
                        "if (__lvl_handle.current() === null) { __lvl_handle.set(draw.line({ time: bar.time, price: bar.high }, { time: bar.time, price: bar.low })); }",
                    ],
                },
            }),
        );
        expect(out).toContain("type DrawingHandle");
        expect(out).toContain("function useDrawingHandleSlot<K extends string>()");
        expect(out).toContain('const __lvl_handle = useDrawingHandleSlot<"line">();');
        expect(out).toContain("compute({ bar, draw }) {");
        expect(out).not.toContain("useDrawingHandleRing");
    });

    it("emits a Camp B ring helper + allocation with its cap", () => {
        const out = emit(
            baseScaffold({
                handleRings: [{ name: "__lvls_ring", kind: "line", cap: 50 }],
                computeBody: {
                    statements: [
                        "__lvls_ring.push(draw.line({ time: bar.time, price: bar.high }, { time: bar.time, price: bar.low }));",
                    ],
                },
            }),
        );
        expect(out).toContain("function useDrawingHandleRing<K extends string>(cap: number)");
        expect(out).toContain('const __lvls_ring = useDrawingHandleRing<"line">(50);');
        expect(out).not.toContain("useDrawingHandleSlot");
    });

    it("emits state-slot allocations from their full factory source", () => {
        const out = emit(
            baseScaffold({
                stateSlots: [{ name: "__count_state", initExpr: "state.int(0)" }],
                computeBody: { statements: ["__count_state.value += 1;"] },
            }),
        );
        expect(out).toContain("const __count_state = state.int(0);");
        expect(out).toContain("compute({ bar, state }) {");
    });

    it("emits the bar-index bridge only when the body uses __bar_index()", () => {
        const withBarIndex = emit(
            baseScaffold({ computeBody: { statements: ["const x = __bar_index();"] } }),
        );
        expect(withBarIndex).toContain("let __barCount = 0;");
        expect(withBarIndex).toContain("if (barstate.isnew) __barCount += 1;");
        expect(withBarIndex).toContain("compute({ bar, barstate }) {");

        const without = emit(baseScaffold({ computeBody: { statements: ["plot(bar.close);"] } }));
        expect(without).not.toContain("__barCount");
    });

    it("emits the __BAR_INTERVAL_MS const only when the body references it", () => {
        const out = emit(
            baseScaffold({
                computeBody: {
                    statements: ["const t = bar.time + 2 * __BAR_INTERVAL_MS;"],
                },
            }),
        );
        expect(out).toContain("const __BAR_INTERVAL_MS = 0;");
    });

    it("emits a defineDrawing constructor when the scaffold chose it", () => {
        const out = emit(baseScaffold({ constructor: "defineDrawing", overlay: null }));
        expect(out).toContain('import { defineDrawing } from "@invinite-org/chartlang-core";');
        expect(out).toContain("export default defineDrawing({");
    });
});
