// Copyright (c) 2026 Invinite. Licensed under the MIT License.
// See the LICENSE file in the repo root for full license text.

import type { ScriptScaffold } from "../transform/ir.js";
import { emitCompute } from "./emitCompute.js";
import { emitImports } from "./emitImports.js";
import { emitInputs } from "./emitInputs.js";
import { emitMaxDrawings } from "./emitMaxDrawings.js";
import { formatSource } from "./format.js";

const HEADER = [
    "// Auto-generated by @invinite-org/chartlang-pine-converter.",
    "// Do not edit directly — re-run the converter.",
];

// The `defineIndicator`/`defineDrawing` option lines preceding `compute`.
// Indicator-only overrides (`overlay`/`format`/`precision`/`scale`/
// `maxBarsBack`) are forced to `null` on a drawing scaffold by the transform
// layer, so a present value here is always emit-legal for the constructor.
function optionLines(scaffold: ScriptScaffold): string[] {
    const lines: string[] = [
        `name: ${JSON.stringify(scaffold.name)},`,
        `apiVersion: ${scaffold.apiVersion},`,
    ];
    if (scaffold.overlay !== null) lines.push(`overlay: ${scaffold.overlay},`);
    if (scaffold.shortName !== null)
        lines.push(`shortName: ${JSON.stringify(scaffold.shortName)},`);
    if (scaffold.format !== null) lines.push(`format: ${JSON.stringify(scaffold.format)},`);
    if (scaffold.precision !== null) lines.push(`precision: ${scaffold.precision},`);
    if (scaffold.scale !== null) lines.push(`scale: ${JSON.stringify(scaffold.scale)},`);
    if (scaffold.maxBarsBack !== null) lines.push(`maxBarsBack: ${scaffold.maxBarsBack},`);
    const maxDrawings = emitMaxDrawings(scaffold);
    if (maxDrawings !== null) lines.push(...maxDrawings);
    const inputs = emitInputs(scaffold);
    if (inputs !== null) lines.push(...inputs);
    return lines;
}

/**
 * Walk a fully-populated {@link ScriptScaffold} and emit the deterministic
 * chartlang `.chart.ts` source string: the auto-generated header, the
 * minimized core import, and the `export default defineIndicator/defineDrawing
 * ({ … })` block with its options + `compute` body. Pure templating — no
 * semantic decisions — so the same scaffold always yields a byte-identical
 * string. The output compiles cleanly through
 * `@invinite-org/chartlang-compiler` (the round-trip is verified by the async
 * `convertFile`, not this sync emit).
 *
 * @since 0.1
 * @stable
 * @example
 *     import { emit } from "./emit.js";
 *     declare const scaffold: import("../transform/ir.js").ScriptScaffold;
 *     emit(scaffold); // "// Auto-generated …\nimport { … } …"
 */
export function emit(scaffold: ScriptScaffold): string {
    const lines: string[] = [
        ...HEADER,
        "",
        emitImports(scaffold),
        "",
        `export default ${scaffold.constructor}({`,
        ...optionLines(scaffold),
        ...emitCompute(scaffold),
        "});",
    ];
    return formatSource(lines.join("\n"));
}
