/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestChartRouteImport } from './routes/test.chart'
import { Route as ApiScriptsRouteImport } from './routes/api/scripts'
import { Route as ApiEodRouteImport } from './routes/api/eod'
import { Route as ApiCompileRouteImport } from './routes/api/compile'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestChartRoute = TestChartRouteImport.update({
  id: '/test/chart',
  path: '/test/chart',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScriptsRoute = ApiScriptsRouteImport.update({
  id: '/api/scripts',
  path: '/api/scripts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEodRoute = ApiEodRouteImport.update({
  id: '/api/eod',
  path: '/api/eod',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompileRoute = ApiCompileRouteImport.update({
  id: '/api/compile',
  path: '/api/compile',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/compile': typeof ApiCompileRoute
  '/api/eod': typeof ApiEodRoute
  '/api/scripts': typeof ApiScriptsRoute
  '/test/chart': typeof TestChartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/compile': typeof ApiCompileRoute
  '/api/eod': typeof ApiEodRoute
  '/api/scripts': typeof ApiScriptsRoute
  '/test/chart': typeof TestChartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/compile': typeof ApiCompileRoute
  '/api/eod': typeof ApiEodRoute
  '/api/scripts': typeof ApiScriptsRoute
  '/test/chart': typeof TestChartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/compile' | '/api/eod' | '/api/scripts' | '/test/chart'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/compile' | '/api/eod' | '/api/scripts' | '/test/chart'
  id:
    | '__root__'
    | '/'
    | '/api/compile'
    | '/api/eod'
    | '/api/scripts'
    | '/test/chart'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCompileRoute: typeof ApiCompileRoute
  ApiEodRoute: typeof ApiEodRoute
  ApiScriptsRoute: typeof ApiScriptsRoute
  TestChartRoute: typeof TestChartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/chart': {
      id: '/test/chart'
      path: '/test/chart'
      fullPath: '/test/chart'
      preLoaderRoute: typeof TestChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scripts': {
      id: '/api/scripts'
      path: '/api/scripts'
      fullPath: '/api/scripts'
      preLoaderRoute: typeof ApiScriptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/eod': {
      id: '/api/eod'
      path: '/api/eod'
      fullPath: '/api/eod'
      preLoaderRoute: typeof ApiEodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/compile': {
      id: '/api/compile'
      path: '/api/compile'
      fullPath: '/api/compile'
      preLoaderRoute: typeof ApiCompileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCompileRoute: ApiCompileRoute,
  ApiEodRoute: ApiEodRoute,
  ApiScriptsRoute: ApiScriptsRoute,
  TestChartRoute: TestChartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
