// Copyright (c) 2026 Invinite. Licensed under the MIT License.
// See the LICENSE file in the repo root for full license text.

import type { ScriptManifest } from "@invinite-org/chartlang-core";

/**
 * Options accepted by `emitTypes`. `manifest` is the frozen script manifest
 * the runtime will consume; `sourcePath` is reserved so a future generator can
 * embed it into the declarations as a comment when source navigation surfaces
 * land. Phase 1 emits the same minimal `.d.ts` for every script.
 *
 * @since 0.1
 * @example
 *     const opts: EmitTypesOptions = {
 *         manifest: { } as never,
 *         sourcePath: "demo.chart.ts",
 *     };
 *     void opts;
 */
export type EmitTypesOptions = Readonly<{
    manifest: ScriptManifest;
    sourcePath: string;
}>;

/**
 * Generate the Phase-1 minimal `.d.ts` sibling for a compiled script. The
 * declarations mirror the runtime expectation in §5.2 — a default-exported
 * `CompiledScriptObject` plus the `__manifest` symbol the bundler emits at
 * the bottom of the JS. Identical content for every script in Phase 1;
 * Phase 4+ specialises per-script inputs / outputs.
 *
 * @since 0.1
 * @example
 *     // const dts = emitTypes({ manifest, sourcePath: "demo.chart.ts" });
 *     // dts.includes("export default script");
 *     const fn: typeof emitTypes = emitTypes;
 *     void fn;
 */
export function emitTypes(_opts: EmitTypesOptions): string {
    return `// auto-generated by @invinite-org/chartlang-compiler
import type { CompiledScriptObject, ScriptManifest } from "@invinite-org/chartlang-core";

declare const script: CompiledScriptObject;
export default script;

export declare const __manifest: ScriptManifest;
`;
}
