// Copyright (c) 2026 Invinite. Licensed under the MIT License.
// See the LICENSE file in the repo root for full license text.

import type { ScriptManifest } from "@invinite-org/chartlang-core";

/**
 * Options accepted by `emitTypes`. `manifest` accepts either a single
 * `ScriptManifest` (single-script files) or an array of manifests for
 * multi-export indicator-composition files. `sourcePath` is reserved so a
 * future generator can embed it into the declarations as a comment when
 * source navigation surfaces land.
 *
 * @since 0.1
 * @example
 *     const opts: EmitTypesOptions = {
 *         manifest: { } as never,
 *         sourcePath: "demo.chart.ts",
 *     };
 *     void opts;
 */
export type EmitTypesOptions = Readonly<{
    manifest: ScriptManifest | ReadonlyArray<ScriptManifest>;
    sourcePath: string;
}>;

/**
 * Generate the `.d.ts` sibling for a compiled script. Single-script files
 * with no `outputs` / `dependencies` emit the Phase-1 minimal declarations
 * byte-identically so existing snapshot tests stay green. Multi-export
 * files (array input) or single-export files carrying `outputs` /
 * `dependencies` emit per-binding typed declarations — `output<K extends
 * "title1" | "title2">(name: K): Series<number>` overloads + `withInputs`
 * typed against the binding's `inputs` schema.
 *
 * @since 0.1
 * @example
 *     // const dts = emitTypes({ manifest, sourcePath: "demo.chart.ts" });
 *     // dts.includes("export default script");
 *     const fn: typeof emitTypes = emitTypes;
 *     void fn;
 */
export function emitTypes(opts: EmitTypesOptions): string {
    const manifests: ReadonlyArray<ScriptManifest> = Array.isArray(opts.manifest)
        ? opts.manifest
        : [opts.manifest as ScriptManifest];

    if (manifests.length === 1 && !needsTypedExports(manifests[0] as ScriptManifest)) {
        return BACK_COMPAT_DTS;
    }

    return emitTypedDeclarations(manifests);
}

const BACK_COMPAT_DTS = `// auto-generated by @invinite-org/chartlang-compiler
import type { CompiledScriptObject, ScriptManifest } from "@invinite-org/chartlang-core";

declare const script: CompiledScriptObject;
export default script;

export declare const __manifest: ScriptManifest;
`;

function needsTypedExports(manifest: ScriptManifest): boolean {
    const hasOutputs = manifest.outputs !== undefined && manifest.outputs.length > 0;
    const hasDependencies = manifest.dependencies !== undefined && manifest.dependencies.length > 0;
    return hasOutputs || hasDependencies;
}

function emitTypedDeclarations(manifests: ReadonlyArray<ScriptManifest>): string {
    const lines: string[] = [
        "// auto-generated by @invinite-org/chartlang-compiler",
        'import type { CompiledScriptObject, ScriptManifest, Series } from "@invinite-org/chartlang-core";',
        "",
    ];

    for (const m of manifests) {
        const exportName = m.exportName ?? "default";
        const localName = exportName === "default" ? "script" : exportName;
        lines.push(
            `declare const ${localName}: CompiledScriptObject & {`,
            `    output${outputOverloadSignature(m)}: Series<number>;`,
            `    withInputs(overrides: ${inputsOverrideType(m)}): typeof ${localName};`,
            "};",
        );
        if (exportName === "default") {
            lines.push(`export default ${localName};`, "");
        } else {
            lines.push(`export { ${localName} };`, "");
        }
    }

    const manifestType = manifests.length > 1 ? "ReadonlyArray<ScriptManifest>" : "ScriptManifest";
    lines.push(`export declare const __manifest: ${manifestType};`, "");

    return lines.join("\n");
}

function outputOverloadSignature(manifest: ScriptManifest): string {
    const outputs = manifest.outputs ?? [];
    if (outputs.length === 0) {
        return "<K extends never>(name: K)";
    }
    const titleUnion = outputs.map((o) => JSON.stringify(o.title)).join(" | ");
    return `<K extends ${titleUnion}>(name: K)`;
}

function inputsOverrideType(manifest: ScriptManifest): string {
    const inputs = manifest.inputs;
    const keys = Object.keys(inputs);
    if (keys.length === 0) {
        return "Readonly<Record<string, never>>";
    }
    const fields: string[] = [];
    for (const key of keys) {
        const descriptor = inputs[key] as Readonly<Record<string, unknown>>;
        const tsType = descriptorToTsType(descriptor);
        fields.push(`${quoteFieldKey(key)}?: ${tsType}`);
    }
    /* v8 ignore next */
    return `Readonly<{ ${fields.join("; ")} }>`;
}

const KIND_TO_TS_TYPE: ReadonlyMap<string, string> = new Map([
    ["int", "number"],
    ["float", "number"],
    ["price", "number"],
    ["time", "number"],
    ["string", "string"],
    ["enum", "string"],
    ["color", "string"],
    ["source", "string"],
    ["symbol", "string"],
    ["interval", "string"],
    ["bool", "boolean"],
    ["external-series", "unknown"],
]);

function descriptorToTsType(descriptor: Readonly<Record<string, unknown>>): string {
    const kind = descriptor.kind;
    /* v8 ignore next 2 */
    if (typeof kind !== "string") return "unknown";
    return KIND_TO_TS_TYPE.get(kind) ?? "unknown";
}

const SAFE_FIELD_NAME = /^[A-Za-z_$][A-Za-z0-9_$]*$/;
function quoteFieldKey(key: string): string {
    /* v8 ignore next */
    return SAFE_FIELD_NAME.test(key) ? key : JSON.stringify(key);
}
