// Copyright (c) 2026 Invinite. Licensed under the MIT License.
// See the LICENSE file in the repo root for full license text.
// GENERATED by pnpm compiler:version:generate — DO NOT EDIT.
// Source of truth: packages/compiler/package.json `version`.

/**
 * Published version of `@invinite-org/chartlang-compiler` this build was cut
 * from. Stamped onto every `ScriptManifest` the compiler emits, so a consumer
 * can key an artifact cache — or fill the `compilerVersion` slot of a
 * `StateStoreKey` — from `compiled.manifest` alone.
 *
 * Annotated `string` on purpose: the inferred literal type would put the
 * exact version into the public `.d.ts` and churn it every release.
 *
 * @since 1.12
 * @stable
 * @example
 *     const v: string = COMPILER_VERSION;
 *     void v;
 */
export const COMPILER_VERSION: string = "1.13.0";
