// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineDrawing, draw } from "@invinite-org/chartlang-core";

export default defineDrawing({
        name: "Camp A line",
        apiVersion: 1,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, draw }) {
            const lvl = draw.line(bar.point(0, bar.close), bar.point(0, bar.close), { color: "#FF5252", lineWidth: 2 });
            lvl.update({ anchors: [bar.point(0, bar.close * 1.01), bar.point(0, bar.close * 0.99)] });
        },
});
