// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineDrawing, draw, state, type DrawingHandle } from "@invinite-org/chartlang-core";

export default defineDrawing({
        name: "Camp A box",
        apiVersion: 1,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, draw, state, barstate }) {
            type __HandleSlot<K extends string> = {
                kind?: K;
                current(): DrawingHandle | null;
                set(h: DrawingHandle | null): void;
            };
            function useDrawingHandleSlot<K extends string>(): __HandleSlot<K> {
                let __h: DrawingHandle | null = null;
                return { current: () => __h, set: (next) => { __h = next; } };
            }
            const __bx_handle = useDrawingHandleSlot<"rectangle">();
            if (__bx_handle.current() === null) { __bx_handle.set(draw.rectangle({ time: bar.time, price: bar.high }, { time: bar.time, price: bar.low })); }
            __bx_handle.current()?.update({ style: { fill: color.new(color.green, 80) } });
            if (barstate.islast) {  }
        },
});
