// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineDrawing, draw } from "@invinite-org/chartlang-core";

export default defineDrawing({
        name: "Camp A box",
        apiVersion: 1,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, draw }) {
            const bx = draw.rectangle(bar.point(0, bar.high), bar.point(0, bar.low));
            bx.update({ style: { fill: "#4CAF5033" } });
        },
});
