// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineDrawing, draw, type DrawingHandle } from "@invinite-org/chartlang-core";

export default defineDrawing({
        name: "Camp A delete",
        apiVersion: 1,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, draw }) {
            type HandleSlot<K extends string> = {
                kind?: K;
                current(): DrawingHandle | null;
                set(h: DrawingHandle | null): void;
            };
            function useDrawingHandleSlot<K extends string>(): HandleSlot<K> {
                let handle: DrawingHandle | null = null;
                return { current: () => handle, set: (next) => { handle = next; } };
            }
            const lvl = useDrawingHandleSlot<"line">();
            if (lvl.current() === null) { lvl.set(draw.line(bar.point(0, bar.close), bar.point(0, bar.close))); }
            lvl.current()?.update({ anchors: [bar.point(0, bar.close), bar.point(0, bar.close)] });
            lvl.current()?.remove();
            lvl.set(null);
        },
});
