// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineDrawing, draw, state, type DrawingHandle } from "@invinite-org/chartlang-core";

export default defineDrawing({
        name: "Camp A delete",
        apiVersion: 1,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, draw, state, barstate }) {
            type __HandleSlot<K extends string> = {
                kind?: K;
                current(): DrawingHandle | null;
                set(h: DrawingHandle | null): void;
            };
            function useDrawingHandleSlot<K extends string>(): __HandleSlot<K> {
                let __h: DrawingHandle | null = null;
                return { current: () => __h, set: (next) => { __h = next; } };
            }
            const __lvl_handle = useDrawingHandleSlot<"line">();
            if (__lvl_handle.current() === null) { __lvl_handle.set(draw.line({ time: bar.time, price: bar.close }, { time: bar.time, price: bar.close })); }
            __lvl_handle.current()?.update({ anchors: [{ time: bar.time, price: bar.close }] });
            __lvl_handle.current()?.remove();
            __lvl_handle.set(null);
            if (barstate.islast) {  }
            if (barstate.isfirst) {  }
        },
});
