// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineDrawing, draw, type DrawingHandle } from "@invinite-org/chartlang-core";

export default defineDrawing({
        name: "Camp B zones",
        apiVersion: 1,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, draw }) {
            type __HandleRing<K extends string> = {
                kind?: K;
                push(h: DrawingHandle | null): void;
                at(i: number): DrawingHandle | null;
                size(): number;
            };
            function useDrawingHandleRing<K extends string>(cap: number): __HandleRing<K> {
                const __buf: (DrawingHandle | null)[] = [];
                let __head = 0;
                return {
                    push: (h) => {
                        if (__buf.length < cap) {
                            __buf.push(h);
                        } else {
                            const __evicted = __buf[__head];
                            if (__evicted !== null && __evicted !== undefined) __evicted.remove();
                            __buf[__head] = h;
                            __head = (__head + 1) % cap;
                        }
                    },
                    at: (i) => (__buf.length < cap ? __buf[i] : __buf[(__head + i) % cap]) ?? null,
                    size: () => __buf.length,
                };
            }
            const __zones_ring = useDrawingHandleRing<"rectangle">(20);
            if (bar.close < bar.open) { __zones_ring.push(draw.rectangle({ time: bar.time, price: bar.high }, { time: bar.time, price: bar.low })); }
            if (bar.close < bar.open) {  }
        },
});
