// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineDrawing, draw, type DrawingHandle } from "@invinite-org/chartlang-core";

export default defineDrawing({
        name: "Camp C heuristic",
        apiVersion: 1,
        maxDrawings: {
            lines: 30,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, draw }) {
            type HandleRing<K extends string> = {
                kind?: K;
                push(h: DrawingHandle | null): void;
                at(i: number): DrawingHandle | null;
                size(): number;
            };
            function useDrawingHandleRing<K extends string>(cap: number): HandleRing<K> {
                const buffer: (DrawingHandle | null)[] = [];
                let head = 0;
                return {
                    push: (h) => {
                        if (buffer.length < cap) {
                            buffer.push(h);
                        } else {
                            const evicted = buffer[head];
                            if (evicted !== null && evicted !== undefined) evicted.remove();
                            buffer[head] = h;
                            head = (head + 1) % cap;
                        }
                    },
                    at: (i) => (buffer.length < cap ? buffer[i] : buffer[(head + i) % cap]) ?? null,
                    size: () => buffer.length,
                };
            }
            const lvls = useDrawingHandleRing<"line">(30);
            if (bar.close > bar.open) { lvls.push(draw.line(bar.point(0, bar.high), bar.point(0, bar.high))); }
        },
});
