// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineDrawing, state } from "@invinite-org/chartlang-core";

export default defineDrawing({
        name: "Camp C unbounded",
        apiVersion: 1,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, state, barstate }) {
            // [pine-converter] HARD-REJECT (unbounded-handle-collection) at 6:22 — line.new(...) — see diagnostics for the suggested rewrite.
            if (barstate.isfirst) {  }
            if (bar.close > bar.open) {  }
        },
});
