// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineDrawing } from "@invinite-org/chartlang-core";

export default defineDrawing({
        name: "Camp C linefill",
        apiVersion: 1,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar }) {
            // [pine-converter] HARD-REJECT (cross-collection-linefill) at 7:12 — linefill.new(...) — see diagnostics for the suggested rewrite.
        },
});
