// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineDrawing, draw, state, type DrawingHandle } from "@invinite-org/chartlang-core";

export default defineDrawing({
        name: "Dashboard",
        apiVersion: 1,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 2,
        },
        compute({ bar, draw, state, barstate }) {
            type HandleSlot<K extends string> = {
                kind?: K;
                current(): DrawingHandle | null;
                set(h: DrawingHandle | null): void;
            };
            function useDrawingHandleSlot<K extends string>(): HandleSlot<K> {
                let handle: DrawingHandle | null = null;
                return { current: () => handle, set: (next) => { handle = next; } };
            }
            const dash = useDrawingHandleSlot<"table">();
            const dashCells = [[{ text: "Metric" }, { text: "Value" }], [{ text: "Trend" }, { text: "Up", bgColor: "#4CAF50", textColor: "#FFFFFF" }], [{ text: "Bias" }, { text: "Long" }], [{ text: "Risk" }, { text: "Low" }], [{ text: "Score" }, { text: "A" }]];
            if (barstate.islast) { dash.current()?.remove(); dash.set(draw.table({ position: "top-right", cells: dashCells })); }
        },
});
