// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineDrawing, draw, state, type DrawingHandle } from "@invinite-org/chartlang-core";

export default defineDrawing({
        name: "Merged header",
        apiVersion: 1,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 2,
        },
        compute({ bar, draw, state, barstate }) {
            type __HandleSlot<K extends string> = {
                kind?: K;
                current(): DrawingHandle | null;
                set(h: DrawingHandle | null): void;
            };
            function useDrawingHandleSlot<K extends string>(): __HandleSlot<K> {
                let __h: DrawingHandle | null = null;
                return { current: () => __h, set: (next) => { __h = next; } };
            }
            const __t_handle = useDrawingHandleSlot<"table">();
            const __t_handle_cells = [[{ text: "Header" }, { text: "" }], [{ text: "A" }, { text: "B" }]];
            if (barstate.islast) { __t_handle.current()?.remove(); __t_handle.set(draw.table({ position: "bottom-left", cells: __t_handle_cells })); }
            if (barstate.islast) {  }
        },
});
