// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineDrawing, draw, state, type DrawingHandle } from "@invinite-org/chartlang-core";

export default defineDrawing({
        name: "Merged header",
        apiVersion: 1,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 2,
        },
        compute({ bar, draw, state, barstate }) {
            type HandleSlot<K extends string> = {
                kind?: K;
                current(): DrawingHandle | null;
                set(h: DrawingHandle | null): void;
            };
            function useDrawingHandleSlot<K extends string>(): HandleSlot<K> {
                let handle: DrawingHandle | null = null;
                return { current: () => handle, set: (next) => { handle = next; } };
            }
            const t = useDrawingHandleSlot<"table">();
            const tCells = [[{ text: "Header" }, { text: "" }], [{ text: "A" }, { text: "B" }]];
            if (barstate.islast) { t.current()?.remove(); t.set(draw.table({ position: "bottom-left", cells: tCells })); }
        },
});
