// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineDrawing, draw, state, type DrawingHandle } from "@invinite-org/chartlang-core";

export default defineDrawing({
        name: "Polyline curve",
        apiVersion: 1,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, draw, state, barstate }) {
            let barCount = 0;
            const barIndex = (): number => barCount;
            if (barstate.isnew) barCount += 1;
            type HandleSlot<K extends string> = {
                kind?: K;
                current(): DrawingHandle | null;
                set(h: DrawingHandle | null): void;
            };
            function useDrawingHandleSlot<K extends string>(): HandleSlot<K> {
                let handle: DrawingHandle | null = null;
                return { current: () => handle, set: (next) => { handle = next; } };
            }
            const pts = useDrawingHandleSlot<"polyline">();
            if (barstate.islast) { pts.current()?.remove(); pts.set(draw.curve([bar.point(-(barIndex()), bar.low), bar.point(-(barIndex()), bar.high), bar.point(-(barIndex()), bar.close)] as const, { color: "#9C27B0" })); }
        },
});
