// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, state } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "Polyline rebuild",
        apiVersion: 1,
        overlay: true,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, state, barstate }) {
            let __barCount = 0;
            const __bar_index = (): number => __barCount;
            if (barstate.isnew) __barCount += 1;
            const __pts_state = state.float((array.new < chart.point) > ([]));
            if (barstate.islast) { for (let i = 0; i <= 2; i++) { array.push(__pts_state.value, chart.point.from_index(__bar_index(), bar.close[i])); } }
        },
});
