// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineDrawing, draw } from "@invinite-org/chartlang-core";

export default defineDrawing({
        name: "Linefill two-line",
        apiVersion: 1,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, draw }) {
            const a = draw.line(bar.point(0, bar.high), bar.point(0, bar.high));
            const b = draw.line(bar.point(0, bar.low), bar.point(0, bar.low));
        },
});
