// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineDrawing, draw, state, type DrawingHandle } from "@invinite-org/chartlang-core";

export default defineDrawing({
        name: "Linefill two-line",
        apiVersion: 1,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, draw, state, barstate }) {
            type __HandleSlot<K extends string> = {
                kind?: K;
                current(): DrawingHandle | null;
                set(h: DrawingHandle | null): void;
            };
            function useDrawingHandleSlot<K extends string>(): __HandleSlot<K> {
                let __h: DrawingHandle | null = null;
                return { current: () => __h, set: (next) => { __h = next; } };
            }
            const __a_handle = useDrawingHandleSlot<"line">();
            const __b_handle = useDrawingHandleSlot<"line">();
            if (__a_handle.current() === null) { __a_handle.set(draw.line({ time: bar.time, price: bar.high }, { time: bar.time, price: bar.high })); }
            if (__b_handle.current() === null) { __b_handle.set(draw.line({ time: bar.time, price: bar.low }, { time: bar.time, price: bar.low })); }
            if (barstate.islast) {  }
        },
});
