// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineDrawing, draw, type DrawingHandle } from "@invinite-org/chartlang-core";

export default defineDrawing({
        name: "Linefill two-line",
        apiVersion: 1,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, draw }) {
            type HandleSlot<K extends string> = {
                kind?: K;
                current(): DrawingHandle | null;
                set(h: DrawingHandle | null): void;
            };
            function useDrawingHandleSlot<K extends string>(): HandleSlot<K> {
                let handle: DrawingHandle | null = null;
                return { current: () => handle, set: (next) => { handle = next; } };
            }
            const fill = useDrawingHandleSlot<"fill-between">();
            const a = draw.line(bar.point(0, bar.high), bar.point(0, bar.high));
            const b = draw.line(bar.point(0, bar.low), bar.point(0, bar.low));
            if (fill.current() === null) { fill.set(draw.fillBetween([bar.point(0, bar.high), bar.point(0, bar.high)], [bar.point(0, bar.low), bar.point(0, bar.low)], { fill: "#00897B33" })); } else { fill.current()?.update({ edgeA: [bar.point(0, bar.high), bar.point(0, bar.high)], edgeB: [bar.point(0, bar.low), bar.point(0, bar.low)] }); }
        },
});
