// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineDrawing, draw } from "@invinite-org/chartlang-core";

export default defineDrawing({
        name: "Future anchor",
        apiVersion: 1,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, draw }) {
            const lvl = draw.line(bar.point(0, bar.close), bar.point((10), bar.close), { color: "#FF5252" });
        },
});
