// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, ta, order } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "S",
        apiVersion: 1,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, ta, order }) {
            let longCond = ta.crossover(bar.close, ta.sma(bar.close, 20)).current;
            if (longCond) { order.buy({ label: "Long" }); }
        },
});
