// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, ta, plot, input } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "Inputs",
        apiVersion: 1,
        overlay: true,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        inputs: {
            len: input.int(20),
            src: input.source("close"),
        },
        compute({ bar, ta, plot, inputs }) {
            plot(ta.sma((inputs.src as number), (inputs.len as number)));
        },
});
