// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, plot, input } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "Timeframe input",
        apiVersion: 1,
        overlay: true,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        inputs: {
            tf: input.interval("1h"),
        },
        compute({ bar, plot, inputs }) {
            plot(bar.close);
        },
});
