// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineDrawing, ta, draw, input, state, type DrawingHandle } from "@invinite-org/chartlang-core";

export default defineDrawing({
        name: "Support / Resistance",
        apiVersion: 1,
        maxDrawings: {
            lines: 20,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 2,
        },
        inputs: {
            lookback: input.int(5),
            showTable: input.bool(true),
            lineColor: input.color("#FF9800"),
        },
        compute({ bar, ta, draw, inputs, state, barstate }) {
            type __HandleSlot<K extends string> = {
                kind?: K;
                current(): DrawingHandle | null;
                set(h: DrawingHandle | null): void;
            };
            function useDrawingHandleSlot<K extends string>(): __HandleSlot<K> {
                let __h: DrawingHandle | null = null;
                return { current: () => __h, set: (next) => { __h = next; } };
            }
            type __HandleRing<K extends string> = {
                kind?: K;
                push(h: DrawingHandle | null): void;
                at(i: number): DrawingHandle | null;
                size(): number;
            };
            function useDrawingHandleRing<K extends string>(cap: number): __HandleRing<K> {
                const __buf: (DrawingHandle | null)[] = [];
                let __head = 0;
                return {
                    push: (h) => {
                        if (__buf.length < cap) {
                            __buf.push(h);
                        } else {
                            const __evicted = __buf[__head];
                            if (__evicted !== null && __evicted !== undefined) __evicted.remove();
                            __buf[__head] = h;
                            __head = (__head + 1) % cap;
                        }
                    },
                    at: (i) => (__buf.length < cap ? __buf[i] : __buf[(__head + i) % cap]) ?? null,
                    size: () => __buf.length,
                };
            }
            const __lastLbl_handle = useDrawingHandleSlot<"frame">();
            const __stats_handle = useDrawingHandleSlot<"table">();
            const __levels_ring = useDrawingHandleRing<"line">(20);
            const __levels_ring = useDrawingHandleRing<"line">(20);
            if (!Number.NaN(ph)) { __levels_ring.push(draw.line({ time: bar.time, price: ph }, { time: bar.time, price: ph }, { color: lineColor, lineWidth: 2 })); }
            if (!Number.NaN(pl)) { __levels_ring.push(draw.line({ time: bar.time, price: pl }, { time: bar.time, price: pl }, { color: lineColor, lineWidth: 2 })); }
            if (__lastLbl_handle.current() === null) { __lastLbl_handle.set(draw.frame({ time: bar.time, price: bar.close }, { time: bar.time, price: bar.close }, { label: "Last close" })); }
            __lastLbl_handle.current()?.update({ body: "Close " + str.tostring(bar.close) });
            const __stats_handle_cells = [[{ text: "Levels" }, { text: str.tostring(array.size(levels)) }], [{ text: "Last close" }, { text: str.tostring(bar.close) }]];
            if (barstate.islast) { __stats_handle.current()?.remove(); __stats_handle.set(draw.table({ position: "top-right", cells: __stats_handle_cells })); }
            let ph = ta.pivotsHighLow.high(inputs.lookback, inputs.lookback);
            let pl = ta.pivotsHighLow.low(inputs.lookback, inputs.lookback);
            if (!Number.NaN(ph)) {  }
            if (!Number.NaN(pl)) {  }
            if (barstate.islast) {  }
        },
});
