// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineDrawing, ta, draw, input, state, type DrawingHandle } from "@invinite-org/chartlang-core";

export default defineDrawing({
        name: "Support / Resistance",
        apiVersion: 1,
        maxDrawings: {
            lines: 20,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 2,
        },
        inputs: {
            lookback: input.int(5),
            showTable: input.bool(true),
            lineColor: input.color("#FF9800"),
        },
        compute({ bar, ta, draw, inputs, state, barstate }) {
            type HandleSlot<K extends string> = {
                kind?: K;
                current(): DrawingHandle | null;
                set(h: DrawingHandle | null): void;
            };
            function useDrawingHandleSlot<K extends string>(): HandleSlot<K> {
                let handle: DrawingHandle | null = null;
                return { current: () => handle, set: (next) => { handle = next; } };
            }
            type HandleRing<K extends string> = {
                kind?: K;
                push(h: DrawingHandle | null): void;
                at(i: number): DrawingHandle | null;
                size(): number;
            };
            function useDrawingHandleRing<K extends string>(cap: number): HandleRing<K> {
                const buffer: (DrawingHandle | null)[] = [];
                let head = 0;
                return {
                    push: (h) => {
                        if (buffer.length < cap) {
                            buffer.push(h);
                        } else {
                            const evicted = buffer[head];
                            if (evicted !== null && evicted !== undefined) evicted.remove();
                            buffer[head] = h;
                            head = (head + 1) % cap;
                        }
                    },
                    at: (i) => (buffer.length < cap ? buffer[i] : buffer[(head + i) % cap]) ?? null,
                    size: () => buffer.length,
                };
            }
            const stats = useDrawingHandleSlot<"table">();
            const levels = useDrawingHandleRing<"line">(20);
            let ph = ta.pivotsHighLow({ leftLength: (inputs.lookback as number), rightLength: (inputs.lookback as number) }).high.current;
            let pl = ta.pivotsHighLow({ leftLength: (inputs.lookback as number), rightLength: (inputs.lookback as number) }).low.current;
            if (!!Number.isFinite(ph)) { levels.push(draw.line(bar.point(0, ph), bar.point(0, ph), { color: lineColor, lineWidth: 2 })); }
            if (!!Number.isFinite(pl)) { levels.push(draw.line(bar.point(0, pl), bar.point(0, pl), { color: lineColor, lineWidth: 2 })); }
            const lastLbl = draw.frame(bar.point(0, bar.close), bar.point(0, bar.close), { label: "Last close" });
            lastLbl.update({ body: "Close " + str.tostring(bar.close) });
            const statsCells = [[{ text: "Levels" }, { text: String(array.size(levels)) }], [{ text: "Last close" }, { text: String(bar.close) }]];
            if (barstate.islast) { stats.current()?.remove(); stats.set(draw.table({ position: "top-right", cells: statsCells })); }
        },
});
