// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, ta, plot, input } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "SMA overlay",
        apiVersion: 1,
        overlay: true,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        inputs: {
            length: input.int(20),
            src: input.source("close"),
        },
        compute({ bar, ta, plot, inputs }) {
            let ma = ta.sma((inputs.src as number), (inputs.length as number)).current;
            plot(ma, { title: "SMA", color: "#2196F3", lineWidth: 2 });
        },
});
