// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, ta, plot, input } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "ATR",
        apiVersion: 1,
        overlay: false,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        inputs: {
            length: input.int(14),
        },
        compute({ bar, ta, plot, inputs }) {
            let a = ta.atr((inputs.length as number)).current;
            plot(a, { title: "ATR", color: "#FF5252" });
        },
});
