// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, ta, plot, hline, input } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "RSI",
        apiVersion: 1,
        overlay: false,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        inputs: {
            length: input.int(14),
        },
        compute({ bar, ta, plot, hline, inputs }) {
            let r = ta.rsi(bar.close, (inputs.length as number)).current;
            plot(r, { title: "RSI", color: "#9C27B0" });
            hline(70, { title: "Overbought", color: "#787B86" });
            hline(30, { title: "Oversold", color: "#787B86" });
        },
});
