// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, ta, plot } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "EMA cross",
        apiVersion: 1,
        overlay: true,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, ta, plot }) {
            let fast = ta.ema(bar.close, 12).current;
            let slow = ta.ema(bar.close, 26).current;
            plot(fast, { title: "Fast", color: "#4CAF50" });
            plot(slow, { title: "Slow", color: "#FF5252" });
            plot(ta.crossover(fast, slow).current ? bar.close : Number.NaN, { color: "#4CAF50", style: { kind: "shape", shape: "triangle-up", size: 8 } });
        },
});
