// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, ta, plot, input } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "MACD",
        apiVersion: 1,
        overlay: false,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        inputs: {
            fast: input.int(12),
            slow: input.int(26),
            sig: input.int(9),
        },
        compute({ bar, ta, plot, inputs }) {
            const macdLineResult = ta.macd(bar.close, { fastLength: (inputs.fast as number), slowLength: (inputs.slow as number), signalLength: (inputs.sig as number) });
            plot(macdLineResult.macd.current, { title: "MACD", color: "#2196F3" });
            plot(macdLineResult.signal.current, { title: "Signal", color: "#FF9800" });
            plot(macdLineResult.hist.current, { title: "Histogram", color: "#787B86" });
        },
});
