// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, ta, plot, input } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "Bollinger Bands",
        apiVersion: 1,
        overlay: true,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        inputs: {
            length: input.int(20),
            mult: input.float(2.0),
        },
        compute({ bar, ta, plot, inputs }) {
            const middleResult = ta.bb(bar.close, (inputs.length as number), { multiplier: (inputs.mult as number) });
            plot(middleResult.middle.current, { title: "Basis", color: "#FF9800" });
            plot(middleResult.upper.current, { title: "Upper", color: "#2196F3" });
            plot(middleResult.lower.current, { title: "Lower", color: "#2196F3" });
        },
});
