// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, ta, plot, input } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "Supertrend",
        apiVersion: 1,
        overlay: true,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        inputs: {
            factor: input.float(3.0),
            atrPeriod: input.int(10),
        },
        compute({ bar, ta, plot, inputs }) {
            const stLineResult = ta.supertrend({ multiplier: (inputs.factor as number), length: (inputs.atrPeriod as number) });
            plot(stLineResult.line.current, { title: "Supertrend", color: "#4CAF50" });
        },
});
