// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, ta, plot } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "Explicit plot zorder",
        apiVersion: 1,
        overlay: true,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, ta, plot }) {
            plot(ta.sma(bar.close, 20), { title: "SMA 20", color: "#2196F3" });
            plot(ta.sma(bar.close, 50), { title: "SMA 50", color: "#FF5252" });
        },
});
