// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, plot, state } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "Rolling window array",
        apiVersion: 1,
        overlay: true,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, plot, state }) {
            const win = state.array<number>(20);
            win.push(bar.close);
            let newest = win.last();
            let prevDay = win.get(win.size - 1 - (1));
            let count = win.size;
            plot((newest + prevDay) / count);
        },
});
