// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, plot, request } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "Multi-symbol request.security",
        apiVersion: 1,
        overlay: true,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, plot, request }) {
            let aapl = request.security({ symbol: "NASDAQ:AAPL", interval: "1d" }).close.current;
            let self = request.security({ interval: "1d" }).close.current;
            plot(aapl);
            plot(self);
        },
});
