// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, bgcolor, barcolor } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "Bgcolor dynamic",
        apiVersion: 1,
        overlay: true,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, bgcolor, barcolor }) {
            bgcolor(bar.close > bar.open ? "#4CAF50" : "#FF5252", { transp: 80 });
            barcolor(bar.close > bar.open ? "#4CAF50" : "#FF5252");
        },
});
