// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, plot, input, time } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "Calendar session",
        apiVersion: 1,
        overlay: true,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        inputs: {
            sess: input.session("0930-1600"),
        },
        compute({ bar, plot, inputs, time }) {
            let dow = time.dayofweek(bar.time);
            let openTime = bar.time;
            let closeTime = time.timeClose(bar.time);
            let isWeekday = (dow >= 2) && (dow <= 6);
            plot(isWeekday ? bar.close : Number.NaN, { title: "Weekday close", color: "#2196F3" });
            plot(openTime, { title: "Bar open time" });
            plot(closeTime, { title: "Bar close time" });
            plot(dow, { title: "Day of week" });
        },
});
