// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, plot, state } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "Array reductions",
        apiVersion: 1,
        overlay: true,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, plot, state }) {
            const win = state.array<number>(20);
            win.push(bar.close);
            win.sort("desc");
            plot(win.avg());
            plot(win.sum());
            plot(win.stdev());
            plot(win.variance());
            plot(win.median());
            plot(win.range());
            plot(win.percentile(90));
            plot(win.max() - win.min());
            plot(win.includes(bar.close) ? 1 : 0);
            plot(win.indexOf(bar.close));
        },
});
