// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, plot, state } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "Volume by level",
        apiVersion: 1,
        overlay: true,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, plot, state }) {
            const levels = state.map<number, number>(1000);
            let key = Math.round(bar.close);
            let prior = (levels.get(key) ?? Number.NaN);
            levels.set(key, (!Number.isFinite(prior) ? 0 : prior) + bar.volume);
            plot((levels.get(key) ?? Number.NaN));
            plot(levels.size);
        },
});
