// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, ta, plot, input } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "Leading-op continuation",
        apiVersion: 1,
        overlay: false,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        inputs: {
            sw: input.bool(true),
        },
        compute({ bar, ta, plot, inputs }) {
            let maOk = bar.close > bar.open;
            let rsi = ta.rsi(bar.close, 14).current;
            let rsiOk = rsi > 50;
            let cond = ((maOk && rsiOk) && (!(inputs.sw as boolean))) && (bar.close > 0);
            let entry = (maOk || rsiOk) || ((bar.close > bar.open) ? maOk : rsiOk);
            plot(cond ? 1 : 0);
            plot(entry ? 1 : 0);
        },
});
