// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, ta, plot, input, state } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "Loop break counter",
        apiVersion: 1,
        overlay: false,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        inputs: {
            tol: input.int(4),
            rng: input.float(1.0, { step: 0.1 }),
        },
        compute({ bar, ta, plot, inputs, state }) {
            const ms = state.series(Number.NaN);
            ms.value = ta.ema((((bar.close - bar.close[1]) / bar.close[1]) * 100), 3).current;
            let consol_count = 0;
            for (let i = 0; i <= 4; i++) { if ((ms[i] > (inputs.rng as number)) || (ms[i] < (-(inputs.rng as number)))) { consol_count = 0; break; } consol_count += 1; }
            plot(consol_count);
        },
});
