// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, ta, plot, state } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "Loop continue",
        apiVersion: 1,
        overlay: false,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, ta, plot, state }) {
            const src = state.series(Number.NaN);
            src.value = ta.ema(bar.close, 5).current;
            let positive_count = 0;
            for (let i = 0; i <= 5; i++) { if (src[i] < 0) { continue; } if (src[i] > 100) { break; } positive_count += 1; }
            plot(positive_count);
        },
});
