// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, plot } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "Loop stateful break reject",
        apiVersion: 1,
        overlay: false,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, plot }) {
            let total = 0.0;
            plot(total);
        },
});
