// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, ta, plot, input } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "Nested ta arithmetic",
        apiVersion: 1,
        overlay: false,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        inputs: {
            scale: input.float(0.1, { step: 0.02 }),
        },
        compute({ bar, ta, plot, inputs }) {
            let r = ta.rsi(bar.close, 14).current * (inputs.scale as number);
            let w = (ta.wma((bar.high + bar.low) / 2, 5).current * 2) + 1;
            let s = (bar.close > bar.open) ? ta.ema(bar.close, 8).current : ta.sma(bar.close, 8).current;
            let y = ta.sma(ta.atr(14), 5).current;
            plot(r);
            plot(w);
            plot(s);
            plot(y);
        },
});
