// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, plot } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "UDF pure limit",
        apiVersion: 1,
        overlay: false,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, plot }) {
            const cf_limit = (input_val: number, upper_limit: number, lower_limit: number) => Math.max(Math.min(input_val, upper_limit), lower_limit);
            let clamped_close = cf_limit(bar.close, 100, 0);
            let clamped_open = cf_limit(bar.open, 50, 10);
            plot(clamped_close);
            plot(clamped_open);
        },
});
