// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, ta, plot } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "UDF stateful slope divergence",
        apiVersion: 1,
        overlay: false,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, ta, plot }) {
            let close_slope = ta.ema((((bar.close - bar.close[1]) / bar.close[1]) * 100), 3).current;
            let open_slope = ta.ema((((bar.open - bar.open[1]) / bar.open[1]) * 100), 5).current;
            plot(close_slope);
            plot(open_slope);
        },
});
