// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, ta, plot } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "Trend Wizard helpers",
        apiVersion: 1,
        overlay: false,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, ta, plot }) {
            let src = bar.close;
            let ma_1 = ta.ema(src, 8).current;
            let ma_2 = ta.ema(src, 21).current;
            let ma_1_dist = ta.sma((((src - ma_1) / ma_1) * 100), 3).current;
            let ma_2_dist = ta.sma((((src - ma_2) / ma_2) * 100), 5).current;
            let atr2 = ta.atr(14).current;
            let atr_prct2 = (atr2 / bar.close) * 100;
            let atr_short = atr_prct2;
            let atr3 = ta.atr(50).current;
            let atr_prct3 = (atr3 / bar.close) * 100;
            let atr_long = atr_prct3;
            plot(ma_1_dist);
            plot(ma_2_dist);
            plot(atr_short);
            plot(atr_long);
        },
});
