// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, ta, plot } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "Trend Wizard slope pending",
        apiVersion: 1,
        overlay: false,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, ta, plot }) {
            let ma_1 = ta.ema(bar.close, 8).current;
            let ma_2 = ta.ema(bar.close, 21).current;
            let ma_1_slope = ta.ema((((ma_1 - ma_1[1]) / ma_1[1]) * 100), 3).current;
            let ma_2_slope = ta.ema((((ma_2 - ma_2[1]) / ma_2[1]) * 100), 5).current;
            plot(ma_1_slope);
            plot(ma_2_slope);
        },
});
