// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, ta, plot, state } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "Trend Wizard slope pending",
        apiVersion: 1,
        overlay: false,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, ta, plot, state }) {
            const ma_1 = state.series(Number.NaN);
            const ma_2 = state.series(Number.NaN);
            ma_1.value = ta.ema(bar.close, 8).current;
            ma_2.value = ta.ema(bar.close, 21).current;
            let ma_1_slope = ta.ema((((ma_1.value - ma_1[1]) / ma_1[1]) * 100), 3).current;
            let ma_2_slope = ta.ema((((ma_2.value - ma_2[1]) / ma_2[1]) * 100), 5).current;
            plot(ma_1_slope);
            plot(ma_2_slope);
        },
});
