// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, plot, input } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "Preset selector",
        apiVersion: 1,
        overlay: false,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        inputs: {
            sel: input.string("X"),
        },
        compute({ bar, plot, inputs }) {
            let a = Number.NaN;
            let b = Number.NaN;
            switch ((inputs.sel as string)) { case "X": { a = 8; b = 21; break; } case "Y": { a = 4; b = 10; break; } }
            plot(a);
            plot(b);
        },
});
