// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, ta, plot, input } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "Switch as value",
        apiVersion: 1,
        overlay: false,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        inputs: {
            sel: input.string("SMA"),
        },
        compute({ bar, ta, plot, inputs }) {
            let ma = (inputs.sel as string) === "SMA" ? ta.sma(bar.close, 14).current : (inputs.sel as string) === "EMA" ? ta.ema(bar.close, 14).current : Number.NaN;
            plot(ma);
        },
});
