// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, plot, input } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "MA Type Select",
        apiVersion: 1,
        overlay: true,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        inputs: {
            ma_type: input.enum("EMA", ["SMA", "EMA"], { title: "MA Type" }),
            preset: input.enum("Fast", ["Fast", "Slow"]),
            mismatch: input.enum("Mid", ["Low", "High"], { title: "Mismatch" }),
        },
        compute({ bar, plot, inputs }) {
            let src = ((inputs.ma_type as string) == "EMA") ? bar.close : bar.open;
            plot(((inputs.preset as string) == "Fast") ? src : bar.close);
            plot(((inputs.mismatch as string) == "Low") ? bar.high : bar.low);
        },
});
