// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, ta, plot, input, type SourceField } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "MASM",
        apiVersion: 1,
        overlay: true,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        inputs: {
            ma_length: input.enum(21, [8, 21, 30, 50, 100, 200], { title: "MA Length" }),
            mult: input.enum(2.0, [1.0, 2.0, 3.0]),
            lt_trend: input.source("close", { title: "LT" }),
            smooth: input.int(14),
        },
        compute({ bar, ta, plot, inputs }) {
            let ma = ta.sma(bar.close, (inputs.ma_length as number)).current;
            let sig = ta.sma(bar[inputs.lt_trend as SourceField], (inputs.smooth as number)).current;
            plot(((inputs.ma_length as number) == 8) ? ma : sig);
            plot(ma * (inputs.mult as number));
        },
});
