// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, plot, hline } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "Color Literal Transp",
        apiVersion: 1,
        overlay: true,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, plot, hline }) {
            plot(bar.close, { title: "MA", color: "#FF990066" });
            hline(0.0, { title: "Zero", color: "#FFFFFF80" });
        },
});
