// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, plot, color } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "Color Dynamic Base",
        apiVersion: 1,
        overlay: true,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, plot }) {
            let trendCol = (bar.close > bar.open) ? color.green : color.red;
            plot(bar.close, { title: "Trend", color: color.withAlpha(trendCol, 0.5) });
            plot(bar.open, { title: "RGB", color: color.rgb((bar.close > bar.open) ? 0 : 255, 153, 0) });
        },
});
