// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, hline, draw } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "Consolidation Band",
        apiVersion: 1,
        overlay: true,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, hline, draw }) {
            let guide_consol_upper = hline(0.2);
            let guide_consol_lower = hline(-0.2);
            draw.fillBetween([bar.point(0, 0.2), bar.point(0, 0.2)], [bar.point(0, -0.2), bar.point(0, -0.2)], { fill: "#CD79DB1F" });
        },
});
