// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, plot, draw } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "Series Band",
        apiVersion: 1,
        overlay: true,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, plot, draw }) {
            let upper = plot(bar.high);
            let lower = plot(bar.low);
            draw.fillBetween([bar.point(0, bar.high), bar.point(0, bar.high)], [bar.point(0, bar.low), bar.point(0, bar.low)], { fill: "#2196F333" });
        },
});
