// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, hline } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "Fill Rejects",
        apiVersion: 1,
        overlay: true,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, hline }) {
            let u = hline(0.2);
            let l = hline(-0.2);
        },
});
