// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, ta, alert } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "Alert message + frequency",
        apiVersion: 1,
        overlay: true,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, ta, alert, syminfo }) {
            let go_long = ta.crossover(bar.close, ta.sma(bar.close, 20)).current;
            let go_short = ta.crossunder(bar.close, ta.sma(bar.close, 20)).current;
            if (go_long) { alert(('{"symbol": "' + syminfo.ticker) + '", "action": "buy"}'); } else if (go_short) { alert(('{"symbol": "' + syminfo.ticker) + '", "action": "sell"}'); }
            if (go_short) { alert("flatten " + syminfo.ticker); }
        },
});
