// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, ta, plot, request } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "Tuple security OHLCV",
        apiVersion: 1,
        overlay: true,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, ta, plot, request }) {
            const src_hi = request.security({ interval: "1d" }).high;
            const src_lo = request.security({ interval: "1d" }).low;
            plot(src_hi);
            plot(src_lo);
            plot(ta.sma(src_hi, 5));
        },
});
