// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, ta, plot, request } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "Tuple security expr",
        apiVersion: 1,
        overlay: true,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, ta, plot, request }) {
            const wk_hi = request.security({ symbol: "NASDAQ:QQQ", interval: "1w" }).high;
            const wk_trend = request.security({ symbol: "NASDAQ:QQQ", interval: "1w" }, (bar) => ta.sma(bar.close, 20));
            plot(wk_hi);
            plot(wk_trend);
        },
});
