// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, ta, plot, input } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "Plot display toggle",
        apiVersion: 1,
        overlay: true,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        inputs: {
            show: input.bool(true),
            hide: input.bool(false),
        },
        compute({ bar, ta, plot, inputs }) {
            plot(ta.sma(bar.close, 20), { visible: (inputs.show as boolean) });
            plot(ta.ema(bar.close, 20), { visible: !((inputs.hide as boolean)) });
            plot(bar.close, { visible: false });
            plot(bar.open);
            plot(bar.volume);
        },
});
