// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, plot, state, color } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "Var Color Slot",
        apiVersion: 1,
        overlay: true,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, plot, state }) {
            const trendClr = state.color("#00000000");
            trendClr.value = (bar.close > bar.open) ? color.green : color.red;
            plot(bar.close, { title: "Price", color: trendClr.value });
        },
});
