// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, plot, state } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "Var Bool History",
        apiVersion: 1,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, plot, state }) {
            const active = state.boolSeries(false);
            active.value = bar.close > bar.open;
            let wasActive = active[1];
            let wasActive2 = active[2];
            plot((wasActive && (!wasActive2)) ? 1 : 0, { title: "JustActivated" });
        },
});
