// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, plot, state } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "Var String History",
        apiVersion: 1,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, plot, state }) {
            const phase = state.stringSeries("-");
            phase.value = (bar.close > bar.open) ? "up" : "down";
            let prevPhase = phase[1];
            plot((prevPhase == "up") ? 1 : 0, { title: "PrevUp" });
        },
});
