// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, plot, state, color } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "MASM Position State",
        apiVersion: 1,
        overlay: true,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, plot, state }) {
            const long_pos_active = state.boolSeries(false);
            const short_pos_active = state.boolSeries(false);
            const long_pos_exit_clr = state.color("#00000000");
            const short_pos_exit_clr = state.color("#00000000");
            long_pos_active.value = (bar.close > bar.open) ? true : long_pos_active.value;
            short_pos_active.value = (bar.close < bar.open) ? true : short_pos_active.value;
            long_pos_exit_clr.value = (bar.close >= bar.open) ? color.green : color.red;
            short_pos_exit_clr.value = (bar.close < bar.open) ? color.red : color.green;
            let alert_trigger_go_long = !long_pos_active[1];
            let alert_trigger_flatten_short = short_pos_active[1];
            plot(bar.close, { title: "Price", color: long_pos_exit_clr.value });
            plot(alert_trigger_go_long ? 1 : 0, { title: "GoLong", color: short_pos_exit_clr.value });
            plot(alert_trigger_flatten_short ? 1 : 0, { title: "FlattenShort" });
        },
});
