// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, plot, state } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "Leading Comments",
        apiVersion: 1,
        overlay: true,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, plot, state, barstate }) {
            plot(bar.close);
            if (barstate.islast) { plot(bar.open); }
        },
});
