// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, plot, input } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "Switch subjectless",
        apiVersion: 1,
        overlay: false,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        inputs: {
            threshold: input.int(50),
            level: input.int(60),
        },
        compute({ bar, plot, inputs }) {
            let score = ((inputs.level as number) > (inputs.threshold as number)) ? 1 : ((inputs.level as number) < (inputs.threshold as number)) ? (-1) : 0;
            plot(score);
        },
});
