// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, ta, plot, input } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "Switch MA",
        apiVersion: 1,
        overlay: true,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        inputs: {
            maType: input.string("SMA"),
            len: input.int(14),
        },
        compute({ bar, ta, plot, inputs }) {
            let result2 = (inputs.maType as string) === "SMA" ? ta.sma(bar.close, (inputs.len as number)).current : (inputs.maType as string) === "EMA" ? ta.ema(bar.close, (inputs.len as number)).current : (inputs.maType as string) === "WMA" ? ta.wma(bar.close, (inputs.len as number)).current : Number.NaN;
            plot(result2);
        },
});
