// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, ta, plot, input } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "Switch pick",
        apiVersion: 1,
        overlay: true,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        inputs: {
            fast: input.int(10),
            slow: input.int(20),
        },
        compute({ bar, ta, plot, inputs }) {
            let out2 = ((inputs.fast as number) > (inputs.slow as number)) ? ta.sma(bar.close, (inputs.fast as number)).current : ta.ema(bar.close, (inputs.slow as number)).current;
            plot(out2);
        },
});
