// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, plot, input, request } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "Input-bound request.security",
        apiVersion: 1,
        overlay: true,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        inputs: {
            sym: input.symbol("NASDAQ:QQQ"),
            tf: input.interval("1d"),
        },
        compute({ bar, plot, inputs, request }) {
            let custom = request.security({ symbol: inputs.sym as string, interval: inputs.tf as string }).close;
            const hi = request.security({ symbol: inputs.sym as string, interval: inputs.tf as string }).high;
            const lo = request.security({ symbol: inputs.sym as string, interval: inputs.tf as string }).low;
            plot(custom);
            plot(hi);
            plot(lo);
        },
});
