// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, plot, input, request } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "Chart-timeframe request.security",
        apiVersion: 1,
        overlay: true,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        inputs: {
            tf: input.interval(""),
        },
        compute({ bar, plot, inputs, request }) {
            let chartclose = request.security({ interval: inputs.tf as string }).close.current;
            plot(chartclose);
        },
});
