// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, ta, plot, input } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "Input args consolidated",
        apiVersion: 1,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        inputs: {
            fast: input.int(9, { group: "MA", inline: "row", tooltip: "fast length" }),
            slow: input.int(21, { group: "MA", inline: "row", tooltip: "slow length" }),
            src: input.source("close", { group: "MA", inline: "row", tooltip: "source" }),
        },
        compute({ bar, ta, plot, inputs }) {
            plot(ta.sma((inputs.src as number), (inputs.fast as number)));
            plot(ta.sma((inputs.src as number), (inputs.slow as number)));
        },
});
