// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, plot, draw, state, color, type DrawingHandle } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "Table formatting consolidated",
        apiVersion: 1,
        overlay: true,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 2,
        },
        compute({ bar, plot, draw, state, barstate }) {
            type HandleSlot<K extends string> = {
                kind?: K;
                current(): DrawingHandle | null;
                set(h: DrawingHandle | null): void;
            };
            function useDrawingHandleSlot<K extends string>(): HandleSlot<K> {
                let handle: DrawingHandle | null = null;
                return { current: () => handle, set: (next) => { handle = next; } };
            }
            const panel = useDrawingHandleSlot<"table">();
            plot(bar.close);
            const panelCells = [[{ text: "Title", textColor: "#FFFFFF" }], [{ text: "Body", bgColor: (bar.close > bar.open) ? color.green : color.red }], [{ text: "Note" }]];
            if (barstate.islast) { panel.current()?.remove(); panel.set(draw.table({ position: "top-right", cells: panelCells })); }
        },
});
