// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, ta, plot, input, state } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "Switch trailing blank",
        apiVersion: 1,
        overlay: true,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        inputs: {
            maType: input.string("SMA"),
            len: input.int(14),
        },
        compute({ bar, ta, plot, inputs, state }) {
            const fast = state.float(0.0);
            const slow = state.float(0.0);
            switch ((inputs.maType as string)) { case "SMA": { fast.value = 8.0; slow.value = 21.0; break; } case "EMA": { fast.value = 12.0; slow.value = 26.0; break; } }
            let result2 = (inputs.maType as string) === "SMA" ? ta.sma(bar.close, (inputs.len as number)).current : (inputs.maType as string) === "EMA" ? ta.ema(bar.close, (inputs.len as number)).current : Number.NaN;
            plot(result2);
            plot(fast.value);
            plot(slow.value);
        },
});
