// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, ta, plot, state } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "Inlined Boolean History",
        apiVersion: 1,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, ta, plot, state }) {
            const ma_cross2 = state.boolSeries(false);
            const ma_cross3 = state.boolSeries(false);
            let src = bar.close;
            let ma_a = ta.sma(src, 5).current;
            let ma_b = ta.sma(src, 20).current;
            ma_cross2.value = ta.crossover(ma_a, ma_b).current;
            let counter2 = (ma_cross2.value && (!(true ? ma_cross2[1] : (ma_cross2[1] || ma_cross2[2])))) ? 1 : 0;
            let cross_ab = counter2;
            ma_cross3.value = ta.crossover(ma_b, ma_a).current;
            let counter3 = (ma_cross3.value && (!(false ? ma_cross3[1] : (ma_cross3[1] || ma_cross3[2])))) ? 1 : 0;
            let cross_ba = counter3;
            plot(cross_ab, { title: "A-B" });
            plot(cross_ba, { title: "B-A" });
        },
});
