// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, ta, plot, input, request } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "Security Expr Invariant Capture",
        apiVersion: 1,
        overlay: false,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        inputs: {
            preset: input.enum("Fast", ["Fast", "Slow"], { title: "Preset" }),
            base_len: input.int(10),
        },
        compute({ bar, ta, plot, inputs, request }) {
            let preset_len = Number.NaN;
            switch ((inputs.preset as string)) { case "Fast": { preset_len = 8; break; } case "Slow": { preset_len = 21; break; } }
            let eff_len = (inputs.base_len as number) + preset_len;
            let atr_len = Math.round(eff_len * 1.5);
            let htf_atr = request.security({ interval: "1d" }, (bar) => { let preset_len = NaN; switch ((inputs.preset as string)) { case "Fast": { preset_len = 8; break; } case "Slow": { preset_len = 21; break; } } let eff_len = (inputs.base_len as number) + preset_len; let atr_len = Math.round(eff_len * 1.5); return ta.atr(atr_len); }).current;
            const htf_hi = request.security({ symbol: "NASDAQ:QQQ", interval: "1d" }).high.current;
            const htf_sma = request.security({ symbol: "NASDAQ:QQQ", interval: "1d" }, (bar) => { let preset_len = NaN; switch ((inputs.preset as string)) { case "Fast": { preset_len = 8; break; } case "Slow": { preset_len = 21; break; } } let eff_len = (inputs.base_len as number) + preset_len; let atr_len = Math.round(eff_len * 1.5); return ta.sma(bar.close.current, atr_len); }).current;
            plot(htf_atr, { title: "HTF ATR" });
            plot(htf_hi, { title: "HTF High" });
            plot(htf_sma, { title: "HTF SMA" });
        },
});
