// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, ta, plot, input } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "Input Metadata Full",
        apiVersion: 1,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        inputs: {
            len: input.int(14, { title: "Length", group: "General", inline: "len", tooltip: "Window length", display: "data-window", confirm: true }),
            use_filter: input.bool(true, { title: "Use filter", group: "General", inline: "filter", tooltip: "Toggle filter", display: "status-line", confirm: false }),
            mode: input.enum("Fast", ["Fast", "Slow"], { title: "Mode", group: "Mode", inline: "mode", tooltip: "Preset", display: "none", confirm: true }),
        },
        compute({ bar, ta, plot, inputs }) {
            let avg = ta.sma(bar.close, (inputs.len as number)).current;
            plot((inputs.use_filter as boolean) ? avg : bar.close);
            plot(((inputs.mode as string) == "Fast") ? bar.close : bar.open);
        },
});
