// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, plot, input } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "Native Enum Input",
        apiVersion: 1,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        inputs: {
            sig: input.enum("Sell Signal", ["Buy Signal", "Sell Signal", "flat"], { title: "Entry Signal", group: "Trade", tooltip: "Choose signal" }),
        },
        compute({ bar, plot, inputs }) {
            plot(((inputs.sig as string) == "Buy Signal") ? bar.close : bar.open);
        },
});
