// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, ta, plot } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "v5 downlevel",
        apiVersion: 1,
        overlay: true,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, ta, plot }) {
            let ma = ta.sma(bar.close, 14).current;
            plot(ma);
        },
});
