// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, plot, input } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "color input defaults",
        apiVersion: 1,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        inputs: {
            c_rgb: input.color("#0DDA74"),
            c_alpha: input.color("#FF525299"),
            c_named: input.color("#FFEB3B"),
        },
        compute({ bar, plot, inputs }) {
            plot(bar.close, { color: (inputs.c_rgb as string) });
        },
});
