// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, plot, input, request } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "security dropdown + concat",
        apiVersion: 1,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        inputs: {
            sym: input.enum("AMEX:SPY", ["AMEX:SPY", "NASDAQ:QQQ"], { title: "Compare" }),
        },
        compute({ bar, plot, inputs, request }) {
            let comp = request.security({ symbol: inputs.sym as string, interval: "1d" }).close.current;
            let earn = request.security({ symbol: "ESD:AAPL", interval: "1d" }).open.current;
            plot(comp);
            plot(earn);
        },
});
