// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, plot, time } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "timestamp gate",
        apiVersion: 1,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, plot, time }) {
            let in_window = (bar.time >= time.timestamp(2019, 1, 1, 0, 0)) && (bar.time < time.timestamp(2027, 1, 1, 0, 0));
            plot(in_window ? bar.close : Number.NaN);
        },
});
