// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, plot, alert } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "na string default",
        apiVersion: 1,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, plot, alert }) {
            let msg = "";
            if (bar.close > bar.open) { msg = "up"; }
            alert(msg);
            plot(bar.close);
        },
});
