// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, plot, color } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "color free expr",
        apiVersion: 1,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, plot }) {
            let clr_green = "#0DDA74";
            let dyn = (bar.close > bar.open) ? color.withAlpha(clr_green, 1) : "#FF5252B3";
            let lbl = "#363A4599";
            plot(bar.close, { color: dyn });
        },
});
