// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, ta, plot, input, state } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "input-bound loop",
        apiVersion: 1,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        inputs: {
            tol: input.int(4, { max: 20 }),
        },
        compute({ bar, ta, plot, inputs, state }) {
            const ma = state.series(Number.NaN);
            let count = 0.0;
            ma.value = ta.sma(bar.close, 5).current;
            for (let i = 0; i <= (inputs.tol as number); i++) { count = count + ma[i]; }
            plot(count);
        },
});
