// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, plot, time } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "timenow",
        apiVersion: 1,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, plot, time }) {
            let ms_left = time.timeClose(bar.time) - time.now();
            plot(ms_left);
        },
});
