// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, plot, state } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "ohlcv-rooted local history",
        apiVersion: 1,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, plot, state }) {
            const chg = state.series(Number.NaN);
            chg.value = ((bar.close - bar.close[1]) / bar.close[1]) * 100;
            let delta = chg.value - chg[1];
            plot(chg.value);
            plot(delta);
        },
});
