// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, plot, state } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "bool series promotion",
        apiVersion: 1,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, plot, state }) {
            const spike = state.boolSeries(false);
            spike.value = bar.close > (bar.open * 1.05);
            let fresh = spike.value && (!spike[1]);
            plot(fresh ? 1 : 0);
        },
});
