// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, ta, plot, input, type SourceField } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "source input series history",
        apiVersion: 1,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        inputs: {
            src: input.source("close"),
        },
        compute({ bar, ta, plot, inputs }) {
            let delta = bar[inputs.src as SourceField] - bar[inputs.src as SourceField][1];
            plot(ta.sma(bar[inputs.src as SourceField], 14));
            plot(delta);
        },
});
