// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, plot, bgcolor, color } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "host-name collision",
        apiVersion: 1,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, plot, bgcolor }) {
            let bgcolor2 = "#00000000";
            bgcolor2 = (bar.close > bar.open) ? color.green : color.red;
            bgcolor(bgcolor2);
            plot(bar.close);
        },
});
