// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, plot, bgcolor, color } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "color na transparent",
        apiVersion: 1,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, plot, bgcolor }) {
            let c = (bar.close > bar.open) ? color.green : "#00000000";
            bgcolor(c);
            plot(bar.close);
        },
});
