// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, plot, state, request } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "rejected request.security placeholder",
        apiVersion: 1,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, plot, state, request, syminfo }) {
            const earnings = state.series(Number.NaN);
            let sym = "ESD:" + syminfo.ticker;
            earnings.value = Number.NaN /* unsupported request.security feed */;
            let changed = earnings.value != earnings[1];
            plot(changed ? 1 : 0);
        },
});
