// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, plot, state } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "history-promoted value shapes",
        apiVersion: 1,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, plot, state }) {
            const tern = state.boolSeries(false);
            const parenb = state.boolSeries(false);
            const unot = state.boolSeries(false);
            const memb = state.series(Number.NaN);
            tern.value = (bar.close > bar.open) ? true : false;
            parenb.value = (bar.close > bar.open);
            unot.value = !(bar.close > bar.open);
            memb.value = bar.close[1];
            plot(tern[1] ? 1 : 0);
            plot(parenb[1] ? 1 : 0);
            plot(unot[1] ? 1 : 0);
            plot(memb[1]);
        },
});
