// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, ta, plot, state } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "boolean ta-series history",
        apiVersion: 1,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        compute({ bar, ta, plot, state }) {
            const x = state.boolSeries(false);
            x.value = ta.crossover(bar.close, bar.open).current;
            plot(x[1] ? 1 : 0);
        },
});
