// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, ta, plot, order, input, state } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "Strategy orders",
        apiVersion: 1,
        overlay: true,
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 0,
        },
        inputs: {
            qtyIn: input.int(2),
        },
        compute({ bar, ta, plot, order, inputs, state }) {
            const hist = state.array<number>(20);
            let fast = ta.ema(bar.close, 12).current;
            let slow = ta.ema(bar.close, 26).current;
            hist.push(bar.close);
            hist.sort();
            let order2 = ta.sma(bar.close, 5).current;
            order.buy({ label: "Ambiguous" });
            plot(order2);
            if (ta.crossover(fast, slow)) { order.buy({ label: "Long" }); }
            if (ta.crossunder(fast, slow)) { order.sell({ label: "Short", qty: (inputs.qtyIn as number) }); }
            order.buy({ label: "Scale", qty: 3 });
            if (bar.close < slow) { order.close({ label: "Long" }); }
            order.close({ label: "Bracket" });
            order.close();
            plot(fast);
            plot(slow);
        },
});
