// Auto-generated by @invinite-org/chartlang-pine-converter.
// Do not edit directly — re-run the converter.

import { defineIndicator, ta, plot, hline, draw, input, state, request, color, type DrawingHandle } from "@invinite-org/chartlang-core";

export default defineIndicator({
        name: "Trend Wizard v1.0",
        apiVersion: 1,
        overlay: false,
        shortName: "Trend Wizard v1.0",
        maxDrawings: {
            lines: 50,
            labels: 50,
            boxes: 50,
            polylines: 50,
            other: 2,
        },
        inputs: {
            src_tframe: input.interval("", { inline: "1", tooltip: "Choose Timeframe used for indicator." }),
            src_symbol_custom: input.symbol("NASDAQ:QQQ", { inline: "2", tooltip: "Choose custom symbol for reference." }),
            src_symbol_swtch: input.bool(false, { inline: "2", tooltip: "Use custom symbol rather than chart symbol." }),
            outputs: input.bool(true, { inline: "6" }),
            tab_inv: input.bool(true, { inline: "6" }),
            tab_out_1: input.bool(true, { inline: "7" }),
            tab_out_2: input.bool(false, { inline: "7" }),
            tab_out_3: input.bool(false, { inline: "7" }),
            tab_out_4: input.bool(false, { inline: "7" }),
            tab_short: input.bool(true, { inline: "8" }),
            tab_med: input.bool(false, { inline: "8" }),
            tab_long: input.bool(false, { inline: "8" }),
            preset_select: input.enum("Trade Rational Default", ["Trade Rational Default", "Swing Trading", "Swing Trader Deluxe"], { title: "Preset", inline: "1" }),
            custom_ma_swtch: input.bool(true, { inline: "3" }),
            ma_1_lgth_custom: input.int(8, { inline: "4" }),
            ma_2_lgth_custom: input.int(21, { inline: "5" }),
            ma_3_lgth_custom: input.int(50, { inline: "6" }),
            ma_4_lgth_custom: input.int(145, { inline: "7" }),
            ma_5_lgth_custom: input.int(241, { inline: "8" }),
            ma_1_type_custom: input.enum("EMA", ["SMA", "EMA"], { title: "", inline: "4" }),
            ma_2_type_custom: input.enum("EMA", ["SMA", "EMA"], { title: "", inline: "5" }),
            ma_3_type_custom: input.enum("SMA", ["SMA", "EMA"], { title: "", inline: "6" }),
            ma_4_type_custom: input.enum("SMA", ["SMA", "EMA"], { title: "", inline: "7" }),
            ma_5_type_custom: input.enum("SMA", ["SMA", "EMA"], { title: "", inline: "8" }),
            ma_slopes_swtch: input.bool(false, { inline: "1" }),
            ma_deriv_swtch: input.bool(false, { inline: "1" }),
            ma_turnover_swtch: input.bool(false, { inline: "1" }),
            ma_dist_swtch: input.bool(false, { inline: "2" }),
            ma_cross_swtch: input.bool(false, { inline: "2" }),
            rsi_swtch: input.bool(false, { inline: "3" }),
            atr_short_swtch: input.bool(false, { inline: "4" }),
            atr_med_swtch: input.bool(false, { inline: "4" }),
            atr_long_swtch: input.bool(false, { inline: "4" }),
            atr_distadj_swtch: input.bool(true, { inline: "4" }),
            zero_line_swtch: input.bool(true, { inline: "5" }),
            ma1_swtch: input.bool(true, { inline: "1" }),
            ma2_swtch: input.bool(true, { inline: "2" }),
            ma3_swtch: input.bool(true, { inline: "3" }),
            ma4_swtch: input.bool(true, { inline: "4" }),
            ma5_swtch: input.bool(true, { inline: "5" }),
            ma1_factor: input.int(1, { inline: "1" }),
            ma2_factor: input.int(1, { inline: "2" }),
            ma3_factor: input.int(1, { inline: "3" }),
            ma4_factor: input.int(1, { inline: "4" }),
            ma5_factor: input.int(1, { inline: "5" }),
            ma1_slope_smooth: input.int(2, { inline: "1" }),
            ma2_slope_smooth: input.int(1, { inline: "2" }),
            ma3_slope_smooth: input.int(2, { inline: "3" }),
            ma4_slope_smooth: input.int(3, { inline: "4" }),
            ma5_slope_smooth: input.int(3, { inline: "5" }),
            ma_slope_comp_swtch: input.bool(true, { inline: "6" }),
            ma_slope_comp_type: input.enum("SMA", ["SMA", "EMA"], { title: "Comp MA Smooth", inline: "7" }),
            ma_slope_comp_smooth: input.int(1, { inline: "7" }),
            ma_slope_deriv_smooth: input.int(3, { inline: "1" }),
            ma_slope_deriv_scaling: input.float(2.0, { inline: "1", step: 0.25 }),
            ma_slope_deriv_comp_swtch: input.bool(true, { inline: "1.5" }),
            ma_slope_deriv_comp_type: input.enum("SMA", ["SMA", "EMA"], { title: "Comp MA Smooth", inline: "2" }),
            ma_slope_deriv_comp_smooth: input.int(21, { inline: "2" }),
            ma_slope_deriv_comp_scaling: input.float(5.0, { inline: "3", step: 0.5 }),
            ma1_tover_swtch: input.bool(true, { inline: "1" }),
            ma2_tover_swtch: input.bool(true, { inline: "2" }),
            ma3_tover_swtch: input.bool(true, { inline: "3" }),
            ma4_tover_swtch: input.bool(true, { inline: "4" }),
            ma5_tover_swtch: input.bool(true, { inline: "5" }),
            ma1_tover_smooth: input.int(8, { inline: "1" }),
            ma2_tover_smooth: input.int(8, { inline: "2" }),
            ma3_tover_smooth: input.int(8, { inline: "3" }),
            ma4_tover_smooth: input.int(8, { inline: "4" }),
            ma5_tover_smooth: input.int(8, { inline: "5" }),
            ma_tover_comp_swtch: input.bool(false, { inline: "6" }),
            ma_tover_plot_type: input.enum("Line", ["Line", "Histo"], { title: "Plot Type", inline: "7" }),
            ma_tover_scaling: input.float(1.0, { inline: "8", step: 0.05 }),
            ma1_dist_swtch: input.bool(true, { inline: "1" }),
            ma2_dist_swtch: input.bool(true, { inline: "2" }),
            ma3_dist_swtch: input.bool(true, { inline: "3" }),
            ma4_dist_swtch: input.bool(true, { inline: "4" }),
            ma5_dist_swtch: input.bool(true, { inline: "5" }),
            ma1_dist_smooth: input.int(3, { inline: "1" }),
            ma2_dist_smooth: input.int(4, { inline: "2" }),
            ma3_dist_smooth: input.int(5, { inline: "3" }),
            ma4_dist_smooth: input.int(8, { inline: "4" }),
            ma5_dist_smooth: input.int(10, { inline: "5" }),
            ma_dist_comp_swtch: input.bool(true, { inline: "6" }),
            ma_dist_scaling: input.float(0.1, { inline: "7", step: 0.01 }),
            ma12_cross_swtch: input.bool(true, { inline: "1" }),
            ma23_cross_swtch: input.bool(false, { inline: "2" }),
            ma34_cross_swtch: input.bool(false, { inline: "3" }),
            ma45_cross_swtch: input.bool(false, { inline: "4" }),
            ma12_cross_smooth: input.int(1, { inline: "1" }),
            ma23_cross_smooth: input.int(1, { inline: "2" }),
            ma34_cross_smooth: input.int(1, { inline: "3" }),
            ma45_cross_smooth: input.int(1, { inline: "4" }),
            ma12_cross_excl: input.enum("2", ["0", "1", "2"], { title: "Excl", inline: "1" }),
            ma23_cross_excl: input.enum("2", ["0", "1", "2"], { title: "Excl", inline: "2" }),
            ma34_cross_excl: input.enum("2", ["0", "1", "2"], { title: "Excl", inline: "3" }),
            ma45_cross_excl: input.enum("2", ["0", "1", "2"], { title: "Excl", inline: "4" }),
            ma_cross_comp_swtch: input.bool(false, { inline: "5" }),
            ma_cross_comp_smooth: input.int(1, { inline: "5" }),
            ma_cross_scaling: input.float(1.0, { inline: "7", step: 0.25 }),
            rsi_ma_length: input.int(14, { inline: "1" }),
            rsi_ma_smooth: input.int(4, { inline: "1" }),
            rsi_plot_swtch: input.bool(false, { inline: "2" }),
            rsi_ma_swtch: input.bool(true, { inline: "2" }),
            rsi_ma_slope_swtch: input.bool(false, { inline: "2" }),
            rsi_scaling: input.float(0.1, { inline: "4", step: 0.02 }),
            rsi_ma_slope_scaling: input.float(2.5, { inline: "4", step: 0.25 }),
            rsi_center: input.bool(true, { inline: "5" }),
            test_int_1: input.int(1, { inline: "6" }),
            test_int_2: input.int(1, { inline: "6" }),
            test_float_1: input.float(1.0, { inline: "7", step: 0.25 }),
            test_float_2: input.float(0.0, { inline: "7", step: 0.05 }),
            test_bool_1: input.bool(true, { inline: "8" }),
            test_bool_2: input.bool(true, { inline: "8" }),
            test_bool_3: input.bool(true, { inline: "8" }),
            inlineInput: input.float(1.1, { step: 0.1 }),
            inlineInput2: input.float(1.35, { step: 0.1 }),
            inlineInput3: input.float(1.9, { step: 0.1 }),
        },
        compute({ bar, ta, plot, hline, draw, inputs, state, request, barstate }) {
            type HandleSlot<K extends string> = {
                kind?: K;
                current(): DrawingHandle | null;
                set(h: DrawingHandle | null): void;
            };
            function useDrawingHandleSlot<K extends string>(): HandleSlot<K> {
                let handle: DrawingHandle | null = null;
                return { current: () => handle, set: (next) => { handle = next; } };
            }
            const ma_1_slope = state.series(Number.NaN);
            const ma_2_slope = state.series(Number.NaN);
            const ma_3_slope = state.series(Number.NaN);
            const ma_4_slope = state.series(Number.NaN);
            const ma_5_slope = state.series(Number.NaN);
            const ma_slope_comp = state.series(Number.NaN);
            const ma_1 = state.series(Number.NaN);
            const ma_2 = state.series(Number.NaN);
            const ma_3 = state.series(Number.NaN);
            const ma_4 = state.series(Number.NaN);
            const ma_5 = state.series(Number.NaN);
            const rsi_ma = state.series(Number.NaN);
            const ma_cross2 = state.boolSeries(false);
            const ma_cross3 = state.boolSeries(false);
            const ma_cross4 = state.boolSeries(false);
            const ma_cross5 = state.boolSeries(false);
            const trendTable = useDrawingHandleSlot<"table">();
            const cf_limit = (input_val: number, upper_limit: number, lower_limit: number) => { let input_limited = Math.max(Math.min(input_val, upper_limit), lower_limit); return input_limited; };
            const cf_tab_madist = (ma_shrt: number, ma_lng: number, scale_pre_limit: number, atr: number, transp_pre_limit: number, limit_upper: number, limit_lower: number, scale_post_limit: number) => { let ma_dist = Math.abs((ma_lng - ma_shrt) / ma_shrt); let ma_dist_adj = ((ma_dist * scale_pre_limit) / atr) + transp_pre_limit; let limited = cf_limit(ma_dist_adj, limit_upper, limit_lower); let final = (limited * scale_post_limit) + 1; return final; };
            const get_dynamic_color = (val: number) => { let abs_val = Math.abs(val); let trans = Math.round(80 - (abs_val * 80)); let base_color = (val > 0.02) ? "#26CE9B" : ((val < (-0.02)) ? "#FF5252" : "#787B86"); return color.withAlpha(base_color, (100 - trans) / 100); };
            const format_trend_text = (val: number) => { let arrow = (val > 0.05) ? "▲ " : ((val < (-0.05)) ? "▼ " : ""); return (arrow + String(Math.abs(Math.round(val * 100)))) + "%"; };
            let menue_0 = "Table";
            let menue_1 = "Display";
            let menue_1_1 = "Indicator";
            let menue_1_2 = "__________________Development Elements__________________";
            let menue_2 = "MA Slope";
            let menue_3 = "MA Slope Derivative";
            let menue_4 = "MA Slope Turnover";
            let menue_5 = "MA Distance";
            let menue_6 = "MAs Crossing";
            let menue_8 = "RSI - Relative Strength";
            let menue_10 = "________________________TESTING________________________";
            let ma_1_lgth_preset = Number.NaN;
            let ma_2_lgth_preset = Number.NaN;
            let ma_3_lgth_preset = Number.NaN;
            let ma_4_lgth_preset = Number.NaN;
            let ma_5_lgth_preset = Number.NaN;
            let ma_1_type_preset = "";
            let ma_2_type_preset = "";
            let ma_3_type_preset = "";
            let ma_4_type_preset = "";
            let ma_5_type_preset = "";
            let src_chart = request.security({ interval: inputs.src_tframe as string }).close.current;
            let src_custom = request.security({ symbol: inputs.src_symbol_custom as string, interval: inputs.src_tframe as string }).close.current;
            let src = (inputs.src_symbol_swtch as boolean) ? src_custom : src_chart;
            const src_custom_hi = request.security({ symbol: inputs.src_symbol_custom as string, interval: inputs.src_tframe as string }).high.current;
            const src_custom_lo = request.security({ symbol: inputs.src_symbol_custom as string, interval: inputs.src_tframe as string }).low.current;
            let src_hi = (inputs.src_symbol_swtch as boolean) ? src_custom_hi : bar.high.current;
            let src_lo = (inputs.src_symbol_swtch as boolean) ? src_custom_lo : bar.low.current;
            switch ((inputs.preset_select as string)) { case "Trade Rational Default": { ma_1_lgth_preset = 8; ma_2_lgth_preset = 21; ma_3_lgth_preset = 50; ma_4_lgth_preset = 145; ma_5_lgth_preset = 241; ma_1_type_preset = "EMA"; ma_2_type_preset = "EMA"; ma_3_type_preset = "SMA"; ma_4_type_preset = "SMA"; ma_5_type_preset = "SMA"; break; } case "Swing Trading": { ma_1_lgth_preset = 4; ma_2_lgth_preset = 10; ma_3_lgth_preset = 25; ma_4_lgth_preset = 50; ma_5_lgth_preset = 100; ma_1_type_preset = "EMA"; ma_2_type_preset = "EMA"; ma_3_type_preset = "EMA"; ma_4_type_preset = "EMA"; ma_5_type_preset = "EMA"; break; } }
            let ma_1_lgth = (inputs.custom_ma_swtch as boolean) ? (inputs.ma_1_lgth_custom as number) : ma_1_lgth_preset;
            let ma_2_lgth = (inputs.custom_ma_swtch as boolean) ? (inputs.ma_2_lgth_custom as number) : ma_2_lgth_preset;
            let ma_3_lgth = (inputs.custom_ma_swtch as boolean) ? (inputs.ma_3_lgth_custom as number) : ma_3_lgth_preset;
            let ma_4_lgth = (inputs.custom_ma_swtch as boolean) ? (inputs.ma_4_lgth_custom as number) : ma_4_lgth_preset;
            let ma_5_lgth = (inputs.custom_ma_swtch as boolean) ? (inputs.ma_5_lgth_custom as number) : ma_5_lgth_preset;
            let ma_1_type = (inputs.custom_ma_swtch as boolean) ? (inputs.ma_1_type_custom as string) : ma_1_type_preset;
            let ma_2_type = (inputs.custom_ma_swtch as boolean) ? (inputs.ma_2_type_custom as string) : ma_2_type_preset;
            let ma_3_type = (inputs.custom_ma_swtch as boolean) ? (inputs.ma_3_type_custom as string) : ma_3_type_preset;
            let ma_4_type = (inputs.custom_ma_swtch as boolean) ? (inputs.ma_4_type_custom as string) : ma_4_type_preset;
            let ma_5_type = (inputs.custom_ma_swtch as boolean) ? (inputs.ma_5_type_custom as string) : ma_5_type_preset;
            let result2 = ma_1_type === "SMA" ? ta.sma(src, ma_1_lgth).current : ma_1_type === "EMA" ? ta.ema(src, ma_1_lgth).current : ma_1_type === "WMA" ? ta.wma(src, ma_1_lgth).current : ma_1_type === "HMA" ? ta.hma(src, ma_1_lgth).current : Number.NaN;
            ma_1.value = result2;
            let result3 = ma_2_type === "SMA" ? ta.sma(src, ma_2_lgth).current : ma_2_type === "EMA" ? ta.ema(src, ma_2_lgth).current : ma_2_type === "WMA" ? ta.wma(src, ma_2_lgth).current : ma_2_type === "HMA" ? ta.hma(src, ma_2_lgth).current : Number.NaN;
            ma_2.value = result3;
            let result4 = ma_3_type === "SMA" ? ta.sma(src, ma_3_lgth).current : ma_3_type === "EMA" ? ta.ema(src, ma_3_lgth).current : ma_3_type === "WMA" ? ta.wma(src, ma_3_lgth).current : ma_3_type === "HMA" ? ta.hma(src, ma_3_lgth).current : Number.NaN;
            ma_3.value = result4;
            let result5 = ma_4_type === "SMA" ? ta.sma(src, ma_4_lgth).current : ma_4_type === "EMA" ? ta.ema(src, ma_4_lgth).current : ma_4_type === "WMA" ? ta.wma(src, ma_4_lgth).current : ma_4_type === "HMA" ? ta.hma(src, ma_4_lgth).current : Number.NaN;
            ma_4.value = result5;
            let result6 = ma_5_type === "SMA" ? ta.sma(src, ma_5_lgth).current : ma_5_type === "EMA" ? ta.ema(src, ma_5_lgth).current : ma_5_type === "WMA" ? ta.wma(src, ma_5_lgth).current : ma_5_type === "HMA" ? ta.hma(src, ma_5_lgth).current : Number.NaN;
            ma_5.value = result6;
            let atr_short_lgth = Math.round(((ma_1_lgth + ma_2_lgth) / 2) * 4.5);
            let atr_med_lgth = Math.round(((ma_2_lgth + ma_3_lgth) / 2) * 4.0);
            let atr_long_lgth = Math.round(((ma_4_lgth + ma_5_lgth) / 2) * 1.4);
            let atr2 = ta.atr(atr_short_lgth).current;
            let atr_prct2 = (atr2 / bar.close) * 100;
            let atr_short_chart = atr_prct2;
            let atr3 = ta.atr(atr_med_lgth).current;
            let atr_prct3 = (atr3 / bar.close) * 100;
            let atr_med_chart = atr_prct3;
            let atr4 = ta.atr(atr_long_lgth).current;
            let atr_prct4 = (atr4 / bar.close) * 100;
            let atr_long_chart = atr_prct4;
            const atr_short_custom = request.security({ symbol: inputs.src_symbol_custom as string, interval: inputs.src_tframe as string }, (bar) => { let ma_1_lgth_preset = NaN; let ma_2_lgth_preset = NaN; let ma_3_lgth_preset = NaN; let ma_4_lgth_preset = NaN; let ma_5_lgth_preset = NaN; let ma_1_type_preset = ""; let ma_2_type_preset = ""; let ma_3_type_preset = ""; let ma_4_type_preset = ""; let ma_5_type_preset = ""; switch ((inputs.preset_select as string)) { case "Trade Rational Default": { ma_1_lgth_preset = 8; ma_2_lgth_preset = 21; ma_3_lgth_preset = 50; ma_4_lgth_preset = 145; ma_5_lgth_preset = 241; ma_1_type_preset = "EMA"; ma_2_type_preset = "EMA"; ma_3_type_preset = "SMA"; ma_4_type_preset = "SMA"; ma_5_type_preset = "SMA"; break; } case "Swing Trading": { ma_1_lgth_preset = 4; ma_2_lgth_preset = 10; ma_3_lgth_preset = 25; ma_4_lgth_preset = 50; ma_5_lgth_preset = 100; ma_1_type_preset = "EMA"; ma_2_type_preset = "EMA"; ma_3_type_preset = "EMA"; ma_4_type_preset = "EMA"; ma_5_type_preset = "EMA"; break; } } let ma_1_lgth = (inputs.custom_ma_swtch as boolean) ? (inputs.ma_1_lgth_custom as number) : ma_1_lgth_preset; let ma_2_lgth = (inputs.custom_ma_swtch as boolean) ? (inputs.ma_2_lgth_custom as number) : ma_2_lgth_preset; let atr_short_lgth = Math.round(((ma_1_lgth + ma_2_lgth) / 2) * 4.5); let atr5 = ta.atr(atr_short_lgth).current; let atr_prct5 = (atr5 / bar.close.current) * 100; return atr_prct5; }).current;
            const atr_med_custom = request.security({ symbol: inputs.src_symbol_custom as string, interval: inputs.src_tframe as string }, (bar) => { let ma_1_lgth_preset = NaN; let ma_2_lgth_preset = NaN; let ma_3_lgth_preset = NaN; let ma_4_lgth_preset = NaN; let ma_5_lgth_preset = NaN; let ma_1_type_preset = ""; let ma_2_type_preset = ""; let ma_3_type_preset = ""; let ma_4_type_preset = ""; let ma_5_type_preset = ""; switch ((inputs.preset_select as string)) { case "Trade Rational Default": { ma_1_lgth_preset = 8; ma_2_lgth_preset = 21; ma_3_lgth_preset = 50; ma_4_lgth_preset = 145; ma_5_lgth_preset = 241; ma_1_type_preset = "EMA"; ma_2_type_preset = "EMA"; ma_3_type_preset = "SMA"; ma_4_type_preset = "SMA"; ma_5_type_preset = "SMA"; break; } case "Swing Trading": { ma_1_lgth_preset = 4; ma_2_lgth_preset = 10; ma_3_lgth_preset = 25; ma_4_lgth_preset = 50; ma_5_lgth_preset = 100; ma_1_type_preset = "EMA"; ma_2_type_preset = "EMA"; ma_3_type_preset = "EMA"; ma_4_type_preset = "EMA"; ma_5_type_preset = "EMA"; break; } } let ma_2_lgth = (inputs.custom_ma_swtch as boolean) ? (inputs.ma_2_lgth_custom as number) : ma_2_lgth_preset; let ma_3_lgth = (inputs.custom_ma_swtch as boolean) ? (inputs.ma_3_lgth_custom as number) : ma_3_lgth_preset; let atr_med_lgth = Math.round(((ma_2_lgth + ma_3_lgth) / 2) * 4.0); let atr6 = ta.atr(atr_med_lgth).current; let atr_prct6 = (atr6 / bar.close.current) * 100; return atr_prct6; }).current;
            const atr_long_custom = request.security({ symbol: inputs.src_symbol_custom as string, interval: inputs.src_tframe as string }, (bar) => { let ma_1_lgth_preset = NaN; let ma_2_lgth_preset = NaN; let ma_3_lgth_preset = NaN; let ma_4_lgth_preset = NaN; let ma_5_lgth_preset = NaN; let ma_1_type_preset = ""; let ma_2_type_preset = ""; let ma_3_type_preset = ""; let ma_4_type_preset = ""; let ma_5_type_preset = ""; switch ((inputs.preset_select as string)) { case "Trade Rational Default": { ma_1_lgth_preset = 8; ma_2_lgth_preset = 21; ma_3_lgth_preset = 50; ma_4_lgth_preset = 145; ma_5_lgth_preset = 241; ma_1_type_preset = "EMA"; ma_2_type_preset = "EMA"; ma_3_type_preset = "SMA"; ma_4_type_preset = "SMA"; ma_5_type_preset = "SMA"; break; } case "Swing Trading": { ma_1_lgth_preset = 4; ma_2_lgth_preset = 10; ma_3_lgth_preset = 25; ma_4_lgth_preset = 50; ma_5_lgth_preset = 100; ma_1_type_preset = "EMA"; ma_2_type_preset = "EMA"; ma_3_type_preset = "EMA"; ma_4_type_preset = "EMA"; ma_5_type_preset = "EMA"; break; } } let ma_4_lgth = (inputs.custom_ma_swtch as boolean) ? (inputs.ma_4_lgth_custom as number) : ma_4_lgth_preset; let ma_5_lgth = (inputs.custom_ma_swtch as boolean) ? (inputs.ma_5_lgth_custom as number) : ma_5_lgth_preset; let atr_long_lgth = Math.round(((ma_4_lgth + ma_5_lgth) / 2) * 1.4); let atr7 = ta.atr(atr_long_lgth).current; let atr_prct7 = (atr7 / bar.close.current) * 100; return atr_prct7; }).current;
            let atr_short = (inputs.src_symbol_swtch as boolean) ? atr_short_custom : atr_short_chart;
            let atr_med = (inputs.src_symbol_swtch as boolean) ? atr_med_custom : atr_med_chart;
            let atr_long = (inputs.src_symbol_swtch as boolean) ? atr_long_custom : atr_long_chart;
            let atr_hilo_prct = (Math.abs(src_hi - src_lo) / src_lo) * 100;
            let atr_short_own = ta.sma(atr_hilo_prct, atr_short_lgth).current;
            let atr_med_own = ta.sma(atr_hilo_prct, atr_med_lgth).current;
            let atr_long_own = ta.sma(atr_hilo_prct, atr_long_lgth).current;
            let atr_short_avg = ta.wma(((atr_short + atr_short_own) / 2), Math.round(atr_short_lgth * 0.6)).current;
            let atr_med_avg = ta.wma(((atr_med + atr_med_own) / 2), Math.round(atr_med_lgth * 0.5)).current;
            let atr_long_avg = ta.wma(((atr_long + atr_long_own) / 2), Math.round(atr_long_lgth * 0.2)).current;
            let atr_short_avg_dist = ta.wma(atr_short_avg, Math.round(atr_short_lgth * 8.0)).current;
            let atr_med_avg_dist = ta.wma(atr_med_avg, Math.round(atr_med_lgth * 3.5)).current;
            let atr_long_avg_dist = ta.wma(atr_long_avg, Math.round(atr_long_lgth * 1.0)).current;
            let atr_short_dist = ta.wma(((((Math.abs((ma_2.value - ma_1.value) / ma_1.value) * 30) / atr_short_avg_dist) * 2) + 1), Math.round(atr_short_lgth * 1.5)).current;
            let atr_med_dist = ta.wma(((((Math.abs((ma_3.value - ma_2.value) / ma_2.value) * 30) / atr_med_avg_dist) * 0.85) + 1), Math.round(atr_med_lgth * 1.2)).current;
            let atr_long_dist = ta.wma(((((Math.abs((ma_5.value - ma_4.value) / ma_4.value) * 30) / atr_long_avg_dist) * 0.3) + 1), Math.round(atr_long_lgth * 1.0)).current;
            let atr_short_adj = atr_short_avg / ((inputs.atr_distadj_swtch as boolean) ? atr_short_dist : 1);
            let atr_med_adj = atr_med_avg / ((inputs.atr_distadj_swtch as boolean) ? atr_med_dist : 1);
            let atr_long_adj = atr_long_avg / ((inputs.atr_distadj_swtch as boolean) ? atr_long_dist : 1);
            ma_1_slope.value = ta.ema((((ma_1.value - ma_1[1]) / ma_1[1]) * 100), (inputs.ma1_slope_smooth as number)).current;
            ma_2_slope.value = ta.ema((((ma_2.value - ma_2[1]) / ma_2[1]) * 100), (inputs.ma2_slope_smooth as number)).current;
            ma_3_slope.value = ta.ema((((ma_3.value - ma_3[1]) / ma_3[1]) * 100), (inputs.ma3_slope_smooth as number)).current;
            ma_4_slope.value = ta.ema((((ma_4.value - ma_4[1]) / ma_4[1]) * 100), (inputs.ma4_slope_smooth as number)).current;
            ma_5_slope.value = ta.ema((((ma_5.value - ma_5[1]) / ma_5[1]) * 100), (inputs.ma5_slope_smooth as number)).current;
            let ma_slope_comp_pre = (((((inputs.ma1_swtch as boolean) ? (ma_1_slope.value / (inputs.ma1_factor as number)) : 0) + ((inputs.ma2_swtch as boolean) ? (ma_2_slope.value / (inputs.ma2_factor as number)) : 0)) + ((inputs.ma3_swtch as boolean) ? (ma_3_slope.value / (inputs.ma3_factor as number)) : 0)) + ((inputs.ma4_swtch as boolean) ? (ma_4_slope.value / (inputs.ma4_factor as number)) : 0)) + ((inputs.ma5_swtch as boolean) ? (ma_5_slope.value / (inputs.ma5_factor as number)) : 0);
            ma_slope_comp.value = ((inputs.ma_slope_comp_type as string) == "SMA") ? ta.sma(ma_slope_comp_pre, (inputs.ma_slope_comp_smooth as number)).current : ta.ema(ma_slope_comp_pre, (inputs.ma_slope_comp_smooth as number)).current;
            let ma_1_slope_deriv = ta.sma(ma_1_slope.value - ma_1_slope[1], (inputs.ma_slope_deriv_smooth as number)).current;
            let ma_2_slope_deriv = ta.sma(ma_2_slope.value - ma_2_slope[1], (inputs.ma_slope_deriv_smooth as number)).current;
            let ma_3_slope_deriv = ta.sma(ma_3_slope.value - ma_3_slope[1], (inputs.ma_slope_deriv_smooth as number)).current;
            let ma_4_slope_deriv = ta.sma(ma_4_slope.value - ma_4_slope[1], (inputs.ma_slope_deriv_smooth as number)).current;
            let ma_5_slope_deriv = ta.sma(ma_5_slope.value - ma_5_slope[1], (inputs.ma_slope_deriv_smooth as number)).current;
            let ma_slope_deriv_comp = (((inputs.ma_slope_deriv_comp_type as string) == "SMA") ? ta.sma(ma_slope_comp.value - ma_slope_comp[1], (inputs.ma_slope_deriv_comp_smooth as number)).current : ta.ema(ma_slope_comp.value - ma_slope_comp[1], (inputs.ma_slope_deriv_comp_smooth as number)).current);
            let ma1_slope_tover = ta.sma((ta.cross(ma_1_slope.value, 0.0).current ? 1 : 0), (inputs.ma1_tover_smooth as number)).current;
            let ma2_slope_tover = ta.sma((ta.cross(ma_2_slope.value, 0.0).current ? 1 : 0), (inputs.ma2_tover_smooth as number)).current;
            let ma3_slope_tover = ta.sma((ta.cross(ma_3_slope.value, 0.0).current ? 1 : 0), (inputs.ma3_tover_smooth as number)).current;
            let ma4_slope_tover = ta.sma((ta.cross(ma_4_slope.value, 0.0).current ? 1 : 0), (inputs.ma4_tover_smooth as number)).current;
            let ma5_slope_tover = ta.sma((ta.cross(ma_5_slope.value, 0.0).current ? 1 : 0), (inputs.ma5_tover_smooth as number)).current;
            let ma_tover_comp = ((((ma1_slope_tover + ma2_slope_tover) + ma3_slope_tover) + ma4_slope_tover) + ma5_slope_tover) / 3;
            let ma_1_dist = ta.sma((((src - ma_1.value) / ma_1.value) * 100), (inputs.ma1_dist_smooth as number)).current;
            let ma_2_dist = ta.sma((((src - ma_2.value) / ma_2.value) * 100), (inputs.ma2_dist_smooth as number)).current;
            let ma_3_dist = ta.sma((((src - ma_3.value) / ma_3.value) * 100), (inputs.ma3_dist_smooth as number)).current;
            let ma_4_dist = ta.sma((((src - ma_4.value) / ma_4.value) * 100), (inputs.ma4_dist_smooth as number)).current;
            let ma_5_dist = ta.sma((((src - ma_5.value) / ma_5.value) * 100), (inputs.ma5_dist_smooth as number)).current;
            let ma_dist_comp = ((((((inputs.ma1_dist_swtch as boolean) ? ma_1_dist : 0) + ((inputs.ma2_dist_swtch as boolean) ? ma_2_dist : 0)) + ((inputs.ma3_dist_swtch as boolean) ? ma_3_dist : 0)) + ((inputs.ma4_dist_swtch as boolean) ? ma_4_dist : 0)) + ((inputs.ma5_dist_swtch as boolean) ? ma_5_dist : 0)) / 5;
            ma_cross2.value = ta.cross(ma_1.value, ma_2.value).current;
            let ma_cross_counter2 = 0.0;
            ma_cross_counter2 = (ma_cross2.value && (!(((inputs.ma12_cross_excl as string) == "1") ? ma_cross2[1] : (((inputs.ma12_cross_excl as string) == "2") ? (ma_cross2[1] || ma_cross2[2]) : false)))) ? 1 : 0;
            let ma_cross_ma2 = (("SMA" as string) == "SMA") ? ta.sma(ma_cross_counter2, (inputs.ma12_cross_smooth as number)).current : ta.ema(ma_cross_counter2, (inputs.ma12_cross_smooth as number)).current;
            let ma_12_cross_ma = ma_cross_ma2;
            ma_cross3.value = ta.cross(ma_2.value, ma_3.value).current;
            let ma_cross_counter3 = 0.0;
            ma_cross_counter3 = (ma_cross3.value && (!(((inputs.ma23_cross_excl as string) == "1") ? ma_cross3[1] : (((inputs.ma23_cross_excl as string) == "2") ? (ma_cross3[1] || ma_cross3[2]) : false)))) ? 1 : 0;
            let ma_cross_ma3 = (("SMA" as string) == "SMA") ? ta.sma(ma_cross_counter3, (inputs.ma23_cross_smooth as number)).current : ta.ema(ma_cross_counter3, (inputs.ma23_cross_smooth as number)).current;
            let ma_23_cross_ma = ma_cross_ma3;
            ma_cross4.value = ta.cross(ma_3.value, ma_4.value).current;
            let ma_cross_counter4 = 0.0;
            ma_cross_counter4 = (ma_cross4.value && (!(((inputs.ma34_cross_excl as string) == "1") ? ma_cross4[1] : (((inputs.ma34_cross_excl as string) == "2") ? (ma_cross4[1] || ma_cross4[2]) : false)))) ? 1 : 0;
            let ma_cross_ma4 = (("SMA" as string) == "SMA") ? ta.sma(ma_cross_counter4, (inputs.ma34_cross_smooth as number)).current : ta.ema(ma_cross_counter4, (inputs.ma34_cross_smooth as number)).current;
            let ma_34_cross_ma = ma_cross_ma4;
            ma_cross5.value = ta.cross(ma_4.value, ma_5.value).current;
            let ma_cross_counter5 = 0.0;
            ma_cross_counter5 = (ma_cross5.value && (!(((inputs.ma45_cross_excl as string) == "1") ? ma_cross5[1] : (((inputs.ma45_cross_excl as string) == "2") ? (ma_cross5[1] || ma_cross5[2]) : false)))) ? 1 : 0;
            let ma_cross_ma5 = (("SMA" as string) == "SMA") ? ta.sma(ma_cross_counter5, (inputs.ma45_cross_smooth as number)).current : ta.ema(ma_cross_counter5, (inputs.ma45_cross_smooth as number)).current;
            let ma_45_cross_ma = ma_cross_ma5;
            let ma_cross_comp = ta.sma((((ma_12_cross_ma + ma_23_cross_ma) + ma_34_cross_ma) + ma_45_cross_ma), (inputs.ma_cross_comp_smooth as number)).current;
            let rsi = ta.rsi(src, 14).current * (inputs.rsi_scaling as number);
            rsi_ma.value = ta.sma(rsi, (inputs.rsi_ma_length as number)).current;
            let rsi_ma_slope = (ta.ema((((rsi_ma.value - rsi_ma[1]) / rsi_ma[1]) * 100), (inputs.rsi_ma_smooth as number)).current * (inputs.rsi_ma_slope_scaling as number)) * (inputs.rsi_scaling as number);
            const transp_pre_limit2 = -0.1;
            const smooth_lgth2 = (ma_1_lgth + ma_2_lgth) / 9;
            let tover_weighted2 = (ma1_slope_tover * 1) + (ma2_slope_tover * 1);
            let limited2 = cf_limit((tover_weighted2 * 0.8) + transp_pre_limit2, 1, 0);
            let mirrored2 = Math.abs((limited2 * 0.9) - 1);
            let smoothed_final2 = ta.wma(mirrored2, Math.round(smooth_lgth2)).current;
            let tab_trend_short_tover = smoothed_final2;
            const transp_pre_limit3 = -0.40;
            const smooth_lgth3 = ma_3_lgth / 2;
            let tover_weighted3 = (ma3_slope_tover * 3) + (ma4_slope_tover * 1);
            let limited3 = cf_limit((tover_weighted3 * 1.1) + transp_pre_limit3, 1, 0);
            let mirrored3 = Math.abs((limited3 * 1.0) - 1);
            let smoothed_final3 = ta.wma(mirrored3, Math.round(smooth_lgth3)).current;
            let tab_trend_med_tover = smoothed_final3;
            const transp_pre_limit4 = -0.05;
            const smooth_lgth4 = (ma_4_lgth + ma_5_lgth) / 15.4;
            let tover_weighted4 = (ma4_slope_tover * 1) + (ma5_slope_tover * 1);
            let limited4 = cf_limit((tover_weighted4 * 1.0) + transp_pre_limit4, 1, 0);
            let mirrored4 = Math.abs((limited4 * 1.8) - 1);
            let smoothed_final4 = ta.wma(mirrored4, Math.round(smooth_lgth4)).current;
            let tab_trend_long_tover = smoothed_final4;
            const smooth_lgth_pre_limit2 = (atr_short_lgth * 1.0);
            const transp_pre_limit5 = -0.080;
            let cross_smooth2 = (("HMA" as string) == "HMA") ? ta.hma(ma_12_cross_ma, Math.round(smooth_lgth_pre_limit2)).current : ta.ema(ma_12_cross_ma, Math.round(smooth_lgth_pre_limit2)).current;
            let cross_adj2 = (cross_smooth2 + transp_pre_limit5) * 5;
            let limited5 = cf_limit(cross_adj2, 1, 0);
            let mirrored5 = Math.abs((limited5 * 0.6) - 1);
            let final2 = ta.sma(mirrored5, 1).current;
            let tab_trend_short_cross = final2;
            const smooth_lgth_pre_limit3 = (ma_3_lgth * 1.0);
            const transp_pre_limit6 = -0.042;
            let cross_smooth3 = (("EMA" as string) == "HMA") ? ta.hma(ma_23_cross_ma, Math.round(smooth_lgth_pre_limit3)).current : ta.ema(ma_23_cross_ma, Math.round(smooth_lgth_pre_limit3)).current;
            let cross_adj3 = (cross_smooth3 + transp_pre_limit6) * 40;
            let limited6 = cf_limit(cross_adj3, 1, 0);
            let mirrored6 = Math.abs((limited6 * 0.8) - 1);
            let final3 = ta.sma(mirrored6, 10).current;
            let tab_trend_med_cross = final3;
            const smooth_lgth_pre_limit4 = (atr_long_lgth * 1.0);
            const transp_pre_limit7 = -0.0075;
            let cross_smooth4 = (("EMA" as string) == "HMA") ? ta.hma(ma_45_cross_ma, Math.round(smooth_lgth_pre_limit4)).current : ta.ema(ma_45_cross_ma, Math.round(smooth_lgth_pre_limit4)).current;
            let cross_adj4 = (cross_smooth4 + transp_pre_limit7) * 95;
            let limited7 = cf_limit(cross_adj4, 1, 0);
            let mirrored7 = Math.abs((limited7 * 0.8) - 1);
            let final4 = ta.sma(mirrored7, 20).current;
            let tab_trend_long_cross = final4;
            let tab_trend_short_madist = cf_tab_madist(ma_1.value, ma_2.value, 30, atr_short_adj, -0.40, 2.0, 0, 0.33);
            let tab_trend_med_madist = cf_tab_madist(ma_2.value, ma_3.value, 25, atr_med_adj, -0.40, 2.0, 0, 0.20);
            let tab_trend_long_madist = cf_tab_madist(ma_4.value, ma_5.value, 25, atr_long_adj, -0.35, 1.8, 0, 0.28);
            let tab_trend_short_pre = ta.wma(((((ma_1_slope.value + (ma_2_slope.value * 2)) * 0.66666) / atr_short_adj) * (inputs.inlineInput as number)), 5).current * ((inputs.test_bool_2 as boolean) ? tab_trend_short_madist : 1);
            let tab_trend_short = (cf_limit(tab_trend_short_pre, 1, -1) * ((inputs.test_bool_2 as boolean) ? tab_trend_short_tover : 1)) * ((inputs.test_bool_2 as boolean) ? tab_trend_short_cross : 1);
            let tab_trend_med_pre = ta.wma((((((ma_2_slope.value + (ma_3_slope.value * 2)) + ma_4_slope.value) * 0.5) / atr_med_adj) * (inputs.inlineInput2 as number)), 5).current * ((inputs.test_bool_1 as boolean) ? tab_trend_med_madist : 1);
            let tab_trend_med = (cf_limit(tab_trend_med_pre, 1, -1) * ((inputs.test_bool_1 as boolean) ? tab_trend_med_tover : 1)) * ((inputs.test_bool_1 as boolean) ? tab_trend_med_cross : 1);
            let tab_trend_long_pre = ta.wma((((((ma_4_slope.value * 2) + ma_5_slope.value) * 0.66666) / atr_long_adj) * (inputs.inlineInput3 as number)), 5).current * ((inputs.test_bool_2 as boolean) ? tab_trend_long_madist : 1);
            if (tab_trend_long_pre < 0) { tab_trend_long_pre *= 1.15; }
            let tab_trend_long = (cf_limit(tab_trend_long_pre, 1, -1) * ((inputs.test_bool_1 as boolean) ? tab_trend_long_tover : 1)) * ((inputs.test_bool_1 as boolean) ? tab_trend_long_cross : 1);
            plot(ma_1_slope.value, { title: "MA 1 Slope", color: "#FF9800", visible: ((inputs.ma_slopes_swtch as boolean) && (!(inputs.ma_slope_comp_swtch as boolean))) && (inputs.ma1_swtch as boolean) });
            plot(ma_2_slope.value, { title: "MA 2 Slope", color: "#FFEB3B", visible: ((inputs.ma_slopes_swtch as boolean) && (!(inputs.ma_slope_comp_swtch as boolean))) && (inputs.ma2_swtch as boolean) });
            plot(ma_3_slope.value, { title: "MA 3 Slope", color: "#00E676", visible: ((inputs.ma_slopes_swtch as boolean) && (!(inputs.ma_slope_comp_swtch as boolean))) && (inputs.ma3_swtch as boolean) });
            plot(ma_4_slope.value, { title: "MA 4 Slope", color: "#2196F3", visible: ((inputs.ma_slopes_swtch as boolean) && (!(inputs.ma_slope_comp_swtch as boolean))) && (inputs.ma4_swtch as boolean) });
            plot(ma_5_slope.value, { title: "MA 5 Slope", color: "#9C27B0", visible: ((inputs.ma_slopes_swtch as boolean) && (!(inputs.ma_slope_comp_swtch as boolean))) && (inputs.ma5_swtch as boolean) });
            plot(ma_slope_comp.value, { title: "MA Slope Comp", color: ma_slope_comp.value >= 0 ? "#2196F3" : "#FF5252", visible: (inputs.ma_slopes_swtch as boolean) && (inputs.ma_slope_comp_swtch as boolean), style: { kind: "columns", baseline: 0 } });
            plot(ma_1_slope_deriv * (inputs.ma_slope_deriv_scaling as number), { title: "MA 1 Derivative", color: "#FF990066", visible: ((inputs.ma_deriv_swtch as boolean) && (inputs.ma1_swtch as boolean)) && (!(inputs.ma_slope_deriv_comp_swtch as boolean)), style: { kind: "columns", baseline: 0 } });
            plot(ma_2_slope_deriv * (inputs.ma_slope_deriv_scaling as number), { title: "MA 2 Derivative", color: "#FFEB3B66", visible: ((inputs.ma_deriv_swtch as boolean) && (inputs.ma2_swtch as boolean)) && (!(inputs.ma_slope_deriv_comp_swtch as boolean)), style: { kind: "columns", baseline: 0 } });
            plot(ma_3_slope_deriv * (inputs.ma_slope_deriv_scaling as number), { title: "MA 3 Derivative", color: "#00E67766", visible: ((inputs.ma_deriv_swtch as boolean) && (inputs.ma3_swtch as boolean)) && (!(inputs.ma_slope_deriv_comp_swtch as boolean)), style: { kind: "columns", baseline: 0 } });
            plot(ma_4_slope_deriv * (inputs.ma_slope_deriv_scaling as number), { title: "MA 4 Derivative", color: "#68B7F866", visible: ((inputs.ma_deriv_swtch as boolean) && (inputs.ma4_swtch as boolean)) && (!(inputs.ma_slope_deriv_comp_swtch as boolean)), style: { kind: "columns", baseline: 0 } });
            plot(ma_5_slope_deriv * (inputs.ma_slope_deriv_scaling as number), { title: "MA 5 Derivative", color: "#A147B166", visible: ((inputs.ma_deriv_swtch as boolean) && (inputs.ma5_swtch as boolean)) && (!(inputs.ma_slope_deriv_comp_swtch as boolean)), style: { kind: "columns", baseline: 0 } });
            plot(ma_slope_deriv_comp * (inputs.ma_slope_deriv_comp_scaling as number), { title: "MA Derivative Comp", color: "#FFFFFF66", visible: (inputs.ma_deriv_swtch as boolean) && (inputs.ma_slope_deriv_comp_swtch as boolean), style: { kind: "columns", baseline: 0 } });
            plot(ma1_slope_tover * (inputs.ma_tover_scaling as number), { title: "MA 1 Turnover", color: "#FF9900E6", visible: ((inputs.ma1_tover_swtch as boolean) && (inputs.ma_turnover_swtch as boolean)) && (!(inputs.ma_tover_comp_swtch as boolean)), style: (inputs.ma_tover_plot_type as string) == "Histo" ? { kind: "histogram", baseline: 0 } : { kind: "line" } });
            plot(ma2_slope_tover * (inputs.ma_tover_scaling as number), { title: "MA 2 Turnover", color: "#FFEB3BE6", visible: ((inputs.ma2_tover_swtch as boolean) && (inputs.ma_turnover_swtch as boolean)) && (!(inputs.ma_tover_comp_swtch as boolean)), style: (inputs.ma_tover_plot_type as string) == "Histo" ? { kind: "histogram", baseline: 0 } : { kind: "line" } });
            plot(ma3_slope_tover * (inputs.ma_tover_scaling as number), { title: "MA 3 Turnover", color: "#00E677E6", visible: ((inputs.ma3_tover_swtch as boolean) && (inputs.ma_turnover_swtch as boolean)) && (!(inputs.ma_tover_comp_swtch as boolean)), style: (inputs.ma_tover_plot_type as string) == "Histo" ? { kind: "histogram", baseline: 0 } : { kind: "line" } });
            plot(ma4_slope_tover * (inputs.ma_tover_scaling as number), { title: "MA 4 Turnover", color: "#68B7F8E6", visible: ((inputs.ma4_tover_swtch as boolean) && (inputs.ma_turnover_swtch as boolean)) && (!(inputs.ma_tover_comp_swtch as boolean)), style: (inputs.ma_tover_plot_type as string) == "Histo" ? { kind: "histogram", baseline: 0 } : { kind: "line" } });
            plot(ma5_slope_tover * (inputs.ma_tover_scaling as number), { title: "MA 5 Turnover", color: "#A147B1E6", visible: ((inputs.ma5_tover_swtch as boolean) && (inputs.ma_turnover_swtch as boolean)) && (!(inputs.ma_tover_comp_swtch as boolean)), style: (inputs.ma_tover_plot_type as string) == "Histo" ? { kind: "histogram", baseline: 0 } : { kind: "line" } });
            plot(ma_tover_comp * (inputs.ma_tover_scaling as number), { title: "MA Turnover Comp", color: "#FFFFFF", visible: (inputs.ma_tover_comp_swtch as boolean) && (inputs.ma_turnover_swtch as boolean), style: (inputs.ma_tover_plot_type as string) == "Histo" ? { kind: "histogram", baseline: 0 } : { kind: "line" } });
            plot(ma_1_dist * (inputs.ma_dist_scaling as number), { title: "MA 1 Distance", color: "#FF9900E6", visible: ((inputs.ma1_dist_swtch as boolean) && (inputs.ma_dist_swtch as boolean)) && (!(inputs.ma_dist_comp_swtch as boolean)) });
            plot(ma_2_dist * (inputs.ma_dist_scaling as number), { title: "MA 2 Distance", color: "#FFEB3BE6", visible: ((inputs.ma2_dist_swtch as boolean) && (inputs.ma_dist_swtch as boolean)) && (!(inputs.ma_dist_comp_swtch as boolean)) });
            plot(ma_3_dist * (inputs.ma_dist_scaling as number), { title: "MA 3 Distance", color: "#00E677E6", visible: ((inputs.ma3_dist_swtch as boolean) && (inputs.ma_dist_swtch as boolean)) && (!(inputs.ma_dist_comp_swtch as boolean)) });
            plot(ma_4_dist * (inputs.ma_dist_scaling as number), { title: "MA 4 Distance", color: "#68B7F8E6", visible: ((inputs.ma4_dist_swtch as boolean) && (inputs.ma_dist_swtch as boolean)) && (!(inputs.ma_dist_comp_swtch as boolean)) });
            plot(ma_5_dist * (inputs.ma_dist_scaling as number), { title: "MA 5 Distance", color: "#A147B1E6", visible: ((inputs.ma5_dist_swtch as boolean) && (inputs.ma_dist_swtch as boolean)) && (!(inputs.ma_dist_comp_swtch as boolean)) });
            plot(ma_dist_comp * (inputs.ma_dist_scaling as number), { title: "MA Distances Comp", color: "#FFFFFF", visible: (inputs.ma_dist_comp_swtch as boolean) && (inputs.ma_dist_swtch as boolean) });
            plot(ma_12_cross_ma * (inputs.ma_cross_scaling as number), { title: "1-2 Cross", color: "#FF9800", visible: ((inputs.ma12_cross_swtch as boolean) && (inputs.ma_cross_swtch as boolean)) && (!(inputs.ma_cross_comp_swtch as boolean)) });
            plot(ma_23_cross_ma * (inputs.ma_cross_scaling as number), { title: "2-3 Cross", color: "#FFEB3B", visible: ((inputs.ma23_cross_swtch as boolean) && (inputs.ma_cross_swtch as boolean)) && (!(inputs.ma_cross_comp_swtch as boolean)) });
            plot(ma_34_cross_ma * (inputs.ma_cross_scaling as number), { title: "3-4 Cross", color: "#00E676", visible: ((inputs.ma34_cross_swtch as boolean) && (inputs.ma_cross_swtch as boolean)) && (!(inputs.ma_cross_comp_swtch as boolean)) });
            plot(ma_45_cross_ma * (inputs.ma_cross_scaling as number), { title: "4-5 Cross", color: "#9C27B0", visible: ((inputs.ma45_cross_swtch as boolean) && (inputs.ma_cross_swtch as boolean)) && (!(inputs.ma_cross_comp_swtch as boolean)) });
            plot(ma_cross_comp * (inputs.ma_cross_scaling as number), { title: "MA Crossing Comp", color: "#FFFFFF", visible: (inputs.ma_cross_comp_swtch as boolean) && (inputs.ma_cross_swtch as boolean) });
            plot(rsi - ((inputs.rsi_center as boolean) ? (50 * (inputs.rsi_scaling as number)) : 0), { title: "RSI", color: "#FFFFFF66", visible: (inputs.rsi_swtch as boolean) && (inputs.rsi_plot_swtch as boolean) });
            plot(rsi_ma.value - ((inputs.rsi_center as boolean) ? (50 * (inputs.rsi_scaling as number)) : 0), { title: "RSI MA", color: "#FFFFFF", visible: (inputs.rsi_swtch as boolean) && (inputs.rsi_ma_swtch as boolean) });
            plot(rsi_ma_slope, { title: "RSI MA Slope", color: "#FFEB3B99", visible: (inputs.rsi_swtch as boolean) && (inputs.rsi_ma_slope_swtch as boolean) });
            plot(atr_short_adj, { title: "ATR Short", color: "#FFFFFF", visible: (inputs.atr_short_swtch as boolean) });
            plot(atr_med_adj, { title: "ATR Medium", color: "#FFFFFF", visible: (inputs.atr_med_swtch as boolean) });
            plot(atr_long_adj, { title: "ATR Long", color: "#FFFFFF", visible: (inputs.atr_long_swtch as boolean) });
            hline((inputs.zero_line_swtch as boolean) ? 0 : Number.NaN, { title: "Zero Line", color: "#ffffffFF", lineStyle: "dashed" });
            let guide_max = hline(1, { title: "Max", color: (inputs.outputs as boolean) ? "#787B86" : "#787b8600" });
            let guide_min = hline(-1, { title: "Min", color: (inputs.outputs as boolean) ? "#787B86" : "#787b8600" });
            let guide_mid_top = hline(0.5, { title: "Mid 50%", color: (inputs.outputs as boolean) ? "#787B86" : "#787b8600", lineStyle: "dashed" });
            let guide_mid_bottom = hline(-0.5, { title: "Mid -50%", color: (inputs.outputs as boolean) ? "#787B86" : "#787b8600", lineStyle: "dashed" });
            let guide_consol_upper = hline(0.2, { title: "Consol Upper", color: "#FFFFFF00" });
            let guide_consol_lower = hline(-0.2, { title: "Consol Lower", color: "#FFFFFF00" });
            draw.fillBetween([bar.point(0, 0.2), bar.point(0, 0.2)], [bar.point(0, -0.2), bar.point(0, -0.2)], { fill: (inputs.outputs as boolean) ? "#CD79DB1F" : "#CD79DB00" });
            plot(tab_trend_short, { title: "Tab Trend Short", color: (((inputs.outputs as boolean) && (inputs.tab_inv as boolean)) && (!((inputs.tab_out_1 as boolean) && (inputs.tab_short as boolean)))) ? "#86868600" : "#CFB066", visible: (((inputs.outputs as boolean) && (inputs.tab_short as boolean)) && (inputs.tab_out_1 as boolean)) || ((inputs.tab_inv as boolean) && (inputs.outputs as boolean)) });
            plot(tab_trend_med, { title: "Tab Trend Medium", color: (((inputs.outputs as boolean) && (inputs.tab_inv as boolean)) && (!((inputs.tab_out_1 as boolean) && (inputs.tab_med as boolean)))) ? "#86868600" : "#26CE9B", visible: (((inputs.outputs as boolean) && (inputs.tab_med as boolean)) && (inputs.tab_out_1 as boolean)) || ((inputs.tab_inv as boolean) && (inputs.outputs as boolean)) });
            plot(tab_trend_long, { title: "Tab Trend Long", color: (((inputs.outputs as boolean) && (inputs.tab_inv as boolean)) && (!((inputs.tab_out_1 as boolean) && (inputs.tab_long as boolean)))) ? "#86868600" : "#4197DD", visible: (((inputs.outputs as boolean) && (inputs.tab_long as boolean)) && (inputs.tab_out_1 as boolean)) || ((inputs.tab_inv as boolean) && (inputs.outputs as boolean)) });
            const trendTableCells = [[{ text: "Fast", textColor: "#FFFFFF80", textHalign: "left", textSize: "normal" }, { text: "Medium", textColor: "#FFFFFF80", textHalign: "left", textSize: "normal" }, { text: "Slow", textColor: "#FFFFFF80", textHalign: "left", textSize: "normal" }], [{ text: format_trend_text(tab_trend_short), bgColor: get_dynamic_color(tab_trend_short), textColor: "#FFFFFF", textHalign: "center", textSize: "normal" }, { text: format_trend_text(tab_trend_med), bgColor: get_dynamic_color(tab_trend_med), textColor: "#FFFFFF", textHalign: "center", textSize: "normal" }, { text: format_trend_text(tab_trend_long), bgColor: get_dynamic_color(tab_trend_long), textColor: "#FFFFFF", textHalign: "center", textSize: "normal" }]] as const;
            if (barstate.islast) { trendTable.current()?.remove(); trendTable.set(draw.table({ position: "top-right", cells: trendTableCells })); }
        },
});
