// Copyright (c) 2026 Invinite. Licensed under the MIT License.
// See the LICENSE file in the repo root for full license text.

import { readFile, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import {
    DIAGNOSTIC_CODE_ENTRIES,
    type DiagnosticCodeEntry,
} from "../packages/pine-converter/src/diagnostics/codes";
// The slug helper is owned by the converter (`diagnostics/format.ts`) so the
// generated `#<slug>` anchors can never drift from the CLI's rendered label.
import { shortCode } from "../packages/pine-converter/src/diagnostics/format";

export { shortCode };

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUTPUT = join(REPO_ROOT, "docs/converter/diagnostics.md");

export const AUTO_HEADER =
    "<!-- AUTO-GENERATED by pnpm converter:docs:generate — do not edit by hand -->";

export const OUT_OF_DATE_MESSAGE =
    "docs/converter/diagnostics.md is out of date. Run pnpm converter:docs:generate and commit.";

// Hand-curated preamble — a generator constant, not a hand-edited page.
// Edit it HERE and re-run the generator; never edit the emitted page.
const INTRO = [
    "# Converter diagnostics",
    "",
    "Every idiom the Pine → chartlang converter cannot translate faithfully",
    "surfaces as a structured `Diagnostic` with a **stable code**, a severity,",
    "a human message, and (usually) a suggested manual rewrite. Codes never",
    "change — downstream tooling (the CLI, editors, gate scripts) keys on them.",
    "",
    "Severities:",
    "",
    "- **error** — the converter could not produce a faithful translation for",
    "  this site. The emitted `.chart.ts` carries a `// HARD-REJECT` marker (or",
    "  omits the construct). Fix the Pine source and re-run, or hand-port the",
    "  rejected slice. Under `--strict` (`strictMode: true`) every **warning**",
    "  is upgraded to an **error**.",
    "- **warning** — the converter translated the site, but a detail was",
    "  dropped or approximated. Review the output.",
    "- **info** — an advisory note about an approximation the converter made on",
    "  purpose (no action usually needed).",
    "",
    "The CLI links each diagnostic to this page by its short slug — the final",
    "`/`-segment of the code. `pine-converter/transform/cap-mismatch` →",
    "[`#cap-mismatch`](#cap-mismatch). Use the anchors below.",
    "",
    "This page is generated from the converter's diagnostic registry, so it can",
    "never drift from the shipped codes. See also the",
    "[reject catalogue](./rejects.md) for the architectural *why* behind the",
    "hard-rejects and the recommended Pine rewrites.",
    "",
];

/** Render one diagnostic-registry entry as an anchored markdown section. */
export function renderEntry(entry: DiagnosticCodeEntry): string {
    const slug = shortCode(entry.code);
    const lines = [
        `### ${slug}`,
        "",
        `- **Code:** \`${entry.code}\``,
        `- **Severity:** ${entry.severity}`,
        `- **Message:** ${entry.defaultMessage}`,
    ];
    if (entry.defaultSuggestion !== undefined) {
        lines.push(`- **Suggested fix:** ${entry.defaultSuggestion}`);
    }
    return lines.join("\n");
}

/**
 * Pure renderer — no IO. Emits the auto-header, the curated intro, then one
 * anchored section per registry entry (sorted by full code string so the page
 * groups by stage: codegen, parse, semantic, transform).
 */
export function renderDiagnosticsPage(entries: ReadonlyArray<DiagnosticCodeEntry>): string {
    const sorted = entries.slice().sort((a, b) => a.code.localeCompare(b.code));
    const parts: string[] = [AUTO_HEADER, "", ...INTRO, sorted.map(renderEntry).join("\n\n"), ""];
    return parts.join("\n");
}

/**
 * Generate `docs/converter/diagnostics.md`. `check: true` byte-diffs the
 * regenerated content against the committed file (failing on drift, like
 * `generate-skills-reference.ts`); otherwise writes the file.
 *
 * @since 0.1
 * @experimental
 */
export async function generateConverterDocs(
    opts: Readonly<{ check?: boolean }> = {},
): Promise<void> {
    const contents = renderDiagnosticsPage(Object.values(DIAGNOSTIC_CODE_ENTRIES));

    if (opts.check === true) {
        let existing = "";
        try {
            existing = await readFile(OUTPUT, "utf8");
        } catch {
            throw new Error(
                `Converter diagnostics page is missing: ${relative(REPO_ROOT, OUTPUT)}`,
            );
        }
        if (existing !== contents) throw new Error(OUT_OF_DATE_MESSAGE);
        return;
    }

    await writeFile(OUTPUT, contents, "utf8");
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
    const check = process.argv.includes("--check");
    generateConverterDocs({ check }).catch((err: unknown) => {
        const message = err instanceof Error ? err.message : String(err);
        console.error(message);
        process.exitCode = 1;
    });
}
