// Copyright (c) 2026 Invinite. Licensed under the MIT License.
// See the LICENSE file in the repo root for full license text.
/**
 * Emits `packages/compiler/src/version.generated.ts` from
 * `packages/compiler/package.json`'s `version`, so the compiler can stamp
 * `manifest.compilerVersion` on every artifact it builds without reading a
 * `package.json` at runtime.
 *
 * `--check` byte-diffs the committed module against a fresh render and exits
 * non-zero on drift — that is the `compiler:version:gate` wired into
 * `pnpm check:content`. `pnpm changeset:version` runs the WRITE mode right
 * after `changeset version` bumps the package, which is what keeps a release
 * commit from shipping a stale constant.
 */
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const PACKAGE_JSON = join(REPO_ROOT, "packages/compiler/package.json");
const OUTPUT = join(REPO_ROOT, "packages/compiler/src/version.generated.ts");

export const OUT_OF_DATE_MESSAGE =
    "packages/compiler/src/version.generated.ts is out of date. Run pnpm compiler:version:generate and commit.";

/**
 * Render the generated module for one compiler version. Pure — no IO — so the
 * gate and the writer share one source of truth for the emitted bytes. The
 * output is Biome-formatted as-is (4-space indent, double quotes, trailing
 * newline); `check:content` runs `pnpm format` before the gate, so a render
 * that Biome would rewrite fails the byte-diff.
 */
export function renderVersionModule(version: string): string {
    return `${[
        "// Copyright (c) 2026 Invinite. Licensed under the MIT License.",
        "// See the LICENSE file in the repo root for full license text.",
        "// GENERATED by pnpm compiler:version:generate — DO NOT EDIT.",
        "// Source of truth: packages/compiler/package.json `version`.",
        "",
        "/**",
        " * Published version of `@invinite-org/chartlang-compiler` this build was cut",
        " * from. Stamped onto every `ScriptManifest` the compiler emits, so a consumer",
        " * can key an artifact cache — or fill the `compilerVersion` slot of a",
        " * `StateStoreKey` — from `compiled.manifest` alone.",
        " *",
        " * Annotated `string` on purpose: the inferred literal type would put the",
        " * exact version into the public `.d.ts` and churn it every release.",
        " *",
        " * @since 1.12",
        " * @stable",
        " * @example",
        " *     const v: string = COMPILER_VERSION;",
        " *     void v;",
        " */",
        `export const COMPILER_VERSION: string = ${JSON.stringify(version)};`,
    ].join("\n")}\n`;
}

/**
 * Read the compiler package's declared `version`. Throws when the field is
 * missing or not a non-empty string — a silently-empty stamp would look like
 * a legitimate version to every downstream cache.
 */
export async function readCompilerVersion(): Promise<string> {
    const parsed: unknown = JSON.parse(await readFile(PACKAGE_JSON, "utf8"));
    const version =
        typeof parsed === "object" && parsed !== null && "version" in parsed
            ? (parsed as { readonly version: unknown }).version
            : undefined;
    if (typeof version !== "string" || version.length === 0) {
        throw new Error(`${relative(REPO_ROOT, PACKAGE_JSON)} has no usable "version" string.`);
    }
    return version;
}

/**
 * Generate `packages/compiler/src/version.generated.ts`. `check: true`
 * byte-diffs the regenerated content against the committed file (failing on
 * drift, like `gen-converter-docs.ts`); otherwise writes it.
 *
 * @since 1.12
 * @experimental
 */
export async function generateCompilerVersion(
    opts: Readonly<{ check?: boolean }> = {},
): Promise<void> {
    const contents = renderVersionModule(await readCompilerVersion());

    if (opts.check === true) {
        let existing = "";
        try {
            existing = await readFile(OUTPUT, "utf8");
        } catch {
            throw new Error(`Compiler version module is missing: ${relative(REPO_ROOT, OUTPUT)}`);
        }
        if (existing !== contents) throw new Error(OUT_OF_DATE_MESSAGE);
        return;
    }

    await writeFile(OUTPUT, contents, "utf8");
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
    const check = process.argv.includes("--check");
    generateCompilerVersion({ check }).catch((err: unknown) => {
        const message = err instanceof Error ? err.message : String(err);
        console.error(message);
        process.exitCode = 1;
    });
}
