// Copyright (c) 2026 Invinite. Licensed under the MIT License.
// See the LICENSE file in the repo root for full license text.

import { readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

import {
    ADAPTERS,
    type AdapterRegistryEntry,
    REPO_URL,
    githubFolder,
} from "./adapters/registry.js";

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const PACKAGES_DIR = join(REPO_ROOT, "packages");
const OUT_DIR = join(REPO_ROOT, "packages/cli/src/generated/adapters");

/** Where the generated docs gallery page lands (Task 15). */
const GALLERY_PATH = join(REPO_ROOT, "docs/adapters/gallery.md");

/** Placeholder the `add-adapter` command substitutes with the chosen name. */
export const PKG_NAME_PLACEHOLDER = "__PKG_NAME__";

/** Header prepended to every emitted file — the "do not hand-edit" marker. */
export const GENERATED_HEADER = "// GENERATED by pnpm adapters:generate — DO NOT EDIT";

/** Markdown "do not hand-edit" marker prepended to the generated gallery page. */
export const GALLERY_HEADER = "<!-- GENERATED by pnpm adapters:generate — DO NOT EDIT -->";

/** The two-line MIT header carried by every emitted `.ts` module. */
const MIT_HEADER = [
    "// Copyright (c) 2026 Invinite. Licensed under the MIT License.",
    "// See the LICENSE file in the repo root for full license text.",
].join("\n");

/**
 * Per-adapter `src/` test basenames omitted from the bundle: they import
 * workspace-internal host-worker test internals / pin a hashed call-log /
 * drive the conformance suite as a CI fixture — none of which a fresh copy
 * outside this monorepo can reproduce. The remaining unit tests resolve
 * against the rewritten published deps.
 */
const OMITTED_TEST_BASENAMES: ReadonlySet<string> = new Set([
    "integration.test.ts",
    "conformance.test.ts",
]);

/** Top-level (non-`src/`) files copied verbatim into each bundle. */
const TOP_LEVEL_FILES = ["README.md", "tsconfig.json"] as const;

/**
 * Standard `.gitignore` synthesized into every bundle. No example ships one
 * (they inherit the repo-root ignore), but a freshly copied adapter repo
 * needs to exclude build/coverage output — same content the
 * `scaffold-adapter` command emits.
 */
export const BUNDLE_GITIGNORE = "node_modules/\ndist/\ncoverage/\n";

/** A single emitted adapter bundle — id + its path -> contents file map. */
export type AdapterBundle = {
    readonly id: string;
    readonly files: Readonly<Record<string, string>>;
};

/**
 * Read every package's `package.json` into a `name -> version` map so
 * `workspace:^` chartlang deps can be pinned to the publishing release's
 * exact versions. A CLI release always installs matching peers this way.
 *
 * @since 1.3
 * @example
 *     import { resolveWorkspaceVersions } from "../scripts/gen-adapters.js";
 *     const versions = await resolveWorkspaceVersions();
 *     versions["@invinite-org/chartlang-adapter-kit"]; // e.g. "1.3.0"
 */
export async function resolveWorkspaceVersions(): Promise<Readonly<Record<string, string>>> {
    const entries = await readdir(PACKAGES_DIR, { withFileTypes: true });
    const versions: Record<string, string> = {};
    for (const entry of entries) {
        if (!entry.isDirectory()) continue;
        const pkgPath = join(PACKAGES_DIR, entry.name, "package.json");
        let raw: string;
        try {
            raw = await readFile(pkgPath, "utf8");
        } catch {
            continue;
        }
        const parsed = JSON.parse(raw) as { name?: unknown; version?: unknown };
        if (typeof parsed.name === "string" && typeof parsed.version === "string") {
            versions[parsed.name] = parsed.version;
        }
    }
    return versions;
}

/**
 * Rewrite an example adapter's `package.json` for bundling: pin every
 * `@invinite-org/chartlang-*` `workspace:^` dep to its published version,
 * swap `name` for the {@link PKG_NAME_PLACEHOLDER}, and keep
 * `"private": true`. Returns the re-serialised JSON (4-space, trailing
 * newline) so the bundle is Biome-clean for the user.
 *
 * @since 1.3
 * @example
 *     import { rewritePackageJson } from "../scripts/gen-adapters.js";
 *     const out = rewritePackageJson(rawPkgJson, { "@invinite-org/chartlang-core": "1.2.0" });
 *     JSON.parse(out).name; // "__PKG_NAME__"
 */
export function rewritePackageJson(
    raw: string,
    versions: Readonly<Record<string, string>>,
): string {
    const pkg = JSON.parse(raw) as Record<string, unknown>;
    pkg.name = PKG_NAME_PLACEHOLDER;
    for (const field of ["dependencies", "devDependencies"] as const) {
        const deps = pkg[field];
        if (deps === undefined || deps === null || typeof deps !== "object") continue;
        const rewritten: Record<string, string> = {};
        for (const [dep, range] of Object.entries(deps as Record<string, string>)) {
            if (range === "workspace:^" && dep in versions) {
                rewritten[dep] = `^${versions[dep]}`;
            } else {
                rewritten[dep] = range;
            }
        }
        pkg[field] = rewritten;
    }
    return `${JSON.stringify(pkg, null, 4)}\n`;
}

/** Normalise an OS path-relative key to forward slashes for the file map. */
function toPosixKey(relPath: string): string {
    return relPath.split(sep).join("/");
}

async function collectSrcFiles(srcDir: string): Promise<ReadonlyArray<string>> {
    const out: string[] = [];
    async function walk(dir: string): Promise<void> {
        const entries = await readdir(dir, { withFileTypes: true });
        for (const entry of entries) {
            const full = join(dir, entry.name);
            if (entry.isDirectory()) {
                await walk(full);
                continue;
            }
            if (!entry.name.endsWith(".ts")) continue;
            if (OMITTED_TEST_BASENAMES.has(entry.name)) continue;
            out.push(full);
        }
    }
    await walk(srcDir);
    return out.sort();
}

/**
 * Build one adapter's bundle: read its source tree (omitting the CI-only
 * test files), `README.md` / `tsconfig.json`, rewrite `package.json`, and
 * synthesize a `.gitignore`. Keys are repo-relative-to-the-example POSIX
 * paths, sorted for determinism.
 *
 * @since 1.3
 * @example
 *     import { buildBundle } from "../scripts/gen-adapters.js";
 *     const bundle = await buildBundle(ADAPTERS[0], versions);
 *     Object.keys(bundle.files).includes("package.json"); // true
 */
export async function buildBundle(
    entry: AdapterRegistryEntry,
    versions: Readonly<Record<string, string>>,
): Promise<AdapterBundle> {
    const exampleRoot = join(REPO_ROOT, entry.exampleDir);
    const files: Record<string, string> = {};

    const srcFiles = await collectSrcFiles(join(exampleRoot, "src"));
    for (const file of srcFiles) {
        files[toPosixKey(relative(exampleRoot, file))] = await readFile(file, "utf8");
    }

    for (const name of TOP_LEVEL_FILES) {
        files[name] = await readFile(join(exampleRoot, name), "utf8");
    }

    files["package.json"] = rewritePackageJson(
        await readFile(join(exampleRoot, "package.json"), "utf8"),
        versions,
    );
    files[".gitignore"] = BUNDLE_GITIGNORE;

    const sorted: Record<string, string> = {};
    for (const key of Object.keys(files).sort()) {
        sorted[key] = files[key];
    }
    return { id: entry.id, files: sorted };
}

/** Render the per-adapter `<id>.ts` module — a frozen bundle literal. */
export function renderBundleModule(bundle: AdapterBundle): string {
    const literal = JSON.stringify({ id: bundle.id, files: bundle.files }, null, 4);
    return `${GENERATED_HEADER}
${MIT_HEADER}

import type { GeneratedAdapterBundle } from "./types.js";

export const bundle: GeneratedAdapterBundle = ${literal};
`;
}

/** Render the generated runtime registry mirror the CLI reads (no scripts/ import). */
export function renderRegistryModule(entries: ReadonlyArray<AdapterRegistryEntry>): string {
    const literal = JSON.stringify(
        entries.map((e) => ({
            id: e.id,
            displayName: e.displayName,
            library: e.library,
            libraryRange: e.libraryRange,
            license: e.license,
            renderTech: e.renderTech,
            strategy: e.strategy,
            approxBundleKb: e.approxBundleKb,
            bestFor: e.bestFor,
            githubFolder: `https://github.com/outraday-org/chartlang/tree/main/${e.exampleDir}`,
        })),
        null,
        4,
    );
    return `${GENERATED_HEADER}
${MIT_HEADER}

import type { GeneratedAdapterMeta } from "./types.js";

export const ADAPTER_REGISTRY: ReadonlyArray<GeneratedAdapterMeta> = ${literal};
`;
}

/**
 * Render the `index.ts` barrel re-exporting each bundle + the meta registry.
 * Imports are emitted sorted by module path (the type-only `./types.js`
 * import merged into that order) so the output is already Biome-clean — the
 * committed file equals the generator output and `adapters:gate` stays green.
 */
export function renderIndexModule(entries: ReadonlyArray<AdapterRegistryEntry>): string {
    const importLines = [
        ...entries.map((e) => ({
            path: `./${e.id}.js`,
            line: `import { bundle as ${identifier(e.id)} } from "./${e.id}.js";`,
        })),
        {
            path: "./types.js",
            line: 'import type { GeneratedAdapterBundle } from "./types.js";',
        },
    ]
        .sort((a, b) => a.path.localeCompare(b.path))
        .map((entry) => entry.line)
        .join("\n");
    const arrayBody = entries.map((e) => `    ${identifier(e.id)},`).join("\n");
    return `${GENERATED_HEADER}
${MIT_HEADER}

${importLines}

export type { GeneratedAdapterBundle, GeneratedAdapterMeta } from "./types.js";
export { ADAPTER_REGISTRY } from "./registry.js";

export const BUNDLED_ADAPTERS: ReadonlyArray<GeneratedAdapterBundle> = [
${arrayBody}
];
`;
}

/** Append the `GeneratedAdapterMeta` shape to the shared `types.ts` module. */
export function renderFullTypesModule(): string {
    return `${GENERATED_HEADER}
${MIT_HEADER}

/** A baked-in adapter bundle: its id and a path -> file-contents map. */
export type GeneratedAdapterBundle = {
    readonly id: string;
    readonly files: Readonly<Record<string, string>>;
};

/** Runtime metadata the CLI reads for the \`add-adapter --list\` matrix. */
export type GeneratedAdapterMeta = {
    readonly id: string;
    readonly displayName: string;
    readonly library: string;
    readonly libraryRange: string;
    readonly license: string;
    readonly renderTech: string;
    readonly strategy: string;
    readonly approxBundleKb: number;
    readonly bestFor: string;
    readonly githubFolder: string;
};
`;
}

/** Convert a kebab adapter id to a safe JS identifier for the barrel imports. */
function identifier(id: string): string {
    const camel = id.replace(/-([a-z0-9])/g, (_m, c: string) => c.toUpperCase());
    return `${camel}Bundle`;
}

/** How each integration strategy paints chartlang's drawing surface — one line for the cards. */
const STRATEGY_BLURB: Readonly<Record<AdapterRegistryEntry["strategy"], string>> = {
    ctx: "paints the decomposed primitives onto a raw 2D canvas context",
    nodes: "maps each decomposed primitive to a retained-mode scene-graph node",
    graphic: "maps each decomposed primitive to a declarative graphic element",
    "native-ctx":
        "renders series/panes natively and overlays drawings through a primitive's context",
    gl: "uploads the decomposed geometry to GPU programs and paints text through a 2D-canvas overlay",
};

/**
 * The GitHub deep link to an adapter's committed conformance report. Only the
 * canvas2d reference adapter ships a committed `CONFORMANCE.md`; the other five
 * are run pass/fail by `pnpm conformance` and own no committed report, so they
 * point at the conformance docs page instead (a resolvable link). Documented in
 * the gallery FAQ + `scripts/CLAUDE.md`.
 */
function conformanceLink(entry: AdapterRegistryEntry): string {
    if (entry.id === "canvas2d") {
        return `${REPO_URL}/blob/main/${entry.exampleDir}/CONFORMANCE.md`;
    }
    return "./conformance.md";
}

/** The exact one-command install line for an adapter (the task's canonical form). */
function installCommand(entry: AdapterRegistryEntry): string {
    return `npx @invinite-org/chartlang-cli add-adapter ${entry.id}`;
}

function renderGalleryIntro(): string {
    return [
        "# Adapter gallery",
        "",
        "An **adapter** teaches a chart library how to render chartlang emissions:",
        "the runtime produces typed, JSON-safe emissions (candles, plots, drawings,",
        "alerts) and the adapter translates them into draw calls on a specific chart",
        "vendor's surface. One script, many charts.",
        "",
        "There are two ways to get an adapter:",
        "",
        "- **`npx @invinite-org/chartlang-cli add-adapter <id>`** — drops a complete,",
        "  runnable, version-pinned copy of one of the full-surface example adapters",
        "  below into your repo (offline; the templates are baked into the CLI).",
        "- **`npx @invinite-org/chartlang-cli scaffold-adapter <name>`** — emits a blank",
        "  starter package wired for conformance, for a library not in this gallery.",
        "",
        "New to adapters? Read [Writing an adapter](./writing-an-adapter.md) for the",
        "contract and [Conformance](./conformance.md) for the scenario suite. Every",
        "adapter here declares the full surface (all 63 drawing kinds + every plot kind)",
        "and is conformance-green.",
        "",
    ].join("\n");
}

function renderGalleryMatrix(entries: ReadonlyArray<AdapterRegistryEntry>): string {
    const rows = entries.map((entry) => {
        const cells = [
            `[${entry.displayName}](#${entry.id})`,
            entry.library === "(none)" ? "none" : `\`${entry.library}\``,
            entry.license,
            entry.renderTech,
            "Full (63 + all plots)",
            `~${entry.approxBundleKb} KB`,
            `[\`${entry.exampleDir}/\`](${githubFolder(entry)})`,
        ];
        return `| ${cells.join(" | ")} |`;
    });
    return [
        "## Comparison",
        "",
        "| Adapter | Library | License | Render tech | Drawing surface | ~Bundle | Source |",
        "| --- | --- | --- | --- | --- | --- | --- |",
        ...rows,
        "",
        "`~Bundle` is a hand-maintained estimate (see the [FAQ](#faq)).",
        "",
    ].join("\n");
}

function renderGalleryCard(entry: AdapterRegistryEntry): string {
    const folder = githubFolder(entry);
    // canvas2d has no external library (`(none)` / `(built-in)` in the registry);
    // render a clean "no dependency" line rather than a doubly-parenthesised one.
    const libraryLine =
        entry.library === "(none)"
            ? `- **Library:** none (zero external dependencies) · ${entry.license}`
            : `- **Library:** \`${entry.library}\` (${entry.libraryRange}) · ${entry.license}`;
    return [
        `## ${entry.displayName} {#${entry.id}}`,
        "",
        `**Best for** — ${entry.bestFor}`,
        "",
        libraryLine,
        `- **Render tech:** ${entry.renderTech} (~${entry.approxBundleKb} KB)`,
        `- **Drawings:** ${STRATEGY_BLURB[entry.strategy]}.`,
        "",
        "Install:",
        "",
        "```bash",
        installCommand(entry),
        "```",
        "",
        "Source:",
        `[folder](${folder}) ·`,
        `[README](${folder}#readme) ·`,
        `[conformance](${conformanceLink(entry)})`,
        "",
    ].join("\n");
}

function renderGalleryGuide(): string {
    return [
        "## Which should I choose?",
        "",
        "- **Financial-native candles / axes / panes for free** → `lightweight-charts`.",
        "- **Tiniest + fastest, immediate-mode draw hooks** → `uplot`.",
        "- **Dashboards / huge ecosystem / declarative graphics** → `echarts`.",
        "- **Interactive, custom, retained-mode scene-graph + hit-testing** → `konva`.",
        "- **Zero-dependency reference, full control over every pixel** → `canvas2d`.",
        "",
        "All six share one renderer-agnostic geometry layer",
        "(`decomposeDrawing` in `@invinite-org/chartlang-adapter-kit`), so the drawing",
        "math is identical — the choice is about your library, not the drawing surface.",
        "",
    ].join("\n");
}

function renderGalleryFaq(): string {
    return [
        "## FAQ",
        "",
        "**The examples aren't on npm — how do I add one?** They are private",
        "(copy-only) example packages, not published. Use",
        "`npx @invinite-org/chartlang-cli add-adapter <id>` (it bakes a version-pinned",
        "copy into your repo) or copy the GitHub folder directly. `npm install` will not",
        "find them.",
        "",
        "**Why is the `~Bundle` size approximate?** `approxBundleKb` is a",
        "hand-maintained field on the adapter registry, not auto-measured, so the",
        "generated gallery + the `add-adapter --list` matrix stay deterministic and the",
        "`adapters:gate` byte-diff never flaps on a measurement.",
        "",
        "**Do drawings look pixel-identical across adapters?** The geometry is shared",
        "via `decomposeDrawing`, but non-canvas adapters use a **linear price axis**",
        "approximation for drawing projection (exact on a linear scale, approximate on a",
        "log scale — a deferred follow-up). The shared geometry layer lives in",
        "`@invinite-org/chartlang-adapter-kit`; canvas-family adapters also reuse its",
        "`/canvas` `paintPrimitive` sink.",
        "",
        "**Where's the committed conformance report?** Only the canvas2d reference",
        "adapter ships a committed `CONFORMANCE.md`; the other five are run pass/fail by",
        "`pnpm conformance` and link the [conformance docs](./conformance.md) instead.",
        "",
    ].join("\n");
}

/**
 * Render the generated `docs/adapters/gallery.md` from the adapter registry —
 * a pure, deterministic page (intro + comparison matrix + per-adapter cards +
 * decision guide + FAQ). The committed page is byte-diffed by `adapters:gate`,
 * so hand-edits fail CI; fix the registry or this renderer and re-run.
 *
 * @since 1.3
 * @example
 *     import { renderGallery } from "../scripts/gen-adapters.js";
 *     import { ADAPTERS } from "../scripts/adapters/registry.js";
 *     renderGallery(ADAPTERS).startsWith("<!-- GENERATED"); // true
 */
export function renderGallery(entries: ReadonlyArray<AdapterRegistryEntry>): string {
    const sections = [
        renderGalleryIntro(),
        renderGalleryMatrix(entries),
        ...entries.map(renderGalleryCard),
        renderGalleryGuide(),
        renderGalleryFaq(),
    ];
    return `${GALLERY_HEADER}\n\n${sections.join("\n")}`;
}

/**
 * The full set of files the generator emits, keyed by basename (no header
 * concerns — each renderer already prepends the header). Pure: takes the
 * built bundles + registry, returns path -> contents for the whole output dir.
 */
export async function renderAllOutputs(
    entries: ReadonlyArray<AdapterRegistryEntry>,
    versions: Readonly<Record<string, string>>,
): Promise<Readonly<Record<string, string>>> {
    const out: Record<string, string> = {};
    for (const entry of entries) {
        const bundle = await buildBundle(entry, versions);
        out[`${entry.id}.ts`] = renderBundleModule(bundle);
    }
    out["types.ts"] = renderFullTypesModule();
    out["registry.ts"] = renderRegistryModule(entries);
    out["index.ts"] = renderIndexModule(entries);
    return out;
}

/**
 * Generate the baked-in adapter bundles into
 * `packages/cli/src/generated/adapters/`. With `check: true`, re-render
 * into memory and byte-diff against the committed files (the
 * `pnpm adapters:gate` contract) instead of writing — failing loudly on
 * drift or a missing file.
 *
 * @since 1.3
 * @example
 *     import { generateAdapters } from "../scripts/gen-adapters.js";
 *     await generateAdapters();              // emit
 *     await generateAdapters({ check: true }); // gate — throws on drift
 */
export async function generateAdapters(opts: Readonly<{ check?: boolean }> = {}): Promise<void> {
    const versions = await resolveWorkspaceVersions();
    const outputs = await renderAllOutputs(ADAPTERS, versions);
    const gallery = renderGallery(ADAPTERS);

    // The full emit/diff set: the CLI bundle files (the Task-14 output) plus
    // the Task-15 docs gallery. Both flow through one generate + one gate.
    const targets: ReadonlyArray<readonly [string, string]> = [
        ...Object.entries(outputs).map(
            ([name, contents]) => [join(OUT_DIR, name), contents] as const,
        ),
        [GALLERY_PATH, gallery] as const,
    ];

    if (opts.check === true) {
        const drift: string[] = [];
        for (const [path, contents] of targets) {
            let existing: string;
            try {
                existing = await readFile(path, "utf8");
            } catch {
                drift.push(`missing: ${relative(REPO_ROOT, path)}`);
                continue;
            }
            if (existing !== contents) drift.push(`drift: ${relative(REPO_ROOT, path)}`);
        }
        if (drift.length > 0) {
            throw new Error(
                `Generated adapter files are out of date — run pnpm adapters:generate and commit.\n  ${drift.join("\n  ")}`,
            );
        }
        return;
    }

    await Promise.all(targets.map(([path, contents]) => writeFile(path, contents, "utf8")));
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
    const check = process.argv.includes("--check");
    generateAdapters({ check }).catch((err: unknown) => {
        console.error(err instanceof Error ? err.message : String(err));
        process.exitCode = 1;
    });
}
