// Copyright (c) 2026 Invinite. Licensed under the MIT License.
// See the LICENSE file in the repo root for full license text.

import { readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import {
    type DrawingDocInput,
    parseDrawingSource,
} from "../packages/cli/src/commands/extractDrawingPages";
import { type PrimitiveDocInput, parsePrimitiveSource } from "../packages/cli/src/commands/genDocs";
import { STATEFUL_PRIMITIVES } from "../packages/core/src/statefulPrimitives";

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const TA_SRC = join(REPO_ROOT, "packages/runtime/src/ta");
// draw.* JSDoc lives at `packages/runtime/src/emit/draw` — the same path
// `docs-gate.ts` walks and `parseDrawingSource` consumes (NOT
// `packages/core/src/draw`, which holds the bucket/types table).
const DRAW_SRC = join(REPO_ROOT, "packages/runtime/src/emit/draw");
const OUTPUT = join(REPO_ROOT, "skills/chartlang-coding/references/primitives.md");

export const AUTO_HEADER = "<!-- AUTO-GENERATED by pnpm skills:generate — do not edit by hand -->";

export const OUT_OF_DATE_MESSAGE =
    "skills/chartlang-coding/references/primitives.md is out of date. Run pnpm skills:generate and commit.";

// Source of truth for these skip rules is `genDocs.ts` (ta) and
// `extractDrawingPages.ts` (draw); their copies are file-private so we
// mirror them here. They cannot drift unnoticed: the same files feed
// `docs:gate`, which would fail first.
const TA_SKIP_BASENAMES = new Set(["index.ts", "persistence.ts", "registry.ts", "sourceValue.ts"]);
const DRAW_SKIP_BASENAMES = new Set([
    "index.ts",
    "namespace.ts",
    "handle.ts",
    "pushDrawing.ts",
    "subIdAllocator.ts",
]);
const SKIP_SUFFIXES = [
    ".test.ts",
    ".bench.ts",
    ".bench.test.ts",
    ".golden.test.ts",
    ".property.test.ts",
    ".types.test.ts",
];

function isSkippable(base: string, skipBasenames: ReadonlySet<string>): boolean {
    if (skipBasenames.has(base)) return true;
    return SKIP_SUFFIXES.some((suffix) => base.endsWith(suffix));
}

// `parsePrimitiveSource` / `parseDrawingSource` require a `repoUrl` +
// `runtimeRelPath` to build a "Source on GitHub" link the skills
// reference never renders. Pass fixed values so generation is hermetic
// (no `package.json` read) and the rendered output is deterministic.
const PARSE_OPTS = { repoUrl: "https://example.invalid/r.git", runtimeRelPath: "" } as const;

async function collectTa(): Promise<ReadonlyArray<PrimitiveDocInput>> {
    const entries = await readdir(TA_SRC, { withFileTypes: true });
    const files = entries
        .filter(
            (e) => e.isFile() && e.name.endsWith(".ts") && !isSkippable(e.name, TA_SKIP_BASENAMES),
        )
        .map((e) => join(TA_SRC, e.name))
        .sort();
    const parsed = await Promise.all(files.map((file) => parsePrimitiveSource(file, PARSE_OPTS)));
    crossCheckTa(
        parsed.map((p) => p.id),
        STATEFUL_PRIMITIVES,
    );
    return parsed.slice().sort((a, b) => a.id.localeCompare(b.id));
}

/**
 * Hard-error if a `ta.*` primitive present in the registry produced no
 * `PrimitiveDocInput` (i.e. its source has no JSDoc the parser accepts),
 * mirroring the docs gate's "no silent drop" spirit.
 */
export function crossCheckTa(
    parsedIds: ReadonlyArray<string>,
    registry: ReadonlySet<{ name: string }>,
): void {
    const have = new Set(parsedIds);
    const missing: string[] = [];
    for (const entry of registry) {
        if (!entry.name.startsWith("ta.")) continue;
        const id = entry.name.slice("ta.".length);
        if (!have.has(id)) missing.push(entry.name);
    }
    if (missing.length > 0) {
        throw new Error(
            `Missing ta.* JSDoc for registry primitive(s): ${missing.sort().join(", ")}. Every ta.* in statefulPrimitives.ts must have a documented source file.`,
        );
    }
}

async function collectDraw(): Promise<ReadonlyArray<DrawingDocInput>> {
    const files: string[] = [];
    const top = await readdir(DRAW_SRC, { withFileTypes: true });
    for (const e of top) {
        const full = join(DRAW_SRC, e.name);
        if (e.isDirectory()) {
            const sub = await readdir(full, { withFileTypes: true });
            for (const s of sub) {
                if (
                    s.isFile() &&
                    s.name.endsWith(".ts") &&
                    !isSkippable(s.name, DRAW_SKIP_BASENAMES)
                ) {
                    files.push(join(full, s.name));
                }
            }
            continue;
        }
        if (e.isFile() && e.name.endsWith(".ts") && !isSkippable(e.name, DRAW_SKIP_BASENAMES)) {
            files.push(full);
        }
    }
    const parsed = await Promise.all(
        files.sort().map((file) => parseDrawingSource(file, PARSE_OPTS)),
    );
    return parsed.slice().sort((a, b) => a.camelKind.localeCompare(b.camelKind));
}

function renderTaBlock(p: PrimitiveDocInput): string {
    const lines = [`### ta.${p.id}`, "", "```ts", p.signature, "```", ""];
    if (p.description.length > 0) lines.push(p.description, "");
    lines.push(`**Formula:** ${p.formula}`);
    lines.push(`**Warmup:** ${p.warmup}`);
    lines.push(`**Since:** ${p.since} · ${p.stability}`);
    return lines.join("\n");
}

function renderDrawBlock(d: DrawingDocInput): string {
    const lines = [`### draw.${d.camelKind}`, "", "```ts", d.signature, "```", ""];
    if (d.description.length > 0) lines.push(d.description, "");
    lines.push(`**Anchors:** ${d.anchors}`);
    lines.push(`**Since:** ${d.since} · ${d.stability}`);
    return lines.join("\n");
}

/**
 * Pure renderer — no IO. Emits the auto-header as the first line, then
 * one block per `ta.*` and `draw.*` primitive (alphabetical within each
 * namespace).
 */
export function renderReference(
    ta: ReadonlyArray<PrimitiveDocInput>,
    draw: ReadonlyArray<DrawingDocInput>,
): string {
    const parts: string[] = [
        AUTO_HEADER,
        "",
        "# chartlang primitive reference",
        "",
        "Generated from source JSDoc. Authoritative — do not hand-edit. Run",
        "`pnpm skills:generate` after changing a `ta.*` / `draw.*` primitive.",
        "",
        "The chartlang compiler injects a leading `slotId: string` argument at",
        "every callsite, so script authors call `ta.<id>(...)` / `draw.<id>(...)`",
        "without it — the signatures below show the runtime form including `slotId`.",
        "",
        "## ta.*",
        "",
        ta.map(renderTaBlock).join("\n\n"),
        "",
        "## draw.*",
        "",
        draw.map(renderDrawBlock).join("\n\n"),
        "",
    ];
    return parts.join("\n");
}

/**
 * Generate the skills primitive reference. `check: true` byte-diffs the
 * regenerated content against the committed file (failing on drift,
 * like `gen-hover-registry.ts`); otherwise writes the file.
 */
export async function generateSkillsReference(
    opts: Readonly<{ check?: boolean }> = {},
): Promise<void> {
    const [ta, draw] = await Promise.all([collectTa(), collectDraw()]);
    const contents = renderReference(ta, draw);

    if (opts.check === true) {
        let existing = "";
        try {
            existing = await readFile(OUTPUT, "utf8");
        } catch {
            throw new Error(`Skills reference is missing: ${relative(REPO_ROOT, OUTPUT)}`);
        }
        if (existing !== contents) throw new Error(OUT_OF_DATE_MESSAGE);
        return;
    }

    await writeFile(OUTPUT, contents, "utf8");
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
    const check = process.argv.includes("--check");
    generateSkillsReference({ check }).catch((err: unknown) => {
        const message = err instanceof Error ? err.message : String(err);
        console.error(message);
        process.exitCode = 1;
    });
}
