// Copyright (c) 2026 Invinite. Licensed under the MIT License.
// See the LICENSE file in the repo root for full license text.

import { readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import ts from "typescript";

import {
    type DrawingDocInput,
    parseDrawingSource,
} from "../packages/cli/src/commands/extractDrawingPages";
import { type PrimitiveDocInput, parsePrimitiveSource } from "../packages/cli/src/commands/genDocs";
import {
    PHASE4_DOC_ENTRIES,
    type Phase4DocInput,
    parsePhase4DocEntry,
} from "../packages/cli/src/commands/genPhase4Docs";
import { STATEFUL_PRIMITIVES } from "../packages/core/src/statefulPrimitives";

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const TA_SRC = join(REPO_ROOT, "packages/runtime/src/ta");
// draw.* JSDoc lives at `packages/runtime/src/emit/draw` — the same path
// `docs-gate.ts` walks and `parseDrawingSource` consumes (NOT
// `packages/core/src/draw`, which holds the bucket/types table).
const DRAW_SRC = join(REPO_ROOT, "packages/runtime/src/emit/draw");
// The plot-family holes (`plot`/`hline`/`bgcolor`/`barcolor`) are core
// sentinel holes — author signatures with no `@formula`/`@warmup`, so they
// can't go through `parsePrimitiveSource` (which hard-requires those tags).
// `collectPlotFamily` reads their JSDoc directly from this one file.
const PLOT_SRC = join(REPO_ROOT, "packages/core/src/plot/plot.ts");
const OUTPUT = join(REPO_ROOT, "skills/chartlang-coding/references/primitives.md");

// Render order of the plot family — author-intuitive (value plot, level
// line, the two Pine-ergonomic background/bar-tint aliases, then the two
// value-carrying derived OHLC series), NOT alphabetical.
const PLOT_FAMILY = ["plot", "hline", "bgcolor", "barcolor", "plotcandle", "plotbar"] as const;

export const AUTO_HEADER = "<!-- AUTO-GENERATED by pnpm skills:generate — do not edit by hand -->";

export const OUT_OF_DATE_MESSAGE =
    "skills/chartlang-coding/references/primitives.md is out of date. Run pnpm skills:generate and commit.";

// Source of truth for these skip rules is `genDocs.ts` (ta) and
// `extractDrawingPages.ts` (draw); their copies are file-private so we
// mirror them here. They cannot drift unnoticed: the same files feed
// `docs:gate`, which would fail first.
const TA_SKIP_BASENAMES = new Set(["index.ts", "persistence.ts", "registry.ts", "sourceValue.ts"]);
const DRAW_SKIP_BASENAMES = new Set([
    "index.ts",
    "namespace.ts",
    "handle.ts",
    "pushDrawing.ts",
    "subIdAllocator.ts",
]);
const SKIP_SUFFIXES = [
    ".test.ts",
    ".bench.ts",
    ".bench.test.ts",
    ".golden.test.ts",
    ".property.test.ts",
    ".types.test.ts",
];

function isSkippable(base: string, skipBasenames: ReadonlySet<string>): boolean {
    if (skipBasenames.has(base)) return true;
    return SKIP_SUFFIXES.some((suffix) => base.endsWith(suffix));
}

// `parsePrimitiveSource` / `parseDrawingSource` require a `repoUrl` +
// `runtimeRelPath` to build a "Source on GitHub" link the skills
// reference never renders. Pass fixed values so generation is hermetic
// (no `package.json` read) and the rendered output is deterministic.
const PARSE_OPTS = { repoUrl: "https://example.invalid/r.git", runtimeRelPath: "" } as const;

async function collectTa(): Promise<ReadonlyArray<PrimitiveDocInput>> {
    const entries = await readdir(TA_SRC, { withFileTypes: true });
    const files = entries
        .filter(
            (e) => e.isFile() && e.name.endsWith(".ts") && !isSkippable(e.name, TA_SKIP_BASENAMES),
        )
        .map((e) => join(TA_SRC, e.name))
        .sort();
    const parsed = await Promise.all(files.map((file) => parsePrimitiveSource(file, PARSE_OPTS)));
    crossCheckTa(
        parsed.map((p) => p.id),
        STATEFUL_PRIMITIVES,
    );
    return parsed.slice().sort((a, b) => a.id.localeCompare(b.id));
}

/**
 * Hard-error if a `ta.*` primitive present in the registry produced no
 * `PrimitiveDocInput` (i.e. its source has no JSDoc the parser accepts),
 * mirroring the docs gate's "no silent drop" spirit.
 */
export function crossCheckTa(
    parsedIds: ReadonlyArray<string>,
    registry: ReadonlySet<{ name: string }>,
): void {
    const have = new Set(parsedIds);
    const missing: string[] = [];
    for (const entry of registry) {
        if (!entry.name.startsWith("ta.")) continue;
        const id = entry.name.slice("ta.".length);
        if (!have.has(id)) missing.push(entry.name);
    }
    if (missing.length > 0) {
        throw new Error(
            `Missing ta.* JSDoc for registry primitive(s): ${missing.sort().join(", ")}. Every ta.* in statefulPrimitives.ts must have a documented source file.`,
        );
    }
}

async function collectDraw(): Promise<ReadonlyArray<DrawingDocInput>> {
    const files: string[] = [];
    const top = await readdir(DRAW_SRC, { withFileTypes: true });
    for (const e of top) {
        const full = join(DRAW_SRC, e.name);
        if (e.isDirectory()) {
            const sub = await readdir(full, { withFileTypes: true });
            for (const s of sub) {
                if (
                    s.isFile() &&
                    s.name.endsWith(".ts") &&
                    !isSkippable(s.name, DRAW_SKIP_BASENAMES)
                ) {
                    files.push(join(full, s.name));
                }
            }
            continue;
        }
        if (e.isFile() && e.name.endsWith(".ts") && !isSkippable(e.name, DRAW_SKIP_BASENAMES)) {
            files.push(full);
        }
    }
    const parsed = await Promise.all(
        files.sort().map((file) => parseDrawingSource(file, PARSE_OPTS)),
    );
    return parsed.slice().sort((a, b) => a.camelKind.localeCompare(b.camelKind));
}

/**
 * One plot-family hole's rendered surface. The plot holes are core
 * sentinel holes (author signatures), so this carries only the tags they
 * actually document — no `@formula` / `@warmup` (those are `ta.*`-specific).
 */
export type PlotDocInput = Readonly<{
    name: string;
    signature: string;
    description: string;
    since: string;
    stability: "stable" | "experimental" | "frozen";
}>;

function jsDocOf(node: ts.FunctionDeclaration): ts.JSDoc | undefined {
    return (node as ts.FunctionDeclaration & { jsDoc?: ts.JSDoc[] }).jsDoc?.[0];
}

function plotSignature(source: ts.SourceFile, fn: ts.FunctionDeclaration): string {
    const printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed, removeComments: true });
    const stripped = ts.factory.updateFunctionDeclaration(
        fn,
        fn.modifiers?.filter((m) => m.kind !== ts.SyntaxKind.ExportKeyword),
        fn.asteriskToken,
        fn.name,
        fn.typeParameters,
        fn.parameters,
        fn.type,
        undefined,
    );
    return printer.printNode(ts.EmitHint.Unspecified, stripped, source);
}

function plotStabilityOf(tags: readonly ts.JSDocTag[]): PlotDocInput["stability"] | null {
    if (tags.some((t) => t.tagName.text === "stable")) return "stable";
    if (tags.some((t) => t.tagName.text === "experimental")) return "experimental";
    if (tags.some((t) => t.tagName.text === "frozen")) return "frozen";
    return null;
}

/**
 * Read the JSDoc + signature for the four plot-family holes from
 * `packages/core/src/plot/plot.ts`. Mirrors `parsePrimitiveSource`'s
 * spirit (TS-AST read, no regex, hard-error on a missing required tag) but
 * only requires the tags a plot hole carries: a description, `@since`, and
 * a stability marker. A new undocumented plotting hole fails here rather
 * than emitting a blank block.
 */
async function collectPlotFamily(): Promise<ReadonlyArray<PlotDocInput>> {
    const text = await readFile(PLOT_SRC, "utf8");
    const source = ts.createSourceFile(PLOT_SRC, text, ts.ScriptTarget.ES2022, true);
    const byName = new Map<string, ts.FunctionDeclaration>();
    for (const stmt of source.statements) {
        if (!ts.isFunctionDeclaration(stmt)) continue;
        if (!stmt.name) continue;
        const exported = stmt.modifiers?.some((m) => m.kind === ts.SyntaxKind.ExportKeyword);
        if (!exported) continue;
        byName.set(stmt.name.text, stmt);
    }
    return PLOT_FAMILY.map((name) => {
        const fn = byName.get(name);
        if (!fn) {
            throw new Error(`Missing exported plot-family hole "${name}" in ${PLOT_SRC}`);
        }
        const doc = jsDocOf(fn);
        const description = (ts.getTextOfJSDocComment(doc?.comment) ?? "").trim();
        const tags = ts.getJSDocTags(fn);
        const sinceTag = tags.find((t) => t.tagName.text === "since");
        const since = (ts.getTextOfJSDocComment(sinceTag?.comment) ?? "").trim();
        const stability = plotStabilityOf(tags);
        if (description.length === 0 || since.length === 0 || stability === null) {
            throw new Error(
                `Plot-family hole "${name}" must document a description, @since, and a stability marker (@stable/@experimental/@frozen).`,
            );
        }
        return { name, signature: plotSignature(source, fn), description, since, stability };
    });
}

/**
 * Collect one value namespace (`math` / `str`) as a single consolidated
 * `Phase4DocInput`. Reuses `parsePhase4DocEntry` + the shared
 * `PHASE4_DOC_ENTRIES` registry so the source path / symbol path can never
 * drift from the docs gate; the namespace's `signature` is the whole
 * `Object.freeze({...})` member list. The produced `sourceUrl` is intentionally
 * NOT rendered (the reference carries no GitHub links).
 */
async function collectNamespace(title: "math" | "str"): Promise<Phase4DocInput> {
    const entry = PHASE4_DOC_ENTRIES.find((e) => e.title === title);
    if (entry === undefined) {
        throw new Error(`Missing PHASE4_DOC_ENTRIES entry for "${title}"`);
    }
    return parsePhase4DocEntry(REPO_ROOT, entry);
}

function renderTaBlock(p: PrimitiveDocInput): string {
    const lines = [`### ta.${p.id}`, "", "```ts", p.signature, "```", ""];
    if (p.description.length > 0) lines.push(p.description, "");
    lines.push(`**Formula:** ${p.formula}`);
    lines.push(`**Warmup:** ${p.warmup}`);
    lines.push(`**Since:** ${p.since} · ${p.stability}`);
    return lines.join("\n");
}

function renderDrawBlock(d: DrawingDocInput): string {
    const lines = [`### draw.${d.camelKind}`, "", "```ts", d.signature, "```", ""];
    if (d.description.length > 0) lines.push(d.description, "");
    lines.push(`**Anchors:** ${d.anchors}`);
    lines.push(`**Since:** ${d.since} · ${d.stability}`);
    return lines.join("\n");
}

function renderPlotBlock(p: PlotDocInput): string {
    const lines = [`### ${p.name}`, "", "```ts", p.signature, "```", ""];
    if (p.description.length > 0) lines.push(p.description, "");
    lines.push(`**Since:** ${p.since} · ${p.stability}`);
    return lines.join("\n");
}

/**
 * Render one consolidated value-namespace block (`## math.*` / `## str.*`).
 * Unlike `ta.*` / `draw.*` (one block per member), the small frozen
 * `math` / `str` namespaces render as a single block whose `signature` is the
 * whole `Object.freeze({...})` member list — mirroring the single-page
 * `docs/primitives/math.md` / `str.md` shape.
 */
function renderNamespaceBlock(title: string, doc: Phase4DocInput): string {
    const lines = [`## ${title}.*`, ""];
    if (doc.description.length > 0) lines.push(doc.description, "");
    lines.push("```ts", doc.signature, "```", "");
    lines.push(`**Example:** \`${doc.example}\``);
    lines.push(`**Since:** ${doc.since} · ${doc.stability}`);
    return lines.join("\n");
}

/**
 * Pure renderer — no IO. Emits the auto-header as the first line, then
 * one block per `ta.*` and `draw.*` primitive (alphabetical within each
 * namespace), then the `## plot family` section (`plot` / `hline` /
 * `bgcolor` / `barcolor`, in `PLOT_FAMILY` order), then the consolidated
 * `## math.*` / `## str.*` value-namespace blocks.
 */
export function renderReference(
    ta: ReadonlyArray<PrimitiveDocInput>,
    draw: ReadonlyArray<DrawingDocInput>,
    plotFamily: ReadonlyArray<PlotDocInput>,
    math: Phase4DocInput,
    str: Phase4DocInput,
): string {
    const parts: string[] = [
        AUTO_HEADER,
        "",
        "# chartlang primitive reference",
        "",
        "Generated from source JSDoc. Authoritative — do not hand-edit. Run",
        "`pnpm skills:generate` after changing a `ta.*` / `draw.*` / plot-family /",
        "`math.*` / `str.*` primitive.",
        "",
        "The chartlang compiler injects a leading `slotId: string` argument at",
        "every callsite, so script authors call `ta.<id>(...)` / `draw.<id>(...)`",
        "without it — the `ta.*` / `draw.*` signatures below show the runtime form",
        "including `slotId`. The plot-family holes (`plot` / `hline` / `bgcolor` /",
        "`barcolor`) are shown in the **author** form (no `slotId`) — that is how",
        "they are written; the compiler injects the slot id at the callsite.",
        "",
        "## ta.*",
        "",
        ta.map(renderTaBlock).join("\n\n"),
        "",
        "## draw.*",
        "",
        draw.map(renderDrawBlock).join("\n\n"),
        "",
        "## plot family",
        "",
        plotFamily.map(renderPlotBlock).join("\n\n"),
        "",
        renderNamespaceBlock("math", math),
        "",
        renderNamespaceBlock("str", str),
        "",
    ];
    return parts.join("\n");
}

/**
 * Generate the skills primitive reference. `check: true` byte-diffs the
 * regenerated content against the committed file (failing on drift,
 * like `gen-hover-registry.ts`); otherwise writes the file.
 */
export async function generateSkillsReference(
    opts: Readonly<{ check?: boolean }> = {},
): Promise<void> {
    const [ta, draw, plotFamily, math, str] = await Promise.all([
        collectTa(),
        collectDraw(),
        collectPlotFamily(),
        collectNamespace("math"),
        collectNamespace("str"),
    ]);
    const contents = renderReference(ta, draw, plotFamily, math, str);

    if (opts.check === true) {
        let existing = "";
        try {
            existing = await readFile(OUTPUT, "utf8");
        } catch {
            throw new Error(`Skills reference is missing: ${relative(REPO_ROOT, OUTPUT)}`);
        }
        if (existing !== contents) throw new Error(OUT_OF_DATE_MESSAGE);
        return;
    }

    await writeFile(OUTPUT, contents, "utf8");
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
    const check = process.argv.includes("--check");
    generateSkillsReference({ check }).catch((err: unknown) => {
        const message = err instanceof Error ? err.message : String(err);
        console.error(message);
        process.exitCode = 1;
    });
}
