// auto-generated by @invinite-org/chartlang-compiler
import type { CompiledScriptObject, ScriptManifest } from "@invinite-org/chartlang-core";

declare const script: CompiledScriptObject;
export default script;

export declare const __manifest: ScriptManifest;
