// auto-generated by @invinite-org/chartlang-compiler
import type { CompiledScriptObject, ScriptManifest, Series } from "@invinite-org/chartlang-core";

declare const script: CompiledScriptObject & {
    output<K extends "BB Upper" | "BB Middle" | "BB Lower">(name: K): Series<number>;
    withInputs(overrides: Readonly<Record<string, never>>): typeof script;
};
export default script;

export declare const __manifest: ScriptManifest;
