// auto-generated by @invinite-org/chartlang-compiler
import type { CompiledScriptObject, ScriptManifest, Series } from "@invinite-org/chartlang-core";

declare const script: CompiledScriptObject & {
    output<K extends "Target (raw)" | "Target (snapped)">(name: K): Series<number>;
    withInputs(overrides: Readonly<{ offsetPercent?: number }>): typeof script;
};
export default script;

export declare const __manifest: ScriptManifest;
