#!/usr/bin/env tsx
// Copyright (c) 2026 Invinite. Licensed under the MIT License.
// See the LICENSE file in the repo root for full license text.

/**
 * Bundle the QuickJS-side dispatcher into a single neutral ESM file. The bundle
 * text is consumed two ways from one source of truth (`bundleDispatcher()`):
 *
 *  1. `dist/dispatcher.js` — the historical on-disk artifact, still emitted for
 *     debugging and back-compat.
 *  2. `src/dispatcherSource.generated.ts` — a committed module exporting the
 *     same text as the `DISPATCHER_SOURCE` string constant. `createQuickJsHost`
 *     imports this constant instead of `readFileSync`-ing the file, so the
 *     runtime path has zero `node:fs` / `node:path` / `node:url` imports and
 *     loads in any runtime (Cloudflare Durable Object, browser, Node).
 *
 * The shared `bundleDispatcher` factory is also imported by
 * `src/dispatcherFreshness.test.ts` to regenerate the bundle in-memory and
 * assert byte-for-byte equality with the committed `dist/dispatcher.js` AND the
 * generated constant — stale-bundle detection. Keep the esbuild flags as the
 * single source of truth so the freshness gate cannot drift from the build
 * itself.
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import * as esbuild from "esbuild";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "..");

/**
 * Absolute path to the bundle entry — `src/dispatcher.ts`.
 */
export const DISPATCHER_ENTRY = resolve(ROOT, "src/dispatcher.ts");

/**
 * Absolute path to the committed bundle output — `dist/dispatcher.js`.
 */
export const DISPATCHER_OUTFILE = resolve(ROOT, "dist/dispatcher.js");

/**
 * Absolute path to the committed generated source module —
 * `src/dispatcherSource.generated.ts`. Emitted alongside `dist/dispatcher.js`
 * so `createQuickJsHost` can import the dispatcher text without touching the
 * filesystem at module scope.
 */
export const DISPATCHER_GENERATED_OUTFILE = resolve(ROOT, "src/dispatcherSource.generated.ts");

/**
 * Render the committed `src/dispatcherSource.generated.ts` module from the
 * bundle text. The body is a single JSON-stringified string literal, so the
 * freshness gate compares the parsed `DISPATCHER_SOURCE` value (not the file
 * text) and is immune to formatter churn.
 */
export function renderDispatcherSourceModule(bundle: string): string {
    return [
        "// Copyright (c) 2026 Invinite. Licensed under the MIT License.",
        "// See the LICENSE file in the repo root for full license text.",
        "",
        "// AUTO-GENERATED by scripts/buildDispatcher.ts — do not edit by hand.",
        "// Run `pnpm build:dispatcher` to regenerate. The dispatcherFreshness gate",
        "// fails if this constant drifts from `bundleDispatcher()`.",
        "",
        "/**",
        " * The QuickJS-side dispatcher bundle as a single neutral-ESM source string.",
        " * `createQuickJsHost` evaluates this once per context instead of reading",
        " * `dist/dispatcher.js`, so the runtime path has zero `node:fs` / `node:path`",
        " * / `node:url` imports and loads in any runtime (Cloudflare Durable Object,",
        " * browser, Node). Byte-identical to `dist/dispatcher.js` — both are emitted",
        " * from the same `bundleDispatcher()` source of truth.",
        " *",
        " * @since 1.5",
        " * @example",
        ' *     import { DISPATCHER_SOURCE } from "./dispatcherSource.generated";',
        " *     context.evalCode(DISPATCHER_SOURCE);",
        " */",
        `export const DISPATCHER_SOURCE = ${JSON.stringify(bundle)};`,
        "",
    ].join("\n");
}

/**
 * Frozen esbuild flag set. Shared between `pnpm build:dispatcher` and the
 * freshness gate; keeping a single source of truth means the test cannot
 * silently drift from the build.
 *
 * `sourcemap: false` and `minify: false` are load-bearing for determinism —
 * esbuild does not embed timestamps in plain bundles, so the output is
 * stable across runs as long as the inputs are stable. `absWorkingDir` is
 * pinned to the package root because esbuild's `// <path>` section comments
 * are cwd-relative; without the pin the bundle differs between `pnpm build`
 * (cwd = package dir) and the root vitest run (cwd = repo root), which made
 * the freshness gate fail spuriously.
 */
export const DISPATCHER_BUILD_OPTIONS = Object.freeze({
    entryPoints: [DISPATCHER_ENTRY],
    bundle: true,
    format: "esm" as const,
    platform: "neutral" as const,
    target: "es2020",
    sourcemap: false,
    minify: false,
    absWorkingDir: ROOT,
});

/**
 * Bundle the dispatcher into a UTF-8 string without writing it to disk.
 * Used by the freshness gate. Inherits every flag from
 * `DISPATCHER_BUILD_OPTIONS` and pins `write: false` so esbuild returns the
 * output via `outputFiles` instead.
 */
export async function bundleDispatcher(): Promise<string> {
    const result = await esbuild.build({
        ...DISPATCHER_BUILD_OPTIONS,
        write: false,
    });
    const files = result.outputFiles;
    if (files === undefined || files.length !== 1) {
        throw new Error(
            `expected exactly one output file, got ${files === undefined ? "undefined" : String(files.length)}`,
        );
    }
    const file = files[0];
    if (file === undefined) throw new Error("missing output file");
    return file.text;
}

const RUN_AS_SCRIPT = import.meta.url === `file://${process.argv[1]}`;

if (RUN_AS_SCRIPT) {
    // `--source-only` emits just the generated `.ts` module. The `build` script
    // runs this first so the constant `createQuickJsHost` imports exists before
    // `tsc` compiles `src/`. `tsc` also emits `dist/dispatcher.js` from
    // `src/dispatcher.ts` (same filename), so the default (full) run must come
    // AFTER `tsc` to leave the esbuild bundle — not tsc's per-file output — as
    // the committed `dist/dispatcher.js`. Both writes share one `bundle` string
    // so the on-disk artifact and the generated constant can never disagree.
    const sourceOnly = process.argv.includes("--source-only");
    const bundle = await bundleDispatcher();
    writeFileSync(DISPATCHER_GENERATED_OUTFILE, renderDispatcherSourceModule(bundle), "utf8");
    if (!sourceOnly) {
        mkdirSync(dirname(DISPATCHER_OUTFILE), { recursive: true });
        writeFileSync(DISPATCHER_OUTFILE, bundle, "utf8");
    }
}
